import {BrowserWindow,dialog,session} from 'electron';
import fs from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {relativePath} from './storage.mjs';
import {projectMime} from './project-store.mjs';

const failure=(code,message)=>Object.assign(new Error(message),{code,details:{},retryable:false});
export function attachProjectUI(projects,main,{qa=false,icon}={}){
  const previews=new Map(),filename=value=>{if(typeof value!=='string'||value.includes('/'))throw failure('E_INVALID_PATH','导出文件名无效。');try{return relativePath(value);}catch{throw failure('E_INVALID_PATH','导出文件名无效。');}};
  const deliver=async(owner,file,name)=>{const result=await dialog.showSaveDialog(main,{defaultPath:filename(name)});if(result.canceled)return {saved:false};projects.check(owner);const temp=result.filePath+'.vela-export-'+randomUUID();try{await fs.copyFile(file,temp);const fd=await fs.open(temp,'r+');try{await fd.sync();}finally{await fd.close();}await fs.rename(temp,result.filePath);return {saved:true,name:path.basename(result.filePath)};}catch{await fs.rm(temp,{force:true});throw failure('E_QUOTA','导出失败，项目原始数据已保留。');}};
  projects.pickHandler=async(owner,a)=>{const known=['png','jpg','jpeg','gif','webp','svg','avif','mp4','webm','ogg','oga','ogv','mp3','wav','woff','woff2','ttf','otf','zip','json','csv','tsv','txt','html','pdf'];const extensions=[...new Set((a.accept||[]).flatMap(type=>type.startsWith('.')?[type.slice(1)]:known.filter(ext=>type.endsWith('/*')?projectMime('x.'+ext).startsWith(type.slice(0,-1)):projectMime('x.'+ext)===type)))];const result=await dialog.showOpenDialog(main,{properties:a.multiple?['openFile','multiSelections']:['openFile'],...(extensions.length?{filters:[{name:'Project assets',extensions}]}:{})});if(result.canceled)return {cancelled:true,selections:[]};projects.check(owner);if(result.filePaths.length>100)throw failure('E_LIMIT','一次最多选择 100 个素材。');return {cancelled:false,selections:await Promise.all(result.filePaths.map(file=>projects.selection(owner,file)))};};
  projects.deliverHandler=async(owner,a)=>{const output=projects.owned(projects.outputs,a.outputToken,owner);projects.check(owner,a.taskId);try{const result=await deliver(owner,output.file,a.suggestedName);return {...result,...(result.saved?{bytes:output.size,sha256:output.sha256}:{})};}finally{await fs.rm(output.file,{force:true});projects.outputs.delete(a.outputToken);}};
  projects.exportFileHandler=async(owner,a)=>{const source=projects.file(a.root,a.path);if('r:'+await projects.hash(source)!==a.expectedRevision)throw failure('E_CONFLICT','文件在导出前已改变。');const temp=path.join(projects.temp,randomUUID());try{await fs.copyFile(source,temp);if('r:'+await projects.hash(temp)!==a.expectedRevision)throw failure('E_CONFLICT','导出期间文件已改变。');return await deliver(owner,temp,a.suggestedName);}finally{await fs.rm(temp,{force:true});}};
  const get=(owner,id)=>{const p=previews.get(id);if(!p||p.owner!==owner)throw failure('E_NOT_FOUND','试演不存在。');return p;};
  const event=(p,type,payload={})=>{p.events.push({type,payload});if(p.events.length>100)p.events.shift();};
  const prepare=async(owner,a)=>{const snapshot=projects.snapshotRecord(a.snapshotId);if(snapshot.owner!==a.pluginId)throw failure('E_PERMISSION','快照不属于此插件。');const assets=await projects.assetOpen(owner,{pluginId:a.pluginId,workspaceId:snapshot.workspaceId,root:snapshot.root,snapshotId:a.snapshotId,allowedRoots:[a.contentRoot||''],purpose:'preview'});return {snapshot,assets};};
  projects.previewHandler=async(action,owner,a)=>{
    if(action==='previewEvents'){const p=get(owner,a.previewId),events=p.events.splice(0);if(p.closed)previews.delete(a.previewId);return events;}
    if(action==='previewClose'){const p=get(owner,a.previewId);if(!p.closed)p.window.close();return true;}
    if(action==='previewReload'){const p=get(owner,a.previewId);if(p.closed)throw failure('E_NOT_FOUND','试演已关闭。');const prepared=await prepare(owner,{...p.args,snapshotId:a.snapshotId});projects.sessions.delete(p.assetSessionId);p.assetSessionId=prepared.assets.sessionId;p.args.snapshotId=a.snapshotId;await p.window.webContents.reload();return true;}
    const packageFiles=new Map();let packageBytes=0;for(const [name,data] of Object.entries(a.runtime?.files||{})){relativePath(name);if(typeof data!=='string')throw failure('E_INVALID_DATA','试演资源无效。');const bytes=Buffer.from(data,'base64');packageBytes+=bytes.length;if(packageBytes>8*1024*1024)throw failure('E_LIMIT','试演资源超过 8 MB。');packageFiles.set(name,bytes);}const runtime=Buffer.from(a.runtime?.data||'','base64');if(!runtime.length||runtime.length>8*1024*1024||!/^[-\w./\u0080-\uffff]+\.(?:html?|js)$/i.test(a.runtime?.path||''))throw failure('E_INVALID_DATA','试演入口无效。');const {assets}=await prepare(owner,a),previewId=randomUUID(),partition='vela-plugin-preview-'+previewId,isolated=session.fromPartition(partition),entryPath=/\.html?$/i.test(a.runtime.path)?a.runtime.path:'index.html',url='vela://preview/'+previewId+'/'+entryPath;
    const p={owner,args:a,assetSessionId:assets.sessionId,events:[],closed:false};previews.set(previewId,p);
    const policy="default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' vela: data:; media-src vela:; font-src 'self' vela: data:; connect-src 'self' vela:; worker-src 'self' blob:; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
    isolated.protocol.handle('vela',request=>{const u=new URL(request.url);if(u.hostname==='asset'){if(!u.pathname.startsWith('/'+p.assetSessionId+'/'))return new Response('',{status:403});return projects.resource(request);}if(u.hostname!=='preview'||!u.pathname.startsWith('/'+previewId+'/'))return new Response('',{status:403});const file=u.pathname.slice(previewId.length+2);if(file!==entryPath){const value=packageFiles.get(file)||((file===a.runtime.path&&/\.js$/i.test(file))?runtime:null);return value?new Response(value,{headers:{'Content-Type':projectMime(file),'Content-Security-Policy':policy,'X-Content-Type-Options':'nosniff'}}):new Response('',{status:404});}const initial=JSON.stringify({previewId,snapshotId:p.args.snapshotId,assetBase:'vela://asset/'+p.assetSessionId+'/',contentRoot:a.contentRoot||'',initialState:a.initialState||{}}).replaceAll('<','\\u003c');const entry=/\.js$/i.test(a.runtime.path)?'<!doctype html><meta charset="utf-8"><div id="app"></div><script src="'+a.runtime.path+'"></script>':runtime.toString('utf8');return new Response('<meta name="viewport" content="width=device-width,initial-scale=1"><script>window.VELA_PREVIEW='+initial+';</script>'+entry,{headers:{'Content-Type':'text/html','Content-Security-Policy':policy,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});});
    isolated.protocol.handle('https',()=>new Response('',{status:403}));isolated.protocol.handle('http',()=>new Response('',{status:403}));isolated.setPermissionRequestHandler((_web,_perm,done)=>done(false));isolated.setPermissionCheckHandler(()=>false);
    const window=new BrowserWindow({title:'Vela · 插件试演',width:Math.max(320,Math.min(1920,a.viewport?.width||1100)),height:Math.max(240,Math.min(1200,a.viewport?.height||800)),show:!qa,icon,autoHideMenuBar:true,webPreferences:{partition,nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});p.window=window;window.setMenu(null);window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-attach-webview',e=>e.preventDefault());window.webContents.on('will-navigate',(e,target)=>{if(target!==url)e.preventDefault();});window.webContents.on('did-finish-load',()=>event(p,'ready'));window.webContents.on('render-process-gone',()=>event(p,'error',{message:'试演进程已退出。'}));window.webContents.on('console-message',(_event,details)=>{if(details&&typeof details.message==='string')event(p,'trace',{message:details.message.slice(0,4096)});});window.on('closed',()=>{p.closed=true;event(p,'closed');projects.sessions.delete(p.assetSessionId);isolated.clearStorageData().catch(()=>{});});await window.loadURL(url);return {previewId};
  };
  projects.previewStop=async owner=>{for(const [id,p] of previews)if(p.owner===owner){if(!p.closed)p.window.close();previews.delete(id);}};
  return ()=>{for(const p of previews.values())if(!p.closed)p.window.close();};
}
