import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {Readable,Transform} from 'node:stream';
import {pipeline} from 'node:stream/promises';
import {createInflateRaw} from 'node:zlib';
import {relativePath,atomic,mime as oldMime} from './storage.mjs';

const MB=1024*1024,chunkBytes=256*1024,contains=(root,p)=>!root||p===root||p.startsWith(root+'/');
const fail=(code,message,details={})=>Object.assign(new Error(message),{code,details,retryable:code==='E_CONFLICT'});
const uuid=value=>typeof value==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(value);
export const projectMime=p=>({mp4:'video/mp4',webm:'video/webm',ogg:'audio/ogg',oga:'audio/ogg',ogv:'video/ogg',mp3:'audio/mpeg',wav:'audio/wav',csv:'text/csv',tsv:'text/tab-separated-values',zip:'application/zip'}[p.split('.').at(-1).toLowerCase()]||oldMime(p));
const crcTable=Uint32Array.from({length:256},(_,i)=>{for(let j=0;j<8;j++)i=i&1?0xedb88320^(i>>>1):i>>>1;return i>>>0;});
const crcUpdate=(crc,bytes)=>{for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return crc>>>0;};
export class ProjectStore {
  constructor(store){this.store=store;this.base=path.join(store.base,'project-data');this.temp=path.join(this.base,'sessions');this.objects=path.join(this.base,'objects');this.snapshots=path.join(this.base,'snapshots');this.blobs=new Map();this.selections=new Map();this.archives=new Map();this.sessions=new Map();this.outputs=new Map();this.cancelled=new Set();this.stopped=new Set();this.hashes=new Map();this.busy=false;for(const dir of [this.temp,this.objects,this.snapshots])fs.mkdirSync(dir,{recursive:true});for(const name of fs.readdirSync(this.temp))fs.rmSync(path.join(this.temp,name),{recursive:true,force:true});}
  check(owner,taskId){if(this.stopped.has(owner))throw fail('E_PLUGIN_STOPPED','插件已停用。');if(taskId&&this.cancelled.has(owner+':'+taskId))throw fail('E_CANCELLED','任务已取消。');}
  capabilities(){return {limits:{textBytes:8*MB,readChunkBytes:chunkBytes,bridgeChunkBytes:chunkBytes,importFileBytes:512*MB,projectEntries:5000,archiveExpandedBytes:1024*MB,archiveEntries:5000,projectBytes:2*1024*MB,snapshotBytes:2*1024*MB},resource:{range:true,worker:true,canvas2d:true},features:{filesystem:true,transactions:true,assetSessions:true,archives:true,snapshots:true,nativePicker:true,independentPreview:true,externalWatch:false}};}
  root(value=''){if(!value)return this.store.root;try{return this.store.target(relativePath(value));}catch{throw fail('E_INVALID_PATH','项目相对路径无效。');}}
  file(root,relative,empty=false){if(!relative&&empty)return this.root(root);if(!relative)throw fail('E_INVALID_PATH','文件路径不能为空。');return this.root((root?root+'/':'')+relative);}
  owned(map,id,owner){const value=map.get(id);if(!value||value.owner!==owner)throw fail('E_NOT_FOUND','会话或暂存对象不存在。');value.expires=Date.now()+30*60000;return value;}
  async hash(file){const s=await fsp.stat(file),key=[s.size,s.mtimeMs,s.ctimeMs,s.ino].join(':');if(this.hashes.get(file)?.key===key)return this.hashes.get(file).value;const h=createHash('sha256');for await(const bytes of fs.createReadStream(file))h.update(bytes);const value=h.digest('hex');this.hashes.set(file,{key,value});return value;}
  async tree(root){const entries=[];let total=0;const walk=async relative=>{const folder=this.file(root,relative,true);for(const name of (await fsp.readdir(folder)).sort()){
    if(name==='.git'||/\.(vela|wenzhou)-tmp$/.test(name))continue;const p=relative?relative+'/'+name:name,file=this.file(root,p),s=await fsp.lstat(file);if(s.isSymbolicLink())throw fail('E_INVALID_PATH','项目包含符号链接。');if(entries.length>=5000)throw fail('E_LIMIT','项目超过条目限制。',{limit:5000});
    const entry={path:p,kind:s.isDirectory()?'directory':'file',size:s.isDirectory()?0:s.size,mime:s.isDirectory()?'inode/directory':projectMime(p),modifiedAt:new Date(s.mtimeMs).toISOString()};entries.push(entry);
    if(s.isDirectory())await walk(p);else if(s.isFile()){total+=s.size;if(total>2*1024*MB)throw fail('E_LIMIT','项目超过容量限制。');entry.revision='r:'+await this.hash(file);}else throw fail('E_INVALID_DATA','项目包含不可用的文件类型。');
  }};await walk('');for(const e of [...entries].reverse())if(e.kind==='directory')e.revision='r:'+createHash('sha256').update(JSON.stringify(entries.filter(child=>contains(e.path,child.path)&&child!==e).map(({path,revision})=>[path,revision]))).digest('hex');return {entries,totalBytes:total};}
  async begin(owner,a){if(this.blobs.size>=5000||[...this.blobs.values()].reduce((n,b)=>n+b.size,0)+a.size>2*1024*MB)throw fail('E_QUOTA','待处理素材已达到数量或容量上限。');if(!Number.isSafeInteger(a.size)||a.size<0||a.size>512*MB)throw fail('E_LIMIT','素材超过单文件限制。',{limit:512*MB});if(a.sha256&&!/^[a-f0-9]{64}$/i.test(a.sha256))throw fail('E_INVALID_DATA','SHA-256 格式无效。');const blobId=randomUUID(),file=path.join(this.temp,blobId);await fsp.writeFile(file,Buffer.alloc(0));this.blobs.set(blobId,{owner,root:a.root,file,size:a.size,mime:a.mime||'application/octet-stream',expectedHash:a.sha256?.toLowerCase(),written:0,sequence:0,hash:createHash('sha256'),expires:Date.now()+30*60000});return {blobId,maxChunkBytes:chunkBytes};}
  async chunk(owner,a){const b=this.owned(this.blobs,a.blobId,owner);if(b.complete)throw fail('E_INVALID_DATA','暂存已经完成。');if(typeof a.data!=='string'||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(a.data))throw fail('E_INVALID_DATA','块编码无效。');const data=Buffer.from(a.data,'base64'),digest=createHash('sha256').update(data).digest('hex');if(a.sequence===b.sequence-1&&b.last===digest)return {acceptedBytes:b.written,nextSequence:b.sequence};if(a.sequence!==b.sequence||data.length>chunkBytes||b.written+data.length>b.size)throw fail('E_INVALID_DATA','块序号或大小无效。');await fsp.appendFile(b.file,data);b.hash.update(data);b.written+=data.length;b.sequence++;b.last=digest;return {acceptedBytes:b.written,nextSequence:b.sequence};}
  async finish(owner,a){const b=this.owned(this.blobs,a.blobId,owner);if(!b.complete){if(b.written!==b.size)throw fail('E_INVALID_DATA','暂存大小不匹配。');b.sha256=b.hash.digest('hex');if(b.expectedHash&&b.sha256!==b.expectedHash)throw fail('E_INVALID_DATA','素材摘要不匹配。');const handle=await fsp.open(b.file,'r+');try{await handle.sync();}finally{await handle.close();}b.complete=true;}return {blobId:a.blobId,size:b.size,sha256:b.sha256};}
  async abort(owner,a){const b=this.owned(this.blobs,a.blobId,owner);if(path.dirname(b.file)===this.temp)await fsp.rm(b.file,{force:true});this.blobs.delete(a.blobId);return true;}
  async read(owner,a){const file=a.snapshotId?this.snapshotFile(owner,a.snapshotId,a.path):this.file(a.root,a.path),s=await fsp.stat(file);if(!s.isFile())throw fail('E_INVALID_DATA','目标不是文件。');const rev='r:'+await this.hash(file);if(a.expectedRevision&&a.expectedRevision!==rev)throw fail('E_CONFLICT','文件已改变。',{path:a.path});const offset=a.offset??0,length=a.length??Math.min(chunkBytes,s.size-offset);if(!Number.isSafeInteger(offset)||offset<0||offset>s.size||!Number.isSafeInteger(length)||length<0||length>chunkBytes)throw fail('E_LIMIT','分块读取范围无效。',{limit:chunkBytes});const buffer=Buffer.alloc(Math.min(length,s.size-offset)),fd=await fsp.open(file,'r');try{await fd.read(buffer,0,buffer.length,offset);}finally{await fd.close();}if('r:'+await this.hash(file)!==rev)throw fail('E_CONFLICT','读取期间文件已改变。',{path:a.path});return {data:buffer.toString('base64'),revision:rev,totalSize:s.size};}
  async apply(owner,a){if(this.busy)throw fail('E_CONFLICT','项目正在提交，请稍后重试。');this.busy=true;try{
    const current=await this.tree(a.root),byPath=new Map(current.entries.map(e=>[e.path,e]));for(const e of a.expected||[]){if((byPath.get(e.path)?.revision??null)!==e.revision)throw fail('E_CONFLICT','磁盘文件已改变。',{path:e.path});}
    if(typeof a.workspace!=='string'||Buffer.byteLength(a.workspace)>64*MB)throw fail('E_LIMIT','工作区索引过大。');const workspace=JSON.parse(a.workspace);if(workspace.storage?.id!==this.store.id)throw fail('E_INVALID_DATA','内部文件夹标识不匹配。');
    const changes=a.changes||[];if(changes.length>5000)throw fail('E_LIMIT','批量操作过多。');for(const c of changes){this.file(a.root,c.path||c.from);if(c.to)this.file(a.root,c.to);if(c.kind==='writeBlob'){const b=this.owned(this.blobs,c.blobId,owner);if(!b.complete||b.root!==a.root)throw fail('E_INVALID_DATA','素材尚未完成或不属于此项目。');}if(c.kind==='writeText'&&(typeof c.text!=='string'||Buffer.byteLength(c.text)>8*MB))throw fail('E_LIMIT','文本超过 8 MB。');}
    // The existing durable journal covers payload files and both document indexes.
    const result=this.store.transaction(tx=>{const records=this.store.records();for(const c of changes){const target=this.file(a.root,c.path||c.from);if(c.kind==='mkdir')tx.mkdir(target);else if(c.kind==='writeText')tx.write(target,c.text);else if(c.kind==='writeBlob')tx.install(this.owned(this.blobs,c.blobId,owner).file,target);else if(c.kind==='move'){const dest=this.file(a.root,c.to);if(fs.existsSync(dest))throw fail('E_EXISTS','移动目标已存在。');tx.copy(target,dest);tx.remove(target);}else if(c.kind==='delete'){if(records.length>=100)throw fail('E_LIMIT','回收站已满。');const id=randomUUID(),full=(a.root?a.root+'/':'')+c.path;records.push({id,path:full,directory:fs.statSync(target).isDirectory(),createdAt:Date.now(),documents:(a.removedDocuments||[]).filter(d=>contains(full,d.path||d.name)),repositories:[]});tx.copy(target,path.join(this.store.base,'trash-payload',id));tx.remove(target);}else throw fail('E_INVALID_DATA','批量操作类型无效。');}tx.write(this.store.trash,JSON.stringify(records));tx.write(this.store.cache,a.workspace);tx.write(this.store.workspace,a.workspace);return {committed:true};});return result;
  }finally{this.busy=false;}}
  snapshotRecord(id){if(!uuid(id))throw fail('E_NOT_FOUND','快照不存在。');const file=path.join(this.snapshots,id+'.json');if(!fs.existsSync(file))throw fail('E_NOT_FOUND','快照不存在。');return JSON.parse(fs.readFileSync(file,'utf8'));}
  snapshotFile(owner,id,p){const record=this.snapshotRecord(id);if(record.owner!==owner)throw fail('E_PERMISSION','快照不属于此插件。');relativePath(p);const entry=record.entries.find(e=>e.path===p&&e.kind==='file');if(!entry)throw fail('E_NOT_FOUND','文件未包含在快照中。');return path.join(this.objects,entry.revision.slice(2));}
  async snapshotCreate(owner,a){const tree=await this.tree(a.root),roots=a.includeRoots||[];for(const r of roots)if(r)relativePath(r);const entries=tree.entries.filter(e=>roots.some(r=>contains(r,e.path))),before=JSON.stringify(tree.entries.map(e=>[e.path,e.revision]));let size=0;for(const e of entries.filter(e=>e.kind==='file')){size+=e.size;const source=this.file(a.root,e.path),dest=path.join(this.objects,e.revision.slice(2));if(!fs.existsSync(dest)){const temp=path.join(this.temp,randomUUID());await fsp.copyFile(source,temp);if('r:'+await this.hash(temp)!==e.revision){await fsp.rm(temp);throw fail('E_CONFLICT','快照创建期间文件已修改。');}await fsp.rename(temp,dest);}}
    this.check(owner,a.taskId);if(before!==JSON.stringify((await this.tree(a.root)).entries.map(e=>[e.path,e.revision])))throw fail('E_CONFLICT','快照创建期间项目已改变。');const ids=new Map((a.entries||[]).map(e=>[e.path,e.entryId]));const snapshotId=randomUUID(),record={id:snapshotId,owner:a.pluginId||owner,workspaceId:a.workspaceId,root:a.root,includeRoots:roots,label:String(a.label||'').slice(0,200),createdAt:new Date().toISOString(),bytes:size,entries:entries.map(e=>({...e,entryId:ids.get(e.path)})),workspace:a.workspace};atomic(path.join(this.snapshots,snapshotId+'.json'),JSON.stringify(record));return {snapshotId,bytes:size};}
  async selection(owner,file){const s=await fsp.lstat(file);if(!s.isFile()||s.isSymbolicLink())throw fail('E_INVALID_DATA','请选择普通文件。');if(s.size>512*MB)throw fail('E_LIMIT','素材超过单文件限制。',{limit:512*MB});const token=randomUUID(),name=path.basename(file);this.selections.set(token,{owner,file,size:s.size,name,mime:projectMime(name),revision:'r:'+await this.hash(file),expires:Date.now()+30*60000});return {token,name,size:s.size,mime:projectMime(name)};}
  async selectionStage(owner,a){this.check(owner,a.taskId);const s=this.owned(this.selections,a.token,owner),b=await this.begin(owner,{root:a.root,size:s.size,mime:s.mime}),record=this.owned(this.blobs,b.blobId,owner);await fsp.copyFile(s.file,record.file);this.check(owner,a.taskId);const sha=await this.hash(record.file);if('r:'+sha!==s.revision){await this.abort(owner,b);throw fail('E_CONFLICT','选中的文件已改变。');}Object.assign(record,{complete:true,sha256:sha,written:s.size});this.selections.delete(a.token);return {blobId:b.blobId,size:s.size,sha256:sha};}
  async archiveInspect(owner,a){this.check(owner,a.taskId);const selection=this.owned(this.selections,a.selectionToken,owner),handle=await fsp.open(selection.file,'r');try{
    const size=selection.size;if(size<22)throw fail('E_INVALID_DATA','ZIP 容器不完整。');const tail=Buffer.alloc(Math.min(size,65557));await handle.read(tail,0,tail.length,size-tail.length);let at=tail.length-22;while(at>=0&&(tail.readUInt32LE(at)!==0x06054b50||at+22+tail.readUInt16LE(at+20)!==tail.length))at--;if(at<0)throw fail('E_INVALID_DATA','ZIP 目录不存在。');if(tail.readUInt16LE(at+4)||tail.readUInt16LE(at+6)||tail.readUInt16LE(at+8)!==tail.readUInt16LE(at+10))throw fail('E_INVALID_DATA','不支持分卷 ZIP。');const count=tail.readUInt16LE(at+10),length=tail.readUInt32LE(at+12),offset=tail.readUInt32LE(at+16);if(count===65535||offset===0xffffffff||length===0xffffffff)throw fail('E_UNSUPPORTED','首版不支持 ZIP64。');if(count>5000||length>16*MB||offset+length>size-tail.length+at)throw fail('E_LIMIT','ZIP 目录超过限制或损坏。');
    const central=Buffer.alloc(length);await handle.read(central,0,length,offset);let i=0,total=0;const entries=[],seen=new Set();for(let n=0;n<count;n++){
      this.check(owner,a.taskId);if(i+46>length||central.readUInt32LE(i)!==0x02014b50)throw fail('E_INVALID_DATA','ZIP 目录损坏。');const flags=central.readUInt16LE(i+8),method=central.readUInt16LE(i+10),crc=central.readUInt32LE(i+16),compressedSize=central.readUInt32LE(i+20),expanded=central.readUInt32LE(i+24),nl=central.readUInt16LE(i+28),el=central.readUInt16LE(i+30),cl=central.readUInt16LE(i+32),attrs=central.readUInt32LE(i+38),local=central.readUInt32LE(i+42);if(flags&1||![0,8].includes(method)||(attrs>>>16&0xf000)===0xa000||(attrs>>>16&0xf000)&&![0x4000,0x8000].includes(attrs>>>16&0xf000)||expanded===0xffffffff||compressedSize===0xffffffff||local===0xffffffff)throw fail('E_INVALID_DATA','ZIP 含加密、链接或不支持的文件。');if(i+46+nl+el+cl>length)throw fail('E_INVALID_DATA','ZIP 路径损坏。');const raw=central.subarray(i+46,i+46+nl);if(!(flags&2048)&&raw.some(b=>b>127))throw fail('E_UNSUPPORTED','请使用 UTF-8 编码的 ZIP 文件名。');let name;try{name=new TextDecoder('utf-8',{fatal:true}).decode(raw);}catch{throw fail('E_INVALID_DATA','ZIP 路径编码无效。');}const directory=name.endsWith('/'),relative=directory?name.slice(0,-1):name;try{relativePath(relative);}catch{throw fail('E_INVALID_PATH','ZIP 含越界路径。');}const key=relative.normalize('NFC').toLowerCase();if(seen.has(key))throw fail('E_INVALID_DATA','ZIP 路径重复或大小写冲突。');seen.add(key);if(expanded>512*MB||(total+=expanded)>1024*MB)throw fail('E_LIMIT','ZIP 展开大小超过限制。');if(directory&&(expanded||compressedSize))throw fail('E_INVALID_DATA','目录带有文件内容。');entries.push({path:relative,size:expanded,compressedSize,directory,method,crc,local});i+=46+nl+el+cl;
    }if(i!==length)throw fail('E_INVALID_DATA','ZIP 目录长度不匹配。');for(const e of entries){let parent=path.posix.dirname(e.path);while(parent!=='.'){if(entries.some(other=>other.path.toLowerCase()===parent.toLowerCase()&&!other.directory))throw fail('E_INVALID_DATA','ZIP 文件与父目录冲突。');parent=path.posix.dirname(parent);}}
    const archiveToken=randomUUID();this.archives.set(archiveToken,{owner,file:selection.file,revision:selection.revision,entries,expandedBytes:total,expires:Date.now()+30*60000});return {archiveToken,entries:entries.map(({path,size,compressedSize,directory})=>({path,size,compressedSize,directory})),expandedBytes:total,warnings:[]};
  }finally{await handle.close();}}
  async extract(owner,archive,entry,destination,taskId){if('r:'+await this.hash(archive.file)!==archive.revision)throw fail('E_CONFLICT','ZIP 源文件已改变。');const fd=await fsp.open(archive.file,'r'),header=Buffer.alloc(30);let offset;try{await fd.read(header,0,30,entry.local);if(header.readUInt32LE(0)!==0x04034b50||header.readUInt16LE(8)!==entry.method)throw fail('E_INVALID_DATA','ZIP 本地头不匹配。');const nl=header.readUInt16LE(26),el=header.readUInt16LE(28);const name=Buffer.alloc(nl);await fd.read(name,0,nl,entry.local+30);if(name.toString('utf8').replace(/\/$/,'')!==entry.path)throw fail('E_INVALID_DATA','ZIP 本地路径不匹配。');offset=entry.local+30+nl+el;}finally{await fd.close();}let size=0,crc=0xffffffff;const guard=new Transform({transform:(chunk,_enc,done)=>{try{this.check(owner,taskId);size+=chunk.length;if(size>entry.size)throw fail('E_LIMIT','ZIP 虚报展开大小。');crc=crcUpdate(crc,chunk);done(null,chunk);}catch(e){done(e);}}});const input=entry.compressedSize?fs.createReadStream(archive.file,{start:offset,end:offset+entry.compressedSize-1}):Readable.from([]);await pipeline(...[input,...(entry.method===8?[createInflateRaw()]:[]),guard,fs.createWriteStream(destination)]);if(size!==entry.size||((crc^0xffffffff)>>>0)!==entry.crc)throw fail('E_INVALID_DATA','ZIP 大小或 CRC 校验失败。');}
  async archiveStage(owner,a){const archive=this.owned(this.archives,a.archiveToken,owner),entries=[],created=[];try{for(const e of archive.entries){this.check(owner,a.taskId);if(e.directory){entries.push({path:e.path,directory:true});continue;}const result=await this.begin(owner,{root:a.root,size:e.size,mime:projectMime(e.path)});created.push(result.blobId);const b=this.owned(this.blobs,result.blobId,owner);await this.extract(owner,archive,e,b.file,a.taskId);const sha=await this.hash(b.file);Object.assign(b,{complete:true,sha256:sha,written:e.size});entries.push({path:e.path,blobId:result.blobId,size:e.size,sha256:sha,directory:false});}return {entries};}catch(cause){for(const blobId of created)await this.abort(owner,{blobId});throw cause;}}
  async archiveRead(owner,a){const archive=this.owned(this.archives,a.archiveToken,owner),entry=archive.entries.find(e=>e.path===a.path&&!e.directory);if(!entry)throw fail('E_NOT_FOUND','归档中不存在此文件。');if(entry.size>Math.min(8*MB,a.maxBytes||8*MB))throw fail('E_LIMIT','预检文本超过限制。');const file=path.join(this.temp,randomUUID());try{await this.extract(owner,archive,entry,file,a.taskId);return {data:(await fsp.readFile(file)).toString('base64')};}finally{await fsp.rm(file,{force:true});}}
  async archiveExport(owner,a){const record=this.snapshotRecord(a.snapshotId);if(record.owner!==a.pluginId)throw fail('E_PERMISSION','快照不属于此插件。');if(a.root)relativePath(a.root);const full=p=>(a.root?a.root+'/':'')+relativePath(p),whitelist=a.paths.map(full),entries=record.entries.filter(e=>whitelist.some(p=>contains(p,e.path))).sort((x,y)=>x.path.localeCompare(y.path));if(!entries.length)throw fail('E_NOT_FOUND','快照中未包含导出文件。');for(const p of whitelist)if(!entries.some(e=>e.path===p))throw fail('E_NOT_FOUND','导出白名单中有缺失文件。',{path:p});const outputToken=randomUUID(),file=path.join(this.temp,outputToken),out=await fsp.open(file,'w'),central=[];let offset=0;const write=async data=>{let written=0;while(written<data.length){const part=await out.write(data,written,data.length-written,offset+written);if(!part.bytesWritten)throw fail('E_QUOTA','归档写入不完整。');written+=part.bytesWritten;}offset+=data.length;};try{
    for(const e of entries){this.check(owner,a.taskId);const relative=e.path.slice(a.root?a.root.length+1:0)+(e.kind==='directory'?'/':''),name=Buffer.from(relative);let crc=0xffffffff;const source=e.kind==='file'?this.snapshotFile(a.pluginId,a.snapshotId,e.path):null;if(source)for await(const chunk of fs.createReadStream(source)){this.check(owner,a.taskId);crc=crcUpdate(crc,chunk);}crc=(crc^0xffffffff)>>>0;const position=offset,local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(2048,6);local.writeUInt16LE(33,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(e.size,18);local.writeUInt32LE(e.size,22);local.writeUInt16LE(name.length,26);await write(local);await write(name);if(source)for await(const chunk of fs.createReadStream(source)){this.check(owner,a.taskId);await write(chunk);}const dir=Buffer.alloc(46);dir.writeUInt32LE(0x02014b50);dir.writeUInt16LE(20,4);dir.writeUInt16LE(20,6);dir.writeUInt16LE(2048,8);dir.writeUInt16LE(33,14);dir.writeUInt32LE(crc,16);dir.writeUInt32LE(e.size,20);dir.writeUInt32LE(e.size,24);dir.writeUInt16LE(name.length,28);dir.writeUInt32LE(e.kind==='directory'?16:0,38);dir.writeUInt32LE(position,42);central.push(Buffer.concat([dir,name]));}
    const start=offset;for(const dir of central)await write(dir);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(offset-start,12);end.writeUInt32LE(start,16);await write(end);await out.sync();
  }catch(cause){await out.close();await fsp.rm(file,{force:true});throw cause;}await out.close();const sha256=await this.hash(file);this.outputs.set(outputToken,{owner,file,size:offset,sha256,expires:Date.now()+30*60000});return {outputToken,bytes:offset,sha256};}
  async assetOpen(owner,a){if(!Array.isArray(a.allowedRoots)||!a.allowedRoots.length)throw fail('E_INVALID_DATA','资源授权范围不能为空。');for(const r of a.allowedRoots)if(r)relativePath(r);if(a.snapshotId){const record=this.snapshotRecord(a.snapshotId);if(record.owner!==a.pluginId||record.workspaceId!==a.workspaceId)throw fail('E_PERMISSION','快照不属于此项目。');}const sessionId=randomUUID();this.sessions.set(sessionId,{...a,owner,expires:Date.now()+30*60000});return {sessionId};}
  assetFile(s,p){relativePath(p);if(!s.allowedRoots.some(root=>contains(root,p)))throw fail('E_PERMISSION','资源越过授权目录。');return s.snapshotId?this.snapshotFile(s.pluginId,s.snapshotId,p):this.file(s.root,p);}
  async assetResolve(owner,a){const s=this.owned(this.sessions,a.sessionId,owner),file=this.assetFile(s,a.path),stat=await fsp.stat(file),revision='r:'+await this.hash(file);if(a.expectedRevision&&a.expectedRevision!==revision)throw fail('E_CONFLICT','资源已改变。');return {url:'vela://asset/'+a.sessionId+'/'+a.path.split('/').map(encodeURIComponent).join('/'),mime:projectMime(a.path),size:stat.size,revision,supportsRange:true};}
  async resource(request){try{const url=new URL(request.url),parts=url.pathname.slice(1).split('/'),id=parts.shift(),s=this.sessions.get(id);if(!s)return new Response('',{status:403});const relative=parts.map(decodeURIComponent).join('/'),file=this.assetFile(s,relative),stat=await fsp.stat(file);if(!stat.isFile())return new Response('',{status:404});let start=0,end=stat.size-1,status=200;const headers={'Content-Type':projectMime(relative),'Accept-Ranges':'bytes','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Access-Control-Allow-Origin':['vela://editor','vela://preview'].includes(request.headers.get('Origin'))?request.headers.get('Origin'):'vela://editor','Vary':'Origin','Access-Control-Expose-Headers':'Content-Range,Content-Length,Accept-Ranges','Content-Security-Policy':"sandbox; default-src 'none'; script-src 'none'"};const range=request.headers.get('Range');if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||!m[1]&&!m[2])return new Response('',{status:416,headers:{'Content-Range':'bytes */'+stat.size}});if(!m[1])start=Math.max(0,stat.size-Number(m[2]));else start=Number(m[1]);if(m[1]&&m[2])end=Math.min(end,Number(m[2]));if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start> end||start>=stat.size)return new Response('',{status:416,headers:{'Content-Range':'bytes */'+stat.size}});status=206;headers['Content-Range']=`bytes ${start}-${end}/${stat.size}`;}headers['Content-Length']=String(Math.max(0,end-start+1));return new Response(request.method==='HEAD'||!stat.size?null:Readable.toWeb(fs.createReadStream(file,{start,end})),{status,headers});}catch{return new Response('',{status:403});}}
  async stop(owner){this.stopped.add(owner);for(const [id,b] of this.blobs)if(b.owner===owner){if(b.file.startsWith(this.temp+path.sep))if(path.dirname(b.file)===this.temp)await fsp.rm(b.file,{force:true});this.blobs.delete(id);}for(const [id,s] of this.outputs)if(s.owner===owner){await fsp.rm(s.file,{force:true});this.outputs.delete(id);}for(const map of [this.selections,this.archives,this.sessions])for(const [id,s] of map)if(s.owner===owner)map.delete(id);await this.previewStop?.(owner);return true;}
  async call(action,owner,a){if(!uuid(owner))throw fail('E_PERMISSION','插件会话无效。');for(const [id,b] of this.blobs)if(b.expires<Date.now()){if(path.dirname(b.file)===this.temp)await fsp.rm(b.file,{force:true});this.blobs.delete(id);}
    switch(action){case 'receipt':while(this.busy)await new Promise(resolve=>setTimeout(resolve,20));return this.store.readWorkspace();case 'capabilities':return this.capabilities();case 'tree':return this.tree(a.root);case 'begin':return this.begin(owner,a);case 'chunk':return this.chunk(owner,a);case 'finish':return this.finish(owner,a);case 'abort':return this.abort(owner,a);case 'read':return this.read(a.pluginId||owner,a);case 'apply':return this.apply(owner,a);case 'stop':return this.stop(owner);case 'cancel':this.cancelled.add(owner+':'+a.taskId);return true;case 'pick':return this.pickHandler(owner,a);case 'selectionStage':return this.selectionStage(owner,a);case 'archiveInspect':return this.archiveInspect(owner,a);case 'archiveRead':return this.archiveRead(owner,a);case 'archiveStage':return this.archiveStage(owner,a);case 'archiveExport':return this.archiveExport(owner,a);case 'discardOutput':{const output=this.outputs.get(a.outputToken);if(output?.owner===owner){await fsp.rm(output.file,{force:true});this.outputs.delete(a.outputToken);}return true;}case 'deliver':return this.deliverHandler(owner,a);case 'exportFile':return this.exportFileHandler(owner,a);case 'assetOpen':return this.assetOpen(owner,a);case 'assetResolve':return this.assetResolve(owner,a);case 'assetRelease':this.owned(this.sessions,a.sessionId,owner);this.sessions.delete(a.sessionId);return true;case 'previewOpen':case 'previewReload':case 'previewClose':case 'previewEvents':return this.previewHandler(action,owner,a);case 'snapshotCreate':return this.snapshotCreate(owner,a);case 'snapshotList':{const values=[];for(const file of await fsp.readdir(this.snapshots)){const record=JSON.parse(await fsp.readFile(path.join(this.snapshots,file),'utf8'));if(record.workspaceId===a.workspaceId&&record.owner===(a.pluginId||owner))values.push({id:record.id,label:record.label,createdAt:record.createdAt,bytes:record.bytes});}return values.sort((x,y)=>y.createdAt.localeCompare(x.createdAt));}case 'snapshotEntries':{const record=this.snapshotRecord(a.snapshotId);if(record.owner!==(a.pluginId||owner)||record.workspaceId!==a.workspaceId)throw fail('E_PERMISSION','快照不属于此项目。');return record;}case 'snapshotStage':{const record=this.snapshotRecord(a.snapshotId);if(record.owner!==a.pluginId||record.workspaceId!==a.workspaceId)throw fail('E_PERMISSION','快照不属于此项目。');const entries=[];for(const e of record.entries){this.check(owner,a.taskId);if(e.kind==='directory'){entries.push(e);continue;}const blobId=randomUUID();this.blobs.set(blobId,{owner,root:a.root,file:this.snapshotFile(a.pluginId,a.snapshotId,e.path),size:e.size,sha256:e.revision.slice(2),complete:true,expires:Date.now()+30*60000});entries.push({...e,blobId});}return {entries};}default:throw fail('E_UNSUPPORTED','当前平台不支持此项目操作。');}
  }
}
