import {openRecentFile} from './start-page-helper.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {zipSync,strToU8} from 'fflate';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import {createVelaV2,velaText} from '../web/vela.mjs';
const root=path.resolve('dist/web'),server=http.createServer(async(req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const contents=await readFile(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.wasm':'application/wasm','.mjs':'text/javascript'}[path.extname(file)]||'application/octet-stream'}).end(contents);}catch{res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const baseURL=process.env.VELA_TEST_URL||'http://127.0.0.1:'+server.address().port;
const launch={headless:true,...(process.env.WENZHOU_CHROME?{executablePath:process.env.WENZHOU_CHROME}:{})};
const browser=await chromium.launch(launch),page=await browser.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route(/^https?:\/\/(?!127\.0\.0\.1|localhost)/,route=>route.abort());
const config=createVelaV2('书籍测试');
await page.addInitScript(text=>{if(window.top!==window)return;if(!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify({version:1,documents:[{id:'config',name:'.vela',path:'Books/.vela',text,updatedAt:1},{id:'tex',name:'main.tex',path:'Books/main.tex',text:'\\documentclass{article}\\begin{document}hello\\end{document}',updatedAt:1}],settings:{theme:'light'},activeId:'tex',openIds:['tex']}));},velaText(config));
const open=async()=>{await page.goto(baseURL);await openRecentFile(page,page.locator('[data-recent=tex]'));await page.locator('#more-tools').click();await page.locator('#plugins').click();};
const card=id=>page.locator('.plugin-card').filter({hasText:id});
const install=async path=>{await page.locator('#plugin-input').setInputFiles(path);};
const waitCard=async id=>{await card(id).waitFor();};
const engine='vela.component.tex.engine',chinese='vela.component.tex.chinese',ebook='vela.component.ebook-reader';
await mkdir('test-results/components',{recursive:true});
try{
 await open();assert.equal(await page.locator('#tex-components-status').count(),0);
 // Legacy migration: populate resources with the old API, without manager records.
 const descriptor=JSON.parse(await readFile('dist/web/tex/components.json','utf8'));
 assert.equal(descriptor.builtin,false,'Run this suite against a lite build');
 await page.evaluate(async descriptor=>{await new Promise((resolve,reject)=>{const request=indexedDB.open('vela.tex-components',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>{const db=request.result,tx=db.transaction('files','readwrite');for(const name of descriptor.groups.engine)tx.objectStore('files').put(new Uint8Array(),descriptor.id+'/'+name);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=reject;};});},descriptor);
 await open();await waitCard(engine);assert.match(await card(engine).textContent(),/已启用/);console.log('PASS existing component resources migrate into the plugin list');
 await install('dist/tex-components/Vela-TeX-0.1.1-engine.zip');await page.waitForFunction(()=>document.querySelector('#toast').textContent==='离线排版组件已安装。');
 await install('dist/tex-components/Vela-TeX-0.1.1-chinese.zip');await waitCard(chinese);
 await card(engine).locator('[data-plugin-enable]').click();await page.waitForFunction(()=>[...document.querySelectorAll('.plugin-card')].find(c=>c.textContent.includes('vela.component.tex.engine'))?.textContent.includes('已停用'));
 await open();assert.match(await card(engine).textContent(),/已停用/);await card(engine).locator('[data-plugin-enable]').click();await page.waitForFunction(()=>[...document.querySelectorAll('.plugin-card')].find(c=>c.textContent.includes('vela.component.tex.engine'))?.textContent.includes('已启用'));console.log('PASS installed components share plugin lifecycle and persist enabled state');
 await page.emulateMedia({reducedMotion:'reduce'});for(const width of [390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await card(engine).isVisible());}await page.screenshot({path:'test-results/components/manager.png',animations:'disabled'});
 await card(chinese).locator('[data-plugin-remove]').click();await card(chinese).waitFor({state:'detached'});await open();assert.equal(await card(chinese).count(),0);const removed=await page.evaluate(async descriptor=>await new Promise(resolve=>{const request=indexedDB.open('vela.tex-components',1);request.onsuccess=()=>{const db=request.result,tx=db.transaction('files'),r=tx.objectStore('files').getKey(descriptor.id+'/vela-tex-cjk.zip');r.onsuccess=()=>resolve(!r.result);tx.oncomplete=()=>db.close();};}),descriptor);assert.equal(removed,true);console.log('PASS uninstall removes resource bytes and card across restart');
 await install('dist/plugins/Vela-Ebook-Reader-1.0.0.zip');await waitCard(ebook);assert.match(await card(ebook).textContent(),/已启用/);assert.equal(await page.locator('#dialog-error').textContent(),'');await card(ebook).locator('[data-plugin-open]').click();await page.locator('.ebook-reader').waitFor();
 const entries={mimetype:strToU8('application/epub+zip'),'META-INF/container.xml':strToU8('<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/book.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'),'OEBPS/book.opf':strToU8('<package xmlns="http://www.idpf.org/2007/opf"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>测试电子书</dc:title><dc:creator>作者</dc:creator></metadata><manifest><item id="b" href="b.xhtml" media-type="application/xhtml+xml"/><item id="a" href="a.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="a"/><itemref idref="b"/></spine></package>'),'OEBPS/a.xhtml':strToU8('<html><body><h1>第一章</h1><p>中文正文</p><script>parent.PWNED=true</script><img src="https://evil.invalid/a.png"></body></html>'),'OEBPS/b.xhtml':strToU8('<html><body><h1>第二章</h1><p>后续正文</p></body></html>')};
 const zip=zipSync(entries);const chooser=page.waitForEvent('filechooser');await page.locator('[data-book-import]').click();await (await chooser).setFiles({name:'测试.epub',mimeType:'application/epub+zip',buffer:Buffer.from(zip)});
 // workspace.current asks for a project grant; approve the concrete read/import fixture.
 await page.locator('#dialog-submit').waitFor();await page.locator('#dialog-submit').click();await page.waitForFunction(()=>document.querySelector('[data-book-status]')?.textContent.includes('测试电子书'));
 const iframe=page.frameLocator('iframe[title="电子书正文"]');await iframe.locator('h1').waitFor();assert.equal(await iframe.locator('h1').textContent(),'第一章');assert.equal(await page.evaluate(()=>window.PWNED),undefined);await page.locator('[data-book-next]').click();await iframe.locator('h1').filter({hasText:'第二章'}).waitFor();await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.ebook-reader').evaluate(el=>el.scrollWidth<=el.clientWidth),true);await page.screenshot({path:'test-results/components/ebook.png',animations:'disabled'});await page.setViewportSize({width:1280,height:844});console.log('PASS EPUB installs, imports through SDK, honors spine order and isolates content');
 // Exercise FB2, PalmDOC/MOBI decoding and malformed input in a real DOM.
 const bundle=await build({entryPoints:['components/ebook-reader/engine.mjs'],bundle:true,write:false,format:'iife',globalName:'ebookQA'});await page.route('**/ebook-qa.js',route=>route.fulfill({contentType:'text/javascript',body:bundle.outputFiles[0].text}));await page.addScriptTag({url:baseURL+'/ebook-qa.js'});
 const unit=await page.evaluate(zip=>{const result={};const fb=new TextEncoder().encode('<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0"><description><title-info><book-title>FB测试</book-title></title-info></description><body><section><title><p>FB章节</p></title><p>正文</p></section></body></FictionBook>');const b=ebookQA.readBook(fb,'book.fb2');result.fb=b.title;result.fbHtml=ebookQA.chapterDocument(b,0);result.palm=[...ebookQA.palmDoc(new Uint8Array([97,98,99,128,24]))];const html=new TextEncoder().encode('<h1>MOBI中文</h1>'),bytes=new Uint8Array(94+40+html.length),v=new DataView(bytes.buffer);bytes.set(new TextEncoder().encode('BOOKMOBI'),60);v.setUint16(76,2);v.setUint32(78,94);v.setUint32(86,134);v.setUint16(94,1);v.setUint32(98,html.length);v.setUint16(102,1);bytes.set(new TextEncoder().encode('MOBI'),110);v.setUint32(114,24);v.setUint32(122,65001);v.setUint32(130,6);bytes.set(html,134);result.mobi=ebookQA.chapterDocument(ebookQA.readBook(bytes,'book.mobi'),0);v.setUint16(106,2);try{ebookQA.readBook(bytes,'book.azw');}catch(e){result.drm=e.message;}v.setUint16(106,0);v.setUint32(130,8);try{ebookQA.readBook(bytes,'book.azw3');}catch(e){result.kf8=e.message;}try{ebookQA.readBook(new Uint8Array([1]),'book.epub');}catch(e){result.badZip=e.message;}try{ebookQA.bookPath('a/b.xhtml','../../evil');}catch(e){result.path=e.message;}result.sanitized=ebookQA.safeChapter('<p onclick="evil()">ok</p><script>evil()</script><a href="javascript:evil()">bad</a><iframe src="https://evil.invalid"></iframe>','x');return result;},[...zip]);
 assert.equal(unit.fb,'FB测试');assert.match(unit.fbHtml,/FB章节/);assert.deepEqual(unit.palm,[97,98,99,97,98,99]);assert.match(unit.mobi,/MOBI中文/);assert.match(unit.drm,/DRM/);assert.match(unit.kf8,/KF8/);assert.ok(unit.badZip&&unit.path);assert.ok(!/script|onclick|iframe|javascript/.test(unit.sanitized));console.log('PASS FB2, PalmDOC, MOBI7, DRM/KF8 rejection and input validation');
 await page.reload();await openRecentFile(page,page.locator('[data-recent=tex]'));await page.locator('#more-tools').click();await page.locator('#plugins').click();await waitCard(ebook);await card(ebook).locator('[data-plugin-open]').click();await page.locator('[data-book-project]').click();await page.locator('#dialog-submit').waitFor();await page.locator('#dialog-submit').click();await page.locator('[data-book-list] button').filter({hasText:'测试.epub'}).click();await page.frameLocator('iframe[title="电子书正文"]').locator('h1').filter({hasText:'第二章'}).waitFor();console.log('PASS book and chapter progress persist after restart');
 const pdfChooser=page.waitForEvent('filechooser');await page.locator('[data-book-import]').click();await (await pdfChooser).setFiles('tests/fixtures/component-reader.pdf');await page.waitForFunction(()=>document.querySelector('[data-book-status]')?.textContent.includes('PDF component fixture'));await page.waitForFunction(()=>document.querySelector('.ebook-pdf canvas')?.width>0&&document.querySelector('.ebook-pdf .textLayer')?.textContent.includes('Component PDF one'));assert.equal(await page.locator('[data-book-chapters] option').count(),2);await page.locator('[data-pdf-query]').fill('Needle');await page.locator('[data-pdf-search]').click();await page.locator('[data-pdf-results] button').filter({hasText:'第 2 页'}).click();await page.waitForFunction(()=>document.querySelector('.ebook-pdf .textLayer')?.textContent.includes('Needle unique'));await page.locator('[data-pdf-zoom]').selectOption('1.5');await page.waitForFunction(()=>document.querySelector('.ebook-pdf canvas')?.width>100);await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.ebook-reader').evaluate(el=>el.scrollWidth<=el.clientWidth),true);await page.screenshot({path:'test-results/components/pdf-reader.png',animations:'disabled'});await page.setViewportSize({width:1280,height:844});console.log('PASS packaged PDF worker/fonts support paged canvas, text selection, search, zoom and mobile width');

 await page.locator('.plugin-page:not([hidden])>header button').click();await page.locator('#more-tools').click();await page.locator('#plugins').click();await card(ebook).locator('[data-plugin-enable]').click();await page.waitForFunction(()=>!document.querySelector('.ebook-reader'));assert.match(await card(ebook).textContent(),/已停用/);await card(ebook).locator('[data-plugin-remove]').click();await card(ebook).waitFor({state:'detached'});assert.deepEqual(errors,[]);console.log('PASS reader stop/uninstall releases page and commands');
 await writeFile('test-results/components/results.json',JSON.stringify({passed:true,errors,unit},null,2));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
