import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.WENZHOU_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),p=await browser.newPage({viewport:{width:1280,height:800}}),checks=[],errors=[];
p.on('pageerror',error=>errors.push(error.message));
await p.addInitScript(()=>localStorage.setItem('wenzhou.workspace',JSON.stringify({version:1,documents:[{id:'book',name:'正文.txt',path:'Book/正文.txt',text:'第一章 起点\n风吹过海面。\n第二章 归航\n风吹过港湾。',updatedAt:1},{id:'other',name:'笔记.txt',path:'Book/笔记.txt',text:'记录风向。',updatedAt:1},{id:'config',name:'.vela',path:'Book/.vela',text:JSON.stringify({version:2,kind:'workspace',id:'p',project:{name:'航程'},reader:{mode:'pages'},reading:{items:[{id:'b',path:'正文.txt'},{id:'o',path:'笔记.txt'}]}}),updatedAt:1}],activeId:'book',openIds:['book'],settings:{theme:'light'}})));
const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('wenzhou.workspace'))),text=()=>p.evaluate(()=>editorManager.editor.state.doc.toString());
const check=async(name,run)=>{await run();checks.push(name);console.log('PASS '+name);};
async function command(name){await p.locator('#commands').click();await p.locator('#command-list button').filter({hasText:name}).click();}
async function chrome(){await p.locator('.reader-viewport').evaluate(el=>{const r=el.getBoundingClientRect();el.dispatchEvent(new MouseEvent('click',{clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true}));});}
try{
  await p.goto('http://127.0.0.1:4173');await p.locator('[data-recent=book]').click();
  await check('章节改名进入撤销历史，保存后可对照并恢复本地快照',async()=>{const original=await text();await command('章节管理');await p.locator('[name=title]').fill('第一章 出发');await p.locator('#dialog-submit').click();assert.ok((await text()).startsWith('第一章 出发'));await p.locator('.cm-content').focus();await p.keyboard.press('Control+z');assert.equal(await text(),original);await p.evaluate(()=>editorManager.editor.dispatch({changes:{from:editorManager.editor.state.doc.length,insert:'\n尾声'}}));await p.locator('#quick-save').click();await command('本地历史与恢复');assert.ok(await p.locator('[data-history]').count()>0);await p.locator('[data-history]').first().click();assert.ok(await p.locator('#history-diff').textContent());await p.locator('#restore-history').click();assert.equal(await text(),original);});
  await check('工作区搜索、替换预览和多文件恢复历史',async()=>{await p.locator('.cm-content').focus();await p.keyboard.press('Control+Shift+f');await p.locator('[name=query]').fill('风');await p.locator('[name=replacement]').fill('雨');await p.locator('#workspace-search').click();await p.waitForFunction(()=>document.querySelectorAll('.search-result').length===3);await p.locator('#replace-preview').click();assert.match(await p.locator('#dialog-title').textContent(),/批量替换/);await p.locator('#dialog-submit').click();const saved=await state();assert.ok(saved.documents.find(d=>d.id==='book').text.includes('雨吹'));assert.equal(saved.documents.find(d=>d.id==='other').text,'记录雨向。');assert.ok(saved.localHistory.other.some(h=>h.text==='记录风向。'));});
  await check('词库补全、编辑书签与阅读批注共用稳定文稿 ID',async()=>{await command('词库与写作片段');await p.locator('[name=glossary]').fill('海岬灯塔\n航海纪事');await p.locator('[name=snippets]').fill('场景 | 港湾\\n灯塔');await p.locator('#dialog-submit').click();await p.evaluate(()=>{const v=editorManager.editor;v.dispatch({selection:{anchor:8,head:9}});v.focus();});await p.keyboard.press('Control+Alt+b');assert.equal((await state()).annotations.book.length,1);await p.locator('[data-view=reader]').click();await p.locator('[data-read=book]').click();await p.waitForTimeout(250);await chrome();await p.locator('#reader-tools').click();assert.equal(await p.locator('[data-reader-mark]').count(),1);await p.locator('.reader-tools-panel input').fill('雨');await p.waitForSelector('[data-reader-hit]');assert.equal(await p.locator('[data-reader-hit]').count(),2);await p.locator('[data-reader-hit]').last().click();assert.ok((await state()).readerPositions.book.offset>0);await chrome();await p.locator('#reader-tools').click();await p.locator('.reader-tools-panel textarea').fill('核对归航场景');await p.locator('[data-reader-note]').click();assert.equal((await state()).annotations.book.length,2);assert.equal((await state()).annotations.book.at(-1).note,'核对归航场景');});
  await check('阅读搜索关闭取消任务，返回编辑保持内容和批注',async()=>{await p.locator('[data-tools-close]').click();await p.locator('#reader-back').click();await p.locator('[data-view=write]').click();assert.ok((await text()).includes('雨吹过港湾'));assert.equal((await state()).annotations.book.length,2);});
  assert.deepEqual(errors,[]);await writeFile('test-results/editing-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));
}catch(error){await p.screenshot({path:'test-results/editing-failure.png'});throw error;}finally{await browser.close();}
