import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createVelaV2,velaText} from '../web/vela.mjs';
import {glossaryText} from '../web/glossary.mjs';
const config=createVelaV2('航程');config.editor.glossaries=['人物.gly','地点.glossary'];
const doc=(id,name,text)=>({id,name,path:'Novel/'+name,text,updatedAt:1});
const seed={version:1,documents:[doc('book','操作指南.txt','第一章 航程\n林舟站在港口。'),doc('config','.vela',velaText(config)),doc('terms','人物.gly',glossaryText({version:1,entries:[{term:'林舟',definition:'航海记录者',category:'人物',aliases:['舟']}]})),doc('places','地点.glossary',glossaryText({version:1,entries:[{term:'林舟',definition:'旧港口名',aliases:[]},{term:'灯塔',definition:'目的地',aliases:[]}]}))],activeId:'book',openIds:['book'],settings:{theme:'light'}};
await mkdir('test-results/ui-overhaul',{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1280,height:850}}),errors=[],checks=[];
await context.addInitScript(seed=>{if(window===window.top&&!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify(seed));},seed);
const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));const state=()=>p.evaluate(()=>{wenzhouSave();return JSON.parse(localStorage.getItem('wenzhou.workspace'));});
try{
 await p.goto('http://127.0.0.1:4173/?ui=harmonyos');await p.waitForSelector('.cm-editor');
 await p.keyboard.press('Control+Alt+h');await p.locator('[data-recent=terms]').click();await p.waitForSelector('.glossary-editor');assert.equal(await p.locator('#glossary-count').textContent(),'1 词条');await p.locator('[data-field=definition]').fill('负责航海日志');await p.locator('.glossary-editor footer button').click();assert.equal(JSON.parse((await state()).documents.find(doc=>doc.id==='terms').text).entries[0].definition,'负责航海日志');
 await p.locator('#glossary-add').click();await p.locator('.glossary-entry').last().locator('[data-field=term]').fill('远航');await p.locator('.glossary-entry').last().locator('[data-field=aliases]').fill('出航, 起航');await p.locator('.glossary-editor footer button').click();assert.equal(JSON.parse((await state()).documents.find(doc=>doc.id==='terms').text).entries.length,2);await p.screenshot({path:'test-results/ui-overhaul/glossary-gui.png'});checks.push('GLY and GLOSSARY recognized, GUI editing, aliases, save and search');
 await p.locator('#glossary-search').fill('远航');assert.equal(await p.locator('.glossary-entry').count(),1);await p.locator('[data-delete]').click();await p.locator('.glossary-editor footer button').click();assert.equal(JSON.parse((await state()).documents.find(doc=>doc.id==='terms').text).entries.length,1);
 await p.keyboard.press('Control+Alt+h');await p.locator('[data-recent=book]').click();await p.evaluate(()=>{const v=editorManager.editor;v.dispatch({changes:{from:0,to:v.state.doc.length,insert:'林'},selection:{anchor:1}});v.focus();});await p.keyboard.press('Control+Space');await p.waitForSelector('.cm-tooltip-autocomplete');const candidate=p.locator('.cm-tooltip-autocomplete li').first();assert.match(await candidate.textContent(),/林舟/);assert.match(await candidate.textContent(),/人物\.gly.*地点\.glossary/);assert.equal(await candidate.evaluate(el=>getComputedStyle(el).fontSize),'12px');assert.equal(await candidate.locator('.cm-completionDetail').evaluate(el=>getComputedStyle(el).fontSize),'11px');await p.screenshot({path:'test-results/ui-overhaul/glossary-completion.png'});await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>editorManager.editor.state.doc.toString()),'林舟');checks.push('Multi-library completion merged, source displayed, small typography and canonical insertion');
 await p.evaluate(()=>{const v=editorManager.editor;v.dispatch({changes:{from:0,to:v.state.doc.length,insert:'海航'},selection:{anchor:0,head:2}});v.focus();});await p.keyboard.press('Control+Alt+g');await p.waitForSelector('#dialog[open]');assert.equal(await p.locator('[name=term]').inputValue(),'海航');await p.locator('[name=source]').selectOption('terms');await p.locator('[name=definition]').fill('航海术语');await p.locator('#dialog-submit').click();assert.ok(JSON.parse((await state()).documents.find(doc=>doc.id==='terms').text).entries.some(entry=>entry.term==='海航'));
 await p.evaluate(()=>{const v=editorManager.editor;v.dispatch({selection:{anchor:0,head:2}});v.focus();});await p.locator('#add-glossary').click();await p.locator('[name=source]').selectOption('new');await p.locator('[name=filename]').fill('航海.glossary');await p.locator('#dialog-submit').click();const saved=await state();assert.ok(saved.documents.some(doc=>doc.path==='Novel/航海.glossary'),JSON.stringify({error:await p.locator('#dialog-error').textContent(),paths:saved.documents.map(doc=>doc.path)}));assert.ok(JSON.parse(saved.documents.find(doc=>doc.id==='config').text).editor.glossaries.includes('航海.glossary'));checks.push('Selection shortcut and button, existing and new libraries, automatic project linking');
 await p.keyboard.press('Control+Alt+h');await p.locator('[data-recent=config]').click();await p.locator('[name=glossaries]').fill('人物.gly\n地点.glossary\n航海.glossary');await p.locator('.vela-config-actions button').click();assert.equal(JSON.parse((await state()).documents.find(doc=>doc.id==='config').text).editor.glossaries.length,3);checks.push('VELA GUI associates multiple relative glossary paths');
 await p.setViewportSize({width:390,height:844});await p.keyboard.press('Control+Alt+h');await p.locator('[data-recent=terms]').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:'test-results/ui-overhaul/glossary-mobile.png'});assert.deepEqual(errors,[]);await writeFile('test-results/ui-overhaul/glossary-results.json',JSON.stringify({checks,errors},null,2));console.log('PASS '+checks.join('\nPASS '));
}finally{await browser.close();}
