import {openRecentFile} from './start-page-helper.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base='第一章 出发\n共同开头\n原来的争议段\n共同结尾\n',local=base.replace('原来的争议段','本地争议段'),remote=base.replace('原来的争议段','远端争议段');
const seed={version:1,documents:[{id:'book',name:'正文.txt',text:local,updatedAt:1,remote:{repo:'writer/book',branch:'main',path:'正文.txt',sha:'a'.repeat(40),lastSyncedText:base}},{id:'gly',name:'词条.gly',text:JSON.stringify({version:1,entries:[{term:'柯戈德尾',category:'地名',definition:'北方港口',aliases:['Kogod']},{term:'柯戈德尾人',category:'人物',definition:'旅人'},{term:'另一座城',category:'地名'}]}),updatedAt:2},{id:'vela',name:'.vela',text:JSON.stringify({version:2,kind:'workspace',id:'book',project:{name:'书稿'},editor:{glossaries:['词条.gly']},reading:{items:[]}}),updatedAt:3}],activeId:'book',openIds:['book'],settings:{theme:'light',language:'zh-CN',glossaryPanel:true}};
const browser=await chromium.launch({headless:true,executablePath:process.env.WENZHOU_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
await mkdir('test-results/improvements',{recursive:true});
try{
 for(const width of [320,390,768,1280]){
  const context=await browser.newContext({viewport:{width,height:850}});await context.addInitScript(seed=>{if(!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify(seed));const visual=new EventTarget();Object.assign(visual,{height:850,width:innerWidth,scale:1,offsetTop:0,offsetLeft:0});Object.defineProperty(window,'visualViewport',{get:()=>visual});window.testVisual=visual;},seed);
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.VELA_TEST_URL||'http://127.0.0.1:4173');await openRecentFile(page,page.locator('[data-recent=book]'));
  await page.locator('#glossary-panel input').fill('  柯戈德尾　地名 ');assert.equal(await page.locator('.glossary-panel-rows>button').count(),1);assert.equal(await page.locator('.glossary-panel-rows strong').textContent(),'柯戈德尾');
  await page.locator('#glossary-panel input').fill('kogod 北方');assert.equal(await page.locator('.glossary-panel-rows>button').count(),1);
  await page.locator('#glossary-panel input').fill('柯戈德尾 人物 地名');assert.equal(await page.locator('.glossary-panel-rows>button').count(),0);
  await page.locator('.cm-content').focus();await page.keyboard.press('Control+f');await page.waitForSelector('.vela-search-panel');const panel=page.locator('.vela-search-panel');assert.match(await panel.textContent(),/查找与替换.*上一处.*下一处.*替换当前.*全部替换/s);assert.doesNotMatch(await panel.textContent(),/match case|replace all|next|previous/i);
  await panel.locator('[name=search]').fill('共同');await page.waitForFunction(()=>document.querySelector('.search-feedback').textContent.includes('2'));await panel.locator('[name=replace]').fill('共有');await panel.locator('[name=replace-all]').click();assert.match(await page.evaluate(()=>editorManager.editor.state.doc.toString()),/共有开头.*共有结尾/s);
  await panel.locator('[name=regexp]').check();await panel.locator('[name=search]').fill('[');assert.equal(await panel.locator('[name=search]').getAttribute('aria-invalid'),'true');assert.ok(await panel.locator('[name=next]').isDisabled());
  await page.locator('.cm-panels').evaluate(el=>el.scrollTop=0);await page.screenshot({path:`test-results/improvements/search-${width}.png`});await panel.locator('[name=close]').click();
  await page.locator('#mobile-library').click();await page.waitForFunction(()=>document.querySelector('#app').dataset.sidebarsAnimating==='false');const handle=page.locator('.sidebar-resize-left');await handle.focus();const before=await page.locator('#library').boundingBox();await page.keyboard.press('ArrowRight');const after=await page.locator('#library').boundingBox();assert.ok(after.width>=before.width);const stored=await page.evaluate(()=>localStorage.getItem('vela.sidebar-widths'));assert.ok(stored);await page.reload();await openRecentFile(page,page.locator('[data-recent=book]'));await page.locator('#mobile-library').click();await page.waitForFunction(()=>document.querySelector('#app').dataset.sidebarsAnimating==='false');assert.equal(await page.evaluate(()=>localStorage.getItem('vela.sidebar-widths')),stored);
  await page.locator('#mobile-library').click();await page.locator('#outline-toggle').click();await page.evaluate(()=>{testVisual.height=420;testVisual.dispatchEvent(new Event('resize'));});await page.waitForFunction(()=>document.body.dataset.keyboard==='true');assert.ok((await page.locator('#app').boundingBox()).height<=421);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  if(width<=390){for(const button of await page.locator('.page-navigation button,.global-tools>button,#mobile-library').all()){const box=await button.boundingBox();assert.ok(box.width>=40&&box.height>=40,JSON.stringify(box));}}
  await page.evaluate(()=>{testVisual.height=850;testVisual.dispatchEvent(new Event('resize'));});await page.locator('#outline-toggle').click();
  // The glossary editing screen uses the same all-keywords semantics.
  await page.locator('#home-button').evaluate(button=>button.click());await openRecentFile(page,page.locator('[data-recent=gly]'));await page.locator('#glossary-search').fill('地名 柯戈德尾');assert.equal(await page.locator('.glossary-entry').count(),1);
  if(width===1280){await page.locator('[data-view=write]').click();await page.locator('[data-tab=book]').click();await page.locator('#more-tools').click();await page.locator('#settings').click();await page.locator('[name=language]').selectOption('en');await page.locator('#dialog-submit').click();await page.waitForFunction(()=>document.documentElement.lang==='en');await page.locator('.cm-content').focus();await page.keyboard.press('Control+f');assert.match(await page.locator('.vela-search-panel').textContent(),/Find and replace.*Previous.*Next.*Replace current.*Replace all/is);assert.doesNotMatch(await page.locator('.vela-search-panel').textContent(),/查找|替换|匹配/);await page.screenshot({path:'test-results/improvements/search-en.png'});}assert.deepEqual(errors,[]);await context.close();console.log('PASS multi-keyword search, localized find/replace, sidebar memory, keyboard and touch layout at '+width);
 }
 const context=await browser.newContext();await context.addInitScript(seed=>localStorage.setItem('wenzhou.workspace',JSON.stringify(seed)),seed);const page=await context.newPage(),writes=[];let rejectWrite=true;
 await page.route('https://api.github.com/**',async route=>{const request=route.request(),path=decodeURIComponent(new URL(request.url()).pathname);let body={},status=200;if(request.method()!=='GET')writes.push(request.postDataJSON());if(path==='/user')body={login:'writer'};else if(path==='/user/repos')body=[{full_name:'writer/book',name:'book',default_branch:'main',permissions:{push:true}}];else if(path.endsWith('/branches'))body=[{name:'main'}];else if((path.endsWith('/contents')||path.endsWith('/contents/')))body=[{name:'正文.txt',path:'正文.txt',type:'file',size:100,sha:'b'.repeat(40)}];else if(path.endsWith('/contents/正文.txt')){if(request.method()==='PUT'){status=rejectWrite?409:200;body=rejectWrite?{message:'remote changed'}:{content:{sha:'c'.repeat(40)},commit:{sha:'d'.repeat(40)}};}else body={type:'file',size:Buffer.byteLength(remote),encoding:'base64',content:Buffer.from(remote).toString('base64'),sha:'b'.repeat(40)};}await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});});
 await page.goto(process.env.VELA_TEST_URL||'http://127.0.0.1:4173');await openRecentFile(page,page.locator('[data-recent=book]'));await page.locator('[data-view=github]').click();await page.locator('#token-login').click();await page.locator('[name=token]').fill('test-only');await page.locator('#dialog-submit').click();await page.locator('.repo-card').click();await page.locator('[data-file]').click();await page.waitForSelector('.sync-conflict-part');assert.equal(writes.length,0);await page.locator('#dialog-submit').click();assert.match(await page.locator('#dialog-error').textContent(),/处理每一处/);await page.locator('[data-choose=remote]').click();assert.ok((await page.locator('.sync-merged').inputValue()).includes('远端争议段'));await page.locator('#dialog-submit').click();await page.waitForSelector('#dialog[open]',{state:'hidden'});let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('wenzhou.workspace')));assert.equal(state.documents.find(d=>d.id==='book').text,remote);assert.ok(state.localHistory.book.some(item=>item.text===local));
 // Failure remains visible, and retry updates the baseline without discarding later edits.
 await page.locator('[data-view=write]').click();await page.locator('.cm-content').focus();await page.keyboard.press('Control+End');await page.keyboard.type('本地新增');await page.locator('#quick-save').click();await page.locator('#quick-git').click();await page.locator('#dialog-submit').click();await page.locator('#dialog-submit').click();await page.waitForFunction(()=>document.querySelector('#dialog-error').textContent.length>0);assert.match(await page.locator('#sync-state').textContent(),/同步失败/);rejectWrite=false;await page.locator('#dialog-submit').click();await page.waitForSelector('#dialog[open]',{state:'hidden'});assert.match(await page.locator('#sync-state').textContent(),/已与远端同步/);await context.close();console.log('PASS real UI conflict resolution, local history, sync failure and retry (mock remote)');
}finally{await browser.close();}
