import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:390,height:820}}),errors=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));
const text=Array.from({length:80},(_,chapter)=>`第${chapter+1}章 航路${chapter+1}\n`+Array.from({length:10},(_,line)=>`航路${chapter+1}第${line+1}段，船向海岛航行，正文保持在同一小说文件中。`).join('\n')).join('\n');
await page.addInitScript(text=>{if(!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify({version:1,documents:[{id:'book',name:'Novel.txt',text,updatedAt:1},{id:'guide',name:'操作指南.txt',text:'guide',updatedAt:1}],activeId:'book',openIds:['book'],settings:{theme:'light',readingMode:'pages',libraryOpen:true}}));},text);
const position=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('wenzhou.workspace')).readerPositions?.book);
async function tap(fraction){await page.waitForTimeout(220);const box=await page.locator('.reader-viewport').boundingBox();await page.mouse.click(box.x+box.width*fraction,box.y+box.height*.55);await page.waitForTimeout(380);}
async function nav(view){if(await page.locator('body').evaluate(el=>el.classList.contains('reader-open')&&!el.classList.contains('reader-chrome-visible')))await tap(.5);await page.locator(`[data-view=${view}]`).click();}
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
try{await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.cm-editor');await nav('reader');await page.locator('[data-read=book]').click();
  await check('阅读自动收起文件栏，默认隐藏工具栏，时间与进度显示',async()=>{await page.waitForTimeout(240);assert.equal(await page.locator('#library').isVisible(),false);assert.equal(await page.locator('.topbar').isVisible(),false);assert.equal(await page.locator('#reader-next,#reader-prev').count(),0);assert.match(await page.locator('#reader-clock').textContent(),/\d{2}:\d{2}/);});
  await check('分页点击前后与中间区域互不干扰，章节跳转定位',async()=>{for(let i=0;i<7;i++)await tap(.9);assert.ok((await position()).offset>150);const pageNumber=await page.locator('#reader-position').textContent();await tap(.5);assert.equal(await page.locator('.topbar').isVisible(),true);assert.equal(await page.locator('#reader-position').textContent(),pageNumber);await page.locator('#outline-toggle').click();await page.locator('[data-reader-offset]').filter({hasText:'第21章'}).click();await page.waitForTimeout(400);assert.ok((await position()).context.includes('航路20')||(await position()).context.includes('航路21'));});
  await check('重开恢复阅读位置，改变字号和设备尺寸保持附近文本',async()=>{const before=await position();await nav('reader');await page.locator('[data-read=book]').click();await page.waitForTimeout(450);assert.ok(Math.abs((await position()).offset-before.offset)<120);await page.locator('.reader-viewport').evaluate(el=>el.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:-12,bubbles:true,cancelable:true})));await page.waitForTimeout(400);assert.ok(Math.abs((await position()).offset-before.offset)<500);await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(450);assert.ok(Math.abs((await position()).offset-before.offset)<1500);});
  await check('上下模式一次滚动一屏，重新加载后恢复文本位置',async()=>{await tap(.5);await page.locator('#settings').click();await page.locator('[name=readingMode]').selectOption('scroll');await page.locator('#dialog-submit').click();await page.waitForTimeout(200);const before=await page.locator('.reader-viewport').evaluate(el=>el.scrollTop);await tap(.9);const after=await page.locator('.reader-viewport').evaluate(el=>el.scrollTop);assert.ok(after>before+500);const saved=await position();await page.reload();await page.waitForSelector('.cm-editor');await nav('reader');await page.locator('[data-read=book]').click();await page.waitForTimeout(450);assert.ok(Math.abs((await position()).offset-saved.offset)<120);});
  assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await writeFile('test-results/reading-060-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));await page.screenshot({path:'test-results/reading-060.png'});
}catch(error){await page.screenshot({path:'test-results/reading-060-failure.png'});throw error;}finally{await browser.close();}
