import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createVelaV2,velaText} from '../web/vela.mjs';
import {glossaryText} from '../web/glossary.mjs';
const config=createVelaV2('航程');config.editor.glossaries=['人物.gly'];config.reader={mode:'double',titlePage:false};config.reading.items=[{id:'book',path:'航程.txt'}];
const text='第一章 航程\n林舟推开驾驶舱的门，望向星澜值守的灯塔。周衡望着青岚港。\n'+'海风吹过旧港。'.repeat(300)+'\n林';
const make=(id,name,text)=>({id,name,path:'Novel/'+name,text,updatedAt:1});
const seed={version:1,documents:[make('book','航程.txt',text),make('other','另一篇.txt','新的文稿。\n林'),make('config','.vela',velaText(config)),make('terms','人物.gly',glossaryText({version:1,entries:[{term:'林舟',category:'人物',definition:'领航员',aliases:['船长']}]}))],activeId:'book',openIds:['book','other'],settings:{theme:'light',readingMode:'double'}};
await mkdir('test-results/storyboard',{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),checks=[],errors=[];
const context=await browser.newContext({viewport:{width:1280,height:850}});await context.addInitScript(seed=>{if(!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify(seed));},seed);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
const setText=async text=>p.evaluate(text=>{const v=editorManager.editor;v.dispatch({changes:{from:0,to:v.state.doc.length,insert:text},selection:{anchor:text.length}});v.focus();},text);
try{
 for(const profile of ['windows','android','harmonyos']){
  await p.goto('http://127.0.0.1:4173/?ui='+profile);if(await p.locator('[data-recent=book]').isVisible())await p.locator('[data-recent=book]').click();await p.waitForSelector('.cm-editor');assert.equal(await p.locator('#glossary-panel').isVisible(),false);
  await setText(text.slice(0,-1)+'星');await p.keyboard.press('Control+Space');await p.waitForSelector('.cm-tooltip-autocomplete');await p.waitForFunction(()=>document.querySelector('.cm-tooltip-autocomplete')?.textContent.includes('星澜'));assert.match(await p.locator('.cm-tooltip-autocomplete').textContent(),/正文候选/);await p.waitForTimeout(250);const candidateRows=await p.locator('.cm-tooltip-autocomplete li').allTextContents();await p.keyboard.press('Enter');const completed=await p.evaluate(()=>editorManager.editor.state.doc.toString());assert.ok(completed.endsWith('星澜'),JSON.stringify({profile,candidateRows,tail:completed.slice(-30)}));await p.keyboard.press('Control+z');assert.ok((await p.evaluate(()=>editorManager.editor.state.doc.toString())).endsWith('星'));checks.push(profile+' local noun completion and undo');
  await p.keyboard.press('Escape');await setText(text);await p.keyboard.press('Control+Space');await p.waitForSelector('.cm-tooltip-autocomplete');assert.match(await p.locator('.cm-tooltip-autocomplete li').first().textContent(),/林舟.*术语/);assert.equal(await p.locator('.cm-tooltip-autocomplete li').filter({hasText:'林舟'}).count(),1);await p.keyboard.press('Escape');
 }
 await setText('第一章\n没有旧名字。\n星');await p.waitForTimeout(400);await p.keyboard.press('Control+Space');await p.waitForTimeout(350);assert.ok(!(await p.locator('.cm-tooltip-autocomplete').allTextContents()).join('').includes('星澜'));checks.push('Deleted names removed from completion');
 await setText(text);await p.keyboard.press('Escape');await p.locator('#settings').click();await p.locator('[name=glossaryPanel]').check();await p.locator('[name=highlightTerms]').check();await p.locator('#dialog-submit').click();await p.waitForSelector('#glossary-panel:not([hidden])');await p.evaluate(()=>{const v=editorManager.editor;v.dispatch({selection:{anchor:0},scrollIntoView:true});});await p.waitForSelector('.vela-term');assert.match(await p.locator('#glossary-panel').textContent(),/林舟.*人物.*领航员/s);
 for(const width of [1280,390,320]){await p.setViewportSize({width,height:850});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await p.locator('#editor').isVisible());await p.screenshot({path:`test-results/storyboard/glossary-${width}.png`});}await p.setViewportSize({width:1280,height:850});checks.push('Opt-in glossary and term highlighting preserve narrow editor');
 await p.locator('#glossary-panel header button').click();assert.equal(await p.locator('#glossary-panel').isVisible(),false);await p.reload();if(await p.locator('[data-recent=book]').isVisible())await p.locator('[data-recent=book]').click();await p.waitForSelector('.cm-editor');assert.equal(await p.locator('#glossary-panel').isVisible(),false);
 await p.locator('[data-view=reader]').click();await p.locator('[data-read=book]').click();await p.waitForSelector('.reader-double');await p.waitForTimeout(250);
 await p.evaluate(()=>{const root=document.querySelector('.reader-content'),w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const at=n.textContent.indexOf('林舟');if(at>=0){const r=document.createRange();r.setStart(n,at);r.setEnd(n,at+2);getSelection().removeAllRanges();getSelection().addRange(r);break;}}});
 await p.evaluate(()=>document.querySelector('#reader-notes').click());await p.locator('.reader-notes-section textarea').fill('领航员的第一次登场');await p.locator('[data-reader-note]').click();await p.locator('[data-tools-close]').click();await p.waitForSelector('.reader-inline-highlight');await p.locator('.reader-note-anchor').first().click();assert.match(await p.locator('.reader-note-bubble').textContent(),/第一次登场/);await p.locator('.reader-note-bubble').click();
 await p.evaluate(()=>document.querySelector('#reader-notes').click());await p.locator('[data-reader-bookmark]').click();await p.locator('[data-tools-close]').click();await p.waitForSelector('.reader-bookmark-ribbon');await p.screenshot({path:'test-results/storyboard/reading-marks.png'});checks.push('Inline annotation highlight, bubble and bookmark ribbon');
 await p.evaluate(()=>{getSelection().removeAllRanges();document.querySelector('.reader-viewport').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));});assert.ok(await p.locator('.reader-book-leaf').count());await p.waitForTimeout(300);assert.equal(await p.locator('.reader-book-leaf').count(),0);await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>document.querySelector('.reader-viewport').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true})));assert.equal(await p.locator('.reader-book-leaf').count(),0);checks.push('Double-page leaf animation and reduced motion');
 assert.deepEqual(errors,[]);console.log(checks.join('\n'));await writeFile('test-results/storyboard/results.json',JSON.stringify({checks,errors},null,2));
}finally{await browser.close();}


