import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import {guide} from '../web/guide.mjs';
import {createVela,velaText} from '../web/vela.mjs';
const root=path.resolve('dist/web'),checks=[],errors=[];
const server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'text/plain'}).end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:process.env.WENZHOU_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),url=`http://127.0.0.1:${server.address().port}`;
await mkdir('test-results',{recursive:true});
const book='第一章 航路\n'+Array.from({length:250},(_,i)=>`第 ${i+1} 行。船驶向岛屿，航海记录仍保留在同一文档。`).join('\n');
const seed={version:1,documents:[{id:'guide',name:'操作指南.txt',text:guide,updatedAt:1,remote:null},{id:'book',name:'Novel.txt',text:book,updatedAt:2,remote:null},{id:'csv',name:'Table.csv',text:Array.from({length:106},(_,r)=>Array.from({length:55},(_,c)=>r===0&&c===0?'姓名':`R${r}C${c}`).join(',')).join('\n'),updatedAt:1,remote:null},{id:'html',name:'Page.html',text:'<!doctype html><html><body><h1>Local HTML</h1><input value="original"></body></html>',updatedAt:1,remote:null}],activeId:'book',openIds:['book'],settings:{theme:'system'}};
let revision=1,configRevision=1,networkDown=false;
const remoteConfig=()=>velaText({...createVela('Remote Novel'),fontSize:16+configRevision,reading:{files:['正文/第一卷/book.txt']}});
async function createPage(width=1440){const context=await browser.newContext({viewport:{width,height:900}});await context.addInitScript(seed=>{if(!localStorage.getItem('wenzhou.workspace'))localStorage.setItem('wenzhou.workspace',JSON.stringify(seed));},seed);
  await context.route('https://api.github.com/**',route=>{if(networkDown)return route.fulfill({status:503,body:'{}',contentType:'application/json'});const request=new URL(route.request().url()),p=request.pathname;let body;
    if(p.endsWith('/releases'))body=[{id:1,tag_name:'v1',name:'Release One',body:'# Notes\nRelease details',published_at:'2026-10-02T00:00:00Z',updated_at:'now'}];
    else if(p.includes('/git/trees/'))body={sha:'tree-'+revision+'-'+configRevision,tree:[{type:'blob',path:'.vela',sha:'config-'+configRevision},{type:'blob',path:'正文/第一卷/book.txt',sha:'book-'+revision,size:40},{type:'blob',path:'private.txt',sha:'private-'+configRevision},{type:'blob',path:'CHANGELOG.md',sha:'changelog',size:30}]};
    else if(p.includes('/git/blobs/config-'))body={encoding:'base64',content:Buffer.from(remoteConfig()).toString('base64'),size:remoteConfig().length};
    else if(p.includes('/git/blobs/book-'))body={encoding:'base64',content:Buffer.from('第一章 订阅阅读\n远端正文 revision '+revision).toString('base64'),size:70};
    else if(p.endsWith('/git/blobs/changelog'))body={encoding:'base64',content:Buffer.from('# Changelog\nChanged navigation').toString('base64'),size:40};
    else body={full_name:'sample/novel',default_branch:'main',pushed_at:'revision-'+revision};
    return route.fulfill({status:200,body:JSON.stringify(body),contentType:'application/json'});
  });const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(url);await page.waitForSelector('.cm-editor');return page;}
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('wenzhou.workspace')));
async function check(name,run){await run();checks.push(name);console.log('PASS '+name);}
let page;
try{
  page=await createPage(390);
  await check('手机顶栏四个页面入口常驻，文件名隐藏，Git 页退出按钮与底栏动画同步',async()=>{
    assert.equal(await page.locator('.page-navigation button').count(),4);for(const button of await page.locator('.page-navigation button').all())assert.equal(await button.isVisible(),true);
    assert.equal(await page.locator('#current-name').isVisible(),false);await page.locator('#mobile-library').click();await page.waitForFunction(()=>document.querySelector('#app').dataset.sidebarsAnimating==='false');
    const frames=await page.evaluate(async()=>{const values=[];document.querySelector('[data-view=github]').click();do{await new Promise(requestAnimationFrame);values.push({bottom:document.querySelector('#library').getBoundingClientRect().bottom,footer:document.querySelector('#writing-footer').getBoundingClientRect().top});}while(document.querySelector('#app').dataset.sidebarsAnimating==='true');return values;});
    assert.ok(frames.length>2);assert.ok(frames.at(-1).bottom>frames[0].bottom+25);assert.ok(frames.at(-1).footer>frames[0].footer+25);assert.equal(await page.locator('#sidebar-logout').isVisible(),true);assert.equal(await page.locator('#sidebar-logout').isDisabled(),true);
    await page.locator('#mobile-library').click();await page.waitForFunction(()=>document.querySelector('#app').dataset.sidebarsAnimating==='false');for(const button of await page.locator('.page-navigation button').all())assert.equal(await button.isVisible(),true);await page.screenshot({path:'test-results/vela-050-mobile-github.png'});
  });
  await check('设置可创建缺失的 .vela，新工作区自动创建配置，新文件进入阅读清单',async()=>{
    await page.locator('[data-view=write]').click();await page.locator('#settings').click();assert.equal(await page.locator('[name=titleTemplates]').count(),0);assert.equal(await page.locator('#create-vela').isEnabled(),true);await page.locator('#create-vela').click();await page.waitForSelector('#vela-form');assert.ok((await saved(page)).documents.some(doc=>doc.name==='.vela'));
    await page.locator('#mobile-library').click();await page.locator('#new-folder').click();await page.locator('[name=path]').fill('My Novel');await page.locator('#dialog-submit').click();assert.ok((await saved(page)).documents.some(doc=>doc.path==='My Novel/.vela'));
    await page.locator('#new-doc').click();await page.locator('#dialog [name=name]').fill('Manuscript.txt');await page.locator('[name=template]').selectOption('empty');await page.locator('#dialog-submit').click();
    const state=await saved(page),manifest=state.documents.find(doc=>doc.path==='My Novel/.vela');assert.deepEqual(JSON.parse(manifest.text).reading.files,['Manuscript.txt']);await page.locator(`[data-doc="${manifest.id}"]`).click();await page.waitForSelector('#vela-form');await page.locator('#vela-form [name=titleTemplates]').fill('【{number}】{title}');await page.locator('#vela-form .primary').click();assert.equal(JSON.parse((await saved(page)).documents.find(doc=>doc.id===manifest.id).text).titleTemplates[0],'【{number}】{title}');
    await page.locator('#settings').click();assert.equal(await page.locator('#create-vela').isDisabled(),true);await page.locator('#dialog-cancel').click();await page.screenshot({path:'test-results/vela-050-config.png'});
    await page.locator('#mobile-library').click();
  });
  await check('手机阅读启动页滑出、隐藏标签、阻止编辑与撤销，Ctrl 捏合只更改文字',async()=>{
    await page.locator('[data-view=reader]').click();await page.locator('[data-read=book]').click();await page.waitForFunction(()=>document.querySelector('.reader-stage')?.classList.contains('reading'));assert.equal(await page.locator('#document-tabs').isVisible(),false);assert.equal(await page.locator('#reader-view textarea,#reader-view [contenteditable]').count(),0);
    const before=await saved(page);await page.keyboard.press('Control+z');await page.keyboard.type('Must not edit');assert.equal((await saved(page)).documents.find(doc=>doc.id==='book').text,before.documents.find(doc=>doc.id==='book').text);
    const toolbar=await page.locator('.topbar').boundingBox(),font=await page.locator('.reader-content').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));await page.locator('.reader-viewport').evaluate(el=>el.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:-20,bubbles:true,cancelable:true})));const next=await page.locator('.reader-content').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));assert.ok(next>font);assert.equal((await page.locator('.topbar').boundingBox()).height,toolbar.height);
    await page.locator('[data-view=reader]').click();assert.equal(await page.locator('.reader-stage.reading').count(),0);assert.equal(await page.locator('.reader-books').isVisible(),true);
  });
  await check('英文支持、CSV 只读表格和三种尺寸分页阅读',async()=>{
    await page.locator('#settings').click();await page.locator('[name=language]').selectOption('en');await page.locator('[name=readingMode]').selectOption('pages');await page.locator('#dialog-submit').click();await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('[data-view=reader]').getAttribute('aria-label'),'Read');
    await page.locator('[data-view=reader]').click();await page.locator('[data-read=csv]').click();await page.waitForSelector('.reader-content td');assert.equal(await page.locator('.reader-content td').first().textContent(),'姓名');assert.equal(await page.locator('.reader-content :is(textarea,input,[contenteditable])').count(),0);assert.ok(await page.locator('.reader-content td').count()<=5000);await page.locator('[data-csv-row=\"1\"]').click();await page.locator('[data-csv-column=\"1\"]').click();assert.equal(await page.locator('.reader-content td').last().textContent(),'R105C54');
    for(const width of [390,1200,1920]){await page.setViewportSize({width,height:900});await page.locator('[data-view=reader]').click();await page.locator('[data-read=book]').click();await page.waitForSelector('.reader-paged');await page.waitForTimeout(220);assert.equal(await page.locator('#reader-next').isEnabled(),true);await page.locator('#reader-next').click();assert.ok((await page.locator('#reader-position').textContent()).startsWith('2 /'));await page.waitForTimeout(180);await page.screenshot({path:`test-results/vela-050-read-${width}.png`});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  });
  await check('订阅配置静默同步、可读文件更新小点、详情和批量忽略/删除，断网保留缓存',async()=>{
    await page.locator('[data-view=subscriptions]').click();await page.locator('#subscription-add').click();await page.locator('[name=url]').fill('https://github.com/sample/novel');await page.locator('#dialog-submit').click();await page.waitForSelector('[data-subscription="sample/novel"]');assert.ok((await saved(page)).documents.some(doc=>doc.path==='Subscriptions/sample/novel/.vela'));assert.equal(await page.locator('.subscription-card .update-dot').count(),0);
    configRevision++;await page.locator('#subscription-refresh').click();await page.waitForFunction(()=>!document.querySelector('#subscription-refresh').disabled);assert.equal(await page.locator('.subscription-card .update-dot').count(),0);assert.equal(JSON.parse((await saved(page)).documents.find(doc=>doc.path==='Subscriptions/sample/novel/.vela').text).fontSize,18);
    revision++;await page.locator('#subscription-refresh').click();await page.waitForFunction(()=>!document.querySelector('#subscription-refresh').disabled);assert.equal(await page.locator('.subscription-card .update-dot').count(),1);await page.locator('[data-subscription-open]').click();await page.waitForFunction(()=>document.querySelector('.release-body')?.textContent.includes('Release details'));await page.waitForFunction(()=>document.querySelector('#subscriptions-view')?.textContent.includes('Changed navigation'));assert.equal((await saved(page)).subscriptions[0].unread,false);await page.locator('#subscription-pull').click();assert.equal(await page.locator('[name=readingOnly]').isChecked(),true);await page.locator('#dialog-submit').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.ok(!(await saved(page)).documents.some(doc=>doc.path==='Subscriptions/sample/novel/private.txt'));assert.ok((await saved(page)).documents.find(doc=>doc.path==='Subscriptions/sample/novel/正文/第一卷/book.txt').text.includes('远端正文'));
    await page.locator('#subscription-back').click();revision++;await page.locator('#subscription-refresh').click();await page.waitForFunction(()=>!document.querySelector('#subscription-refresh').disabled);await page.locator('[data-select-subscription]').check();await page.locator('#subscription-ignore').click();assert.equal((await saved(page)).subscriptions[0].unread,false);
    networkDown=true;await page.locator('#subscription-refresh').click();await page.waitForFunction(()=>!document.querySelector('#subscription-refresh').disabled);assert.equal((await saved(page)).subscriptions.length,1);assert.ok((await saved(page)).subscriptions[0].error);networkDown=false;
    await page.locator('[data-select-subscription]').check();await page.locator('#subscription-delete').click();await page.locator('#dialog-submit').click();assert.equal((await saved(page)).subscriptions.length,0);assert.ok((await saved(page)).documents.some(doc=>doc.path==='Subscriptions/sample/novel/.vela'));
  });
  await check('订阅正文第一次阅读下载并缓存，编辑器补全确认不占用 Tab',async()=>{
    await page.locator('#subscription-add').click();await page.locator('[name=url]').fill('https://github.com/sample/novel');await page.locator('#dialog-submit').click();await page.waitForSelector('[data-subscription]');const remote=(await saved(page)).documents.find(doc=>doc.path==='Subscriptions/sample/novel/正文/第一卷/book.txt');await page.locator('[data-view=reader]').click();await page.locator(`[data-read="${remote.id}"]`).click();await page.waitForFunction(()=>document.querySelector('.reader-content')?.textContent.includes('远端正文'));assert.equal((await saved(page)).documents.find(doc=>doc.id===remote.id).subscription.loadedSha,'book-'+revision);
    await page.locator('[data-view=write]').click();await page.locator('#mobile-library').click();await page.locator('[data-doc=book]').click();await page.evaluate(()=>{const v=window.editorManager.editor;v.dispatch({changes:{from:0,to:v.state.doc.length,insert:'navigation navigator\nnav'},selection:{anchor:24}});v.focus();});await page.keyboard.press('Control+Space');await page.waitForSelector('.cm-tooltip-autocomplete');await page.keyboard.press('Escape');await page.keyboard.press('Tab');assert.ok((await page.evaluate(()=>window.editorManager.editor.state.doc.toString())).includes('　　'));await page.locator('#quick-save').click();
  });
  await check('启动检查产生导航小点，进入页面仅清除导航小点，长按左滑忽略仓库更新',async()=>{
    revision++;await page.reload();await page.waitForSelector('.cm-editor');await page.waitForFunction(()=>!document.querySelector('[data-view=subscriptions] .update-dot').hidden);
    await page.locator('[data-view=subscriptions]').click();assert.equal(await page.locator('[data-view=subscriptions] .update-dot').isVisible(),false);await page.waitForSelector('.subscription-card .update-dot');
    await page.waitForFunction(()=>document.querySelector('#subscription-refresh')&&!document.querySelector('#subscription-refresh').disabled);await page.locator('.subscription-card').waitFor({state:'visible'});const box=await page.locator('.subscription-card').boundingBox();await page.mouse.move(box.x+box.width*.65,box.y+25);await page.mouse.down();await page.waitForTimeout(420);await page.mouse.move(box.x+box.width*.65-100,box.y+25,{steps:5});await page.mouse.up();await page.waitForFunction(()=>!document.querySelector('.subscription-card .update-dot'));assert.equal((await saved(page)).subscriptions[0].unread,false);
    await page.locator('[data-view=write]').click();await page.locator('#settings').click();await page.locator('[name=language]').selectOption('zh-CN');await page.locator('#dialog-submit').click();assert.equal(await page.locator('[data-view=reader]').getAttribute('aria-label'),'阅读');
  });
  assert.deepEqual(errors,[]);await writeFile('test-results/vela-050-browser-results.json',JSON.stringify({passed:checks.length,checks,pageErrors:errors},null,2));
}catch(error){await page?.screenshot({path:'test-results/vela-050-failure.png'}).catch(()=>{});throw error;}finally{await browser.close();server.close();}
