import {openRecentFile} from './start-page-helper.mjs';
import {chromium} from 'playwright';
import {build} from 'esbuild';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {readPluginZip} from '../web/plugin-package.mjs';
const odfPlugin=readPluginZip(new Uint8Array(await readFile('dist/plugins/Vela-ODF-1.0.0.zip')));
const fixture=await build({stdin:{contents:"export * from './web/velaodt.mjs'; export {zipSync,strToU8,unzipSync,strFromU8} from 'fflate';",resolveDir:process.cwd()},bundle:true,format:'iife',globalName:'odfTest',write:false});
const root=path.resolve('dist/web');const qaFont=process.env.VELA_QA_FONT_DIR;const fontCss=qaFont?(await readFile(path.join(qaFont,'400.css'),'utf8')).replaceAll('./files/', '/qa-font/files/')+'\nbody,button,input,select,textarea,.cm-scroller{font-family:"Noto Sans SC",sans-serif!important}':'';
const server=http.createServer(async(req,res)=>{if(qaFont&&/^\/qa-font\/files\/[A-Za-z0-9_.-]+$/.test(req.url)){try{const contents=await readFile(file);res.writeHead(200,{'Content-Type':'font/woff2'}).end(await readFile(path.join(qaFont,req.url.replace('/qa-font/',''))));}catch{res.writeHead(404).end();}return;}if(req.url==='/fixture.js'){res.writeHead(200,{'Content-Type':'text/javascript'}).end(fixture.outputFiles[0].text);return;}const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const contents=await readFile(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream'}).end(contents);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.env.WENZHOU_CHROME,args:process.env.VELA_BROWSER_SINGLE_PROCESS==='1'?['--single-process','--no-zygote']:[]});
const errors=[],checks=[];let lastPage;await mkdir('test-results/velaodt',{recursive:true});
try{
 for(const profile of [{width:390,height:844,platform:'harmonyos',top:0,bottom:22},{width:360,height:800,platform:'android',top:32,bottom:24},{width:1280,height:850,platform:'windows',top:0,bottom:0}]){
  const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.platform!=='windows',permissions:['clipboard-read','clipboard-write']});
  await context.addInitScript(()=>!localStorage.getItem('wenzhou.workspace')&&localStorage.setItem('wenzhou.workspace',JSON.stringify({version:1,documents:[{id:'book',name:'book.txt',text:'第一章\n'+('灯塔照亮航路，海风吹过港湾。\n'.repeat(80)),updatedAt:1}],activeId:'book',openIds:['book'],settings:{theme:'light'}})));
  await context.addInitScript(plugin=>{if(window.top===window&&!localStorage.getItem('wenzhou.plugins'))localStorage.setItem('wenzhou.plugins',JSON.stringify([plugin]));},odfPlugin);
  const richName=profile.platform==='android'?'故事.vodt':'故事.velaodt';const page=await context.newPage();lastPage=page;page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/?ui='+profile.platform);await page.waitForSelector('[data-recent=book]',{state:'attached'});await openRecentFile(page,page.locator('[data-recent=book]'));await page.addScriptTag({url:url+'/fixture.js'});if(fontCss){await page.addStyleTag({content:fontCss});await page.evaluate(()=>document.fonts.ready);}
  await page.evaluate(p=>window.dispatchEvent(new CustomEvent('wenzhouEnvironment',{detail:p})),profile);
  const barBefore=await page.locator('.topbar').boundingBox(),footerBefore=await page.locator('#writing-footer').boundingBox();assert.equal(Math.round(barBefore.y),profile.top);assert.ok(Math.abs(footerBefore.y+footerBefore.height-profile.height)<2);
  await page.evaluate(()=>{window.scrollTo(0,120);document.querySelector('.quickbar').dispatchEvent(new WheelEvent('wheel',{deltaY:300,bubbles:true}));});
  if(profile.platform!=='windows'){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:profile.width/2,y:profile.height-50}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:profile.width/2,y:profile.height-260}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  await page.waitForTimeout(220);assert.deepEqual(await page.locator('.topbar').boundingBox(),barBefore);assert.deepEqual(await page.locator('#writing-footer').boundingBox(),footerBefore);assert.equal(await page.evaluate(()=>scrollY),0);
  // Simulated keyboard viewport pan is ignored while its visible height is respected.
  await page.evaluate(()=>{window.testVisual=new EventTarget();Object.assign(testVisual,{height:400,offsetTop:50,scale:1});Object.defineProperty(window,'visualViewport',{configurable:true,value:testVisual});testVisual.dispatchEvent(new Event('resize'));window.dispatchEvent(new Event('resize'));});
  assert.equal(Math.round((await page.locator('.topbar').boundingBox()).y),profile.top);assert.ok((await page.locator('#writing-footer').boundingBox()).y<400);
  await page.evaluate(p=>{testVisual.height=p.height;testVisual.offsetTop=0;testVisual.dispatchEvent(new Event('resize'));window.dispatchEvent(new Event('resize'));},profile);
  // Full-document selection extends beyond CodeMirror's rendered viewport.
  await page.locator('.cm-content').click();await page.keyboard.press('Control+a');await page.waitForSelector('#selection-menu.selection-docked:not([hidden])');
  const dock=await page.locator('#selection-menu').boundingBox(),shell=await page.locator('#app').boundingBox();assert.ok(shell.y+shell.height<=dock.y+1,JSON.stringify({shell,dock}));await page.screenshot({path:'test-results/velaodt/'+profile.platform+'-selection.png'});
  await page.locator('#selection-menu').getByRole('menuitem',{name:'加入词库',exact:true}).click();assert.ok((await page.locator('#toast').textContent()).includes('不能换行'));
  await page.keyboard.press('ArrowRight');
  await page.locator('#new-doc').evaluate(b=>b.click());await page.locator('[name=name]').fill('人物.md');assert.ok((await page.locator('[name=template]').textContent()).includes('人物设定'));await page.locator('[name=template]').selectOption('character');await page.locator('#dialog-submit').click();assert.ok((await page.locator('.cm-content').textContent()).includes('# 姓名与身份'));
  // A native range selection triggers the shared menu. Its box never covers the selected word.
  await page.locator('.cm-content').click();await page.keyboard.press('Control+Home');await page.keyboard.press('Shift+End');await page.evaluate(()=>window.wenzhouShowSelectionMenu());
  await page.waitForSelector('#selection-menu:not([hidden])');const box=await page.locator('#selection-menu').boundingBox();const rect=await page.evaluate(()=>getSelection().getRangeAt(0).getBoundingClientRect().toJSON());assert.ok(box.y+box.height<=rect.top||box.y>=rect.bottom||box.x+box.width<=rect.left||box.x>=rect.right);
  assert.ok(await page.locator('#selection-menu').getByRole('menuitem',{name:'复制',exact:true}).isVisible());assert.ok(await page.locator('#selection-menu').getByRole('menuitem',{name:'加粗',exact:true}).count());
  await page.locator('#selection-menu').getByRole('menuitem',{name:'复制',exact:true}).click();assert.ok(await page.evaluate(()=>navigator.clipboard.readText()));
  await page.locator('#new-doc').evaluate(b=>b.click());await page.locator('[name=name]').fill(richName);await page.locator('[name=template]').selectOption('chapters');await page.locator('#dialog-submit').click();await page.waitForSelector('.odf-paper[contenteditable=true]');await page.locator('[aria-label="纸张大小"]').selectOption('A5');await page.locator('[aria-label="页边距"]').selectOption('1.5');
  await page.locator('.odf-paper').evaluate(paper=>{paper.focus();const p=paper.querySelector('p');p.textContent='海风与灯塔';const range=document.createRange();range.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(range);paper.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));});
  await page.locator('.odf-toolbar').getByRole('button',{name:'粗体',exact:true}).click();await page.locator('#quick-save').click();
  const source=await page.evaluate(name=>JSON.parse(localStorage.getItem('wenzhou.workspace')).documents.find(d=>d.name===name).text,richName);assert.ok(source.includes('fo:font-weight="bold"'));assert.ok(source.includes('海风与灯塔'));assert.ok(source.includes('14.8cm')&&source.includes('1.5cm'));
  const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=80;const ctx=c.getContext('2d');ctx.fillStyle='#23744e';ctx.fillRect(0,0,160,80);ctx.fillStyle='#fff';ctx.fillRect(40,20,80,40);return c.toDataURL('image/png').split(',')[1];});
  await page.locator('.odf-paper').evaluate(p=>{p.focus();const range=document.createRange();range.selectNodeContents(p);range.collapse(false);getSelection().removeAllRanges();getSelection().addRange(range);});await page.waitForTimeout(50);
  await page.locator('#preview input[type=file]').setInputFiles({name:'灯塔.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForSelector('.odf-paper img');await page.locator('.odf-paper img').click();await page.locator('[aria-label="图片宽度（px）"]').fill('120');await page.locator('.odf-image-tools button').filter({hasText:'应用图片尺寸'}).click();await page.locator('#quick-save').click();
  assert.equal(await page.locator('.odf-paper img').getAttribute('width'),'120');
  const imageSource=await page.evaluate(name=>JSON.parse(localStorage.getItem('wenzhou.workspace')).documents.find(d=>d.name===name).text,richName);assert.ok(imageSource.includes('office:binary-data'));
  const imageRoundtrip=await page.evaluate(source=>{const m=odfTest,bytes=m.flatToOdt(source),entries=m.unzipSync(bytes),flat=m.odtToFlat(bytes),html=m.odfToHtml(m.parseOdf(flat));const node=document.createElement('div');node.innerHTML=html;return {hasPackageImage:!!entries['Pictures/image1.png'],width:node.querySelector('img').width,image:node.querySelector('img').src,plain:m.odfPlainText(m.parseOdf(flat))};},imageSource);assert.ok(imageRoundtrip.hasPackageImage);assert.equal(imageRoundtrip.width,120);assert.equal(imageRoundtrip.image.split(',')[1],png);assert.ok(imageRoundtrip.plain.includes('[图片]'));
  
  await page.reload();await page.waitForSelector('[data-recent]',{state:'attached'});await openRecentFile(page,page.locator('[data-recent]').filter({hasText:richName}));await page.waitForSelector('.odf-paper');await page.addScriptTag({url:url+'/fixture.js'});if(fontCss){await page.addStyleTag({content:fontCss});await page.evaluate(()=>document.fonts.ready);}assert.ok((await page.locator('.odf-paper').textContent()).includes('海风与灯塔'));assert.equal(await page.locator('.odf-paper img').getAttribute('width'),'120');assert.equal(await page.locator('[aria-label="纸张大小"]').inputValue(),'A5');
  await page.screenshot({path:'test-results/velaodt/'+profile.platform+'.png'});
  const odf=await page.evaluate(()=>{const m=odfTest,source=m.htmlToOdf('<h1>标题 &amp; 中文</h1><p style="text-align:center;text-indent:2em"><b>粗体</b>  中文\t末尾<br>第二行</p><ul><li>甲</li><li>乙</li></ul><table><tr><td>名称</td><td>条目</td></tr></table>'),xml=m.parseOdf(source),html=m.odfToHtml(xml),text=m.odfPlainText(xml),bytes=m.flatToOdt(source),flat=m.odtToFlat(bytes);let denied=false;try{m.parseOdf('<!DOCTYPE a [<!ENTITY b SYSTEM "file:///x">]><a/>');}catch{denied=true;}const attachmentFlat=m.odtToFlat(m.zipSync({...m.unzipSync(bytes),'Object1/content.xml':new Uint8Array([1,2])}));const resourceDenied=!!m.unzipSync(m.flatToOdt(attachmentFlat))['Object1/content.xml'];return {source:m.exportFlatOdf(source),text,html,roundtrip:m.odfPlainText(m.parseOdf(flat)),mimeStored:bytes[8]===0&&bytes[9]===0,extraEmpty:bytes[28]===0&&bytes[29]===0,denied,resourceDenied,readonly:!m.parseOdf(flat).documentElement.hasAttributeNS(m.NS.vela,'profile')};});
  if(profile.platform==='windows'){await writeFile('test-results/velaodt/interop.fodt',odf.source);await writeFile('test-results/velaodt/image-interop.vodt',imageSource);await writeFile('test-results/velaodt/image-interop.fodt',await page.evaluate(source=>odfTest.exportFlatOdf(source),imageSource));}
  assert.equal(odf.text,odf.roundtrip);assert.ok(odf.text.includes('  中文\t末尾\n第二行'));assert.ok(odf.html.includes('font-weight: bold'));assert.ok(odf.mimeStored&&odf.extraEmpty&&odf.denied&&odf.resourceDenied&&odf.readonly);
  checks.push({platform:profile.platform,layout:'fixed',template:'filtered',selection:'copy and avoidance',richtext:'bold/images/resize/save/reopen',alias:richName.endsWith('.vodt')?'vodt':'velaodt',odf:'ODT roundtrip / DTD / resources'});await context.close();
 }
 assert.deepEqual(errors,[]);await writeFile('test-results/velaodt/results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify(checks));
}catch(error){if(lastPage&&!lastPage.isClosed()){console.log(await lastPage.evaluate(()=>({owns:window.wenzhouOwnsSelectionMenu(),selection:getSelection().toString(),active:document.activeElement?.outerHTML.slice(0,200),menu:document.querySelector('#selection-menu').outerHTML.slice(0,300),ui:document.body.dataset.ui,selectionCount:document.querySelector('#selection-count').textContent,scroll:document.querySelector('.cm-scroller').scrollTop,editorRect:document.querySelector('#editor').getBoundingClientRect().toJSON(),doc:document.querySelector('.cm-content').textContent.slice(0,200)})));await lastPage.screenshot({path:'test-results/velaodt/failure.png'});}throw error;}finally{await browser.close();server.close();}
