import {imageData,imageMime,bytesToBase64} from './images.mjs';
// Flat ODF: UTF-8 source stays compatible with the existing text workspace/Git path.
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
export const NS={draw:'urn:oasis:names:tc:opendocument:xmlns:drawing:1.0',svg:'urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0',office:'urn:oasis:names:tc:opendocument:xmlns:office:1.0',text:'urn:oasis:names:tc:opendocument:xmlns:text:1.0',style:'urn:oasis:names:tc:opendocument:xmlns:style:1.0',fo:'urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0',table:'urn:oasis:names:tc:opendocument:xmlns:table:1.0',xlink:'http://www.w3.org/1999/xlink',vela:'urn:wenzhou:velaodt:1'};
const mime='application/vnd.oasis.opendocument.text';
export const xmlEscape=s=>String(s).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'\ufffd').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const namespaces=Object.entries(NS).map(([k,v])=>`xmlns:${k}="${v}"`).join(' ');
export function createVelaOdt(headings=[]){return `<?xml version="1.0" encoding="UTF-8"?>\n<office:document ${namespaces} office:version="1.3" office:mimetype="${mime}" vela:profile="1"><office:styles/><office:automatic-styles/><office:body><office:text>${headings.length?headings.map(h=>`<text:h text:outline-level="1">${xmlEscape(h)}</text:h><text:p/>`).join(''):'<text:p/>'}</office:text></office:body></office:document>\n`;}
export function parseOdf(source){
 if(typeof source!=='string'||new TextEncoder().encode(source).length>8*1024*1024)throw Error('文档超过 8 MB。');
 if(/<!DOCTYPE|<!ENTITY/i.test(source))throw Error('不允许 XML 外部实体或 DTD。');
 const xml=new DOMParser().parseFromString(source,'application/xml');if(xml.querySelector('parsererror'))throw Error('ODF XML 格式错误；可切换源码修复，原文保留。');
 if(xml.documentElement.namespaceURI!==NS.office||!['document','document-content'].includes(xml.documentElement.localName)||!xml.getElementsByTagNameNS(NS.office,'body').length)throw Error('不是 ODF 文本文档。');
 const stack=[[xml.documentElement,0]];let count=0;while(stack.length){const [node,depth]=stack.pop();if(depth>80||++count>100000)throw Error('ODF XML 结构超出限制。');for(const child of node.children)stack.push([child,depth+1]);}return xml;
}
function nodeText(node){if(node.namespaceURI===NS.office&&node.localName==='binary-data')return '';if(node.namespaceURI===NS.draw&&node.localName==='frame')return '[图片]';if(node.nodeType===3)return node.nodeValue||'';if(node.namespaceURI===NS.text){if(node.localName==='s')return ' '.repeat(Math.min(10000,Number(node.getAttributeNS(NS.text,'c'))||1));if(node.localName==='tab')return '\t';if(node.localName==='line-break')return '\n';}return [...node.childNodes].map(nodeText).join('');}
export function odfPlainText(xml){return [...xml.getElementsByTagNameNS(NS.office,'body')[0].querySelectorAll('*')].filter(e=>e.namespaceURI===NS.text&&['p','h'].includes(e.localName)).map(nodeText).join('\n');}
export {odfToHtml} from './renderer.mjs';
export function htmlToOdf(html){
 const root=document.createElement('div');root.innerHTML=html;let serial=0;const styles=[];
 function attrs(el,family){const props={};const style=el.style;
 if(['B','STRONG'].includes(el.tagName)||style.fontWeight==='bold')props['fo:font-weight']='bold';if(['I','EM'].includes(el.tagName)||style.fontStyle==='italic')props['fo:font-style']='italic';
 if(el.tagName==='U'||style.textDecoration.includes('underline'))props['style:text-underline-style']='solid';if(['S','STRIKE','DEL'].includes(el.tagName)||style.textDecoration.includes('line-through'))props['style:text-line-through-style']='solid';
 let color=style.color||el.getAttribute('color');if(color?.startsWith('rgb'))color='#'+(color.match(/\d+/g)||[]).slice(0,3).map(n=>Number(n).toString(16).padStart(2,'0')).join('');if(/^#[a-f\d]{6}$/i.test(color||''))props['fo:color']=color;
 if(style.fontFamily&&style.fontFamily.length<160&&!/[;{}<>]/.test(style.fontFamily))props['fo:font-family']=style.fontFamily;let background=style.backgroundColor;if(background?.startsWith('rgb'))background='#'+(background.match(/\d+/g)||[]).slice(0,3).map(n=>Number(n).toString(16).padStart(2,'0')).join('');if(/^#[a-f\d]{6}$/i.test(background||''))props['fo:background-color']=background;if(el.tagName==='SUP'||style.verticalAlign==='super')props['style:text-position']='super 58%';if(el.tagName==='SUB'||style.verticalAlign==='sub')props['style:text-position']='sub 58%';
 const size=style.fontSize;if(/^\d+(\.\d+)?(pt|px)$/.test(size))props['fo:font-size']=size;
 const para={};for(const [property,attr] of [['lineHeight','line-height'],['marginTop','margin-top'],['marginBottom','margin-bottom'],['marginLeft','margin-left'],['marginRight','margin-right']])if(/^-?\d+(\.\d+)?(cm|mm|in|pt|px|em|%)$/.test(style[property]))para['fo:'+attr]=style[property];if(style.breakBefore==='page')para['fo:break-before']='page';if(/^(left|right|center|justify)$/.test(style.textAlign))para['fo:text-align']=style.textAlign;if(/^-?\d+(\.\d+)?(cm|pt|em)$/.test(style.textIndent))para['fo:text-indent']=style.textIndent.endsWith('em')?(parseFloat(style.textIndent)*16*2.54/96).toFixed(4)+'cm':style.textIndent;
 if(!Object.keys(props).length&&!Object.keys(para).length)return '';const name='v'+(++serial),attributes=o=>Object.entries(o).map(([k,v])=>`${k}="${xmlEscape(v)}"`).join(' ');styles.push(`<style:style style:name="${name}" style:family="${family}">${Object.keys(props).length?'<style:text-properties '+attributes(props)+'/>':''}${Object.keys(para).length?'<style:paragraph-properties '+attributes(para)+'/>':''}</style:style>`);return ` text:style-name="${name}"`;
 }
 function render(n){if(n.nodeType===3)return xmlEscape(n.nodeValue).replace(/ {2,}/g,s=>`<text:s text:c="${s.length}"/>`).replace(/\t/g,'<text:tab/>');if(n.nodeType!==1)return '';if(['SCRIPT','STYLE','IFRAME','OBJECT'].includes(n.tagName))return '';if(n.tagName==='IMG'){const image=imageData(n.getAttribute('src')),width=Math.max(1,Math.min(1600,parseFloat(n.style.width)||n.width||640)),height=Math.max(1,Math.min(1600,n.height||width*.75));return `<draw:frame draw:name="Image${++serial}" text:anchor-type="as-char" svg:width="${(width*2.54/96).toFixed(4)}cm" svg:height="${(height*2.54/96).toFixed(4)}cm"><draw:image draw:mime-type="${image.mime}"><office:binary-data>${image.base64}</office:binary-data></draw:image><svg:title>${xmlEscape(n.alt||'图片')}</svg:title></draw:frame>`;}
 const tag=n.tagName,kids=()=>[...n.childNodes].map(render).join('');if(tag==='BR')return '<text:line-break/>';if(/^H[1-6]$/.test(tag))return `<text:h text:outline-level="${tag[1]}"${attrs(n,'paragraph')}>${kids()}</text:h>`;if(tag==='DIV'&&[...n.children].some(e=>/^(P|DIV|H[1-6]|UL|OL|TABLE)$/.test(e.tagName)))return kids();if(['DIV','P'].includes(tag))return `<text:p${attrs(n,'paragraph')}>${kids()}</text:p>`;
 if(tag==='UL'||tag==='OL'){const name='list'+(++serial);styles.push('<text:list-style style:name="'+name+'">'+Array.from({length:10},(_,i)=>tag==='OL'?'<text:list-level-style-number text:level="'+(i+1)+'" style:num-format="1" style:num-suffix="."/>':'<text:list-level-style-bullet text:level="'+(i+1)+'" text:bullet-char="•"/>').join('')+'</text:list-style>');return '<text:list text:style-name="'+name+'">'+kids()+'</text:list>';}if(tag==='LI'){const hasBlock=[...n.children].some(e=>['P','DIV'].includes(e.tagName));return '<text:list-item>'+(hasBlock?kids():'<text:p>'+kids()+'</text:p>')+'</text:list-item>';}
 if(tag==='TABLE'){let columns=1;const pending=[],rows=[];for(const row of [...n.querySelectorAll('tr')].filter(row=>row.closest('table')===n)){let column=0,content='';const covered=()=>{while(pending[column]>0){content+='<table:covered-table-cell/>';pending[column]--;column++;}};for(const cell of row.children){covered();const width=Math.max(1,Math.min(100,cell.colSpan||1)),height=Math.max(1,Math.min(100,cell.rowSpan||1));content+=render(cell);for(let i=0;i<width;i++)pending[column+i]=height-1;column+=width;}while(column<pending.length){if(pending[column]>0){content+='<table:covered-table-cell/>';pending[column]--;}else content+='<table:table-cell><text:p/></table:table-cell>';column++;}columns=Math.max(columns,column);rows.push('<table:table-row>'+content+'</table:table-row>');}return '<table:table table:name="Table'+(++serial)+'"><table:table-column table:number-columns-repeated="'+columns+'"/>'+rows.join('')+'</table:table>';}if(tag==='TR')return '<table:table-row>'+kids()+'</table:table-row>';if(['TD','TH'].includes(tag)){const span=Math.max(1,Math.min(100,Number(n.colSpan)||1)),rows=Math.max(1,Math.min(100,Number(n.rowSpan)||1)),block=[...n.children].some(e=>/^(P|DIV|H[1-6]|UL|OL|TABLE)$/.test(e.tagName));return '<table:table-cell office:value-type="string"'+(span>1?' table:number-columns-spanned="'+span+'"':'')+(rows>1?' table:number-rows-spanned="'+rows+'"':'')+'>'+(block?kids():'<text:p>'+kids()+'</text:p>')+'</table:table-cell>'+Array.from({length:span-1},()=>'<table:covered-table-cell/>').join('');}if(['TBODY','THEAD','TFOOT'].includes(tag))return kids();
 if(tag==='A'){const href=n.getAttribute('href')||'';return /^(https?:|mailto:|#)/i.test(href)?`<text:a xlink:href="${xmlEscape(href)}">${kids()}</text:a>`:kids();}return `<text:span${attrs(n,'text')}>${kids()}</text:span>`;
 }
 let content='';for(const n of root.childNodes){const block=n.nodeType===1&&/^(P|DIV|H[1-6]|UL|OL|TABLE)$/.test(n.tagName);content+=block?render(n):'<text:p>'+render(n)+'</text:p>';}
 return createVelaOdt().replace('<office:automatic-styles/>','<office:automatic-styles>'+styles.join('')+'</office:automatic-styles>').replace('<text:p/>',content||'<text:p/>');
}

export {odfToFlat,odtToFlat,flatToOdfPackage,flatToOdt,exportFlatOdf,packageInfo} from './package.mjs';
