import {loadImage} from './images.mjs';
import {NS,parseOdf,odfToHtml,htmlToOdf,odfPlainText,flatToOdt,exportFlatOdf} from './engine.mjs';
import {preserveDocumentSettings,configurePage} from './page-layout.mjs';
import {packageInfo} from './package.mjs';
import {captureParagraphs,patchParagraphs} from './preserve-edit.mjs';
export function renderVelaOdt({root,doc,onChange,onCopy,onError,onGlossary,exportText,exportBinary}){
 root.classList.add('velaodt-preview');root.replaceChildren();
 let xml;try{xml=parseOdf(doc.text);}catch(e){root.textContent=e.message;return;}
 const info=packageInfo(xml),isText=!!xml.getElementsByTagNameNS(NS.office,'text').length,simple=isText&&!info.signed&&xml.documentElement.getAttributeNS(NS.vela,'profile')==='1'&&!xml.getElementsByTagNameNS(NS.vela,'package').length,compatible=isText&&!info.signed&&!simple&&![...xml.getElementsByTagNameNS(NS.table,'table-row'),...xml.getElementsByTagNameNS(NS.table,'table-cell')].some(n=>Number(n.getAttributeNS(NS.table,'number-rows-repeated'))>1||Number(n.getAttributeNS(NS.table,'number-columns-repeated'))>1),editable=simple||compatible;let source=doc.text;
 const toolbar=document.createElement('div');toolbar.className='odf-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','富文本排版');
 const scroll=document.createElement('div');scroll.className='odf-scroll';const paper=document.createElement('div');paper.className='odf-paper';paper.contentEditable=String(simple);paper.setAttribute('role','textbox');paper.setAttribute('aria-label','富文本文稿');paper.setAttribute('aria-multiline','true');paper.innerHTML=odfToHtml(xml,{editing:compatible})||'<p><br></p>';scroll.append(paper);let snapshots=captureParagraphs(paper),savedHtml=paper.innerHTML;
 let savedRange=null,selectedImage=null;const remember=()=>{const s=getSelection();if(s.rangeCount&&paper.contains(s.anchorNode)&&paper.contains(s.focusNode))savedRange=s.getRangeAt(0).cloneRange();};document.addEventListener('selectionchange',remember);
 // Replace the previous listener when re-rendering this one preview surface.
 root.odfDispose?.();root.odfDispose=()=>document.removeEventListener('selectionchange',remember);
 const restore=()=>{if(simple)paper.focus();if(savedRange&&paper.contains(savedRange.commonAncestorContainer)){const s=getSelection();s.removeAllRanges();s.addRange(savedRange);}};
 const sync=()=>{if(!editable)return;try{const next=compatible?patchParagraphs(source,paper,snapshots):preserveDocumentSettings(source,htmlToOdf(paper.innerHTML));parseOdf(next);onChange(next);source=next;snapshots=captureParagraphs(paper);savedHtml=paper.innerHTML;}catch(error){paper.innerHTML=savedHtml;savedRange=null;throw error;}};
 const command=(name,value=null)=>{if(!editable)return;if(compatible&&!['bold','italic','underline','strikeThrough','superscript','subscript','justifyLeft','justifyCenter','justifyFull','justifyRight','removeFormat','insertText','undo','redo','foreColor','hiliteColor'].includes(name))throw Error('结构编辑请创建简化副本；原文的对象和复杂样式会保留。');restore();document.execCommand(name,false,value);remember();sync();};
 const button=(label,fn,mutates=false)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=mutates===2?!simple:mutates&&!editable;b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{try{Promise.resolve(fn()).catch(onError);}catch(e){onError(e);}};toolbar.append(b);return b;};
 for(const [label,name,value] of [['粗体','bold'],['斜体','italic'],['下划线','underline'],['删除线','strikeThrough'],['正文','formatBlock','p'],['标题','formatBlock','h1'],['左对齐','justifyLeft'],['居中','justifyCenter'],['两端对齐','justifyFull'],['有序列表','insertOrderedList'],['上标','superscript'],['下标','subscript'],['右对齐','justifyRight'],['列表','insertUnorderedList'],['清除格式','removeFormat']])button(label,()=>command(name,value),['formatBlock','insertUnorderedList','insertOrderedList'].includes(name)?2:true);
 const sizes=document.createElement('select');sizes.setAttribute('aria-label','字号');for(const n of [12,14,16,18,20,24,28,32]){const o=document.createElement('option');o.value=n;o.textContent=n+' pt';sizes.append(o);}sizes.value='16';sizes.disabled=!editable;sizes.onchange=()=>{restore();const selection=getSelection();if(!selection.rangeCount||selection.isCollapsed)return;const range=selection.getRangeAt(0),span=document.createElement('span');span.style.fontSize=sizes.value+'pt';span.append(range.extractContents());range.insertNode(span);range.selectNodeContents(span);selection.removeAllRanges();selection.addRange(range);remember();sync();};toolbar.append(sizes);
 const color=document.createElement('input');color.type='color';color.setAttribute('aria-label','文字颜色');color.disabled=!editable;color.onchange=()=>command('foreColor',color.value);toolbar.append(color);
 const fonts=document.createElement('select');fonts.setAttribute('aria-label','字体');for(const name of ['system-ui','serif','sans-serif','monospace','SimSun','Microsoft YaHei']){const o=document.createElement('option');o.value=name;o.textContent=name;fonts.append(o);}fonts.disabled=!simple;fonts.onchange=()=>{restore();document.execCommand('fontName',false,fonts.value);paper.querySelectorAll('font[face]').forEach(el=>{el.style.fontFamily=el.getAttribute('face');});sync();};toolbar.append(fonts);
 const spacing=document.createElement('select');spacing.setAttribute('aria-label','行距');for(const value of ['100%','125%','150%','180%','200%']){const o=document.createElement('option');o.value=value;o.textContent='行距 '+value;spacing.append(o);}spacing.value='180%';spacing.disabled=!editable;spacing.onchange=()=>{restore();const paragraph=getSelection().anchorNode?.parentElement?.closest('p,h1,h2,h3,h4,h5,h6');if(paragraph&&paper.contains(paragraph)){paragraph.style.lineHeight=spacing.value;sync();}};toolbar.append(spacing);
 const pageSize=document.createElement('select');pageSize.setAttribute('aria-label','纸张大小');for(const value of ['A4','A5','Letter']){const o=document.createElement('option');o.value=value;o.textContent=value;pageSize.append(o);}pageSize.disabled=!simple;
 const margins=document.createElement('select');margins.setAttribute('aria-label','页边距');for(const value of ['1','1.5','2','2.5','3']){const o=document.createElement('option');o.value=value;o.textContent='边距 '+value+' cm';margins.append(o);}margins.value='2.5';margins.disabled=!simple;
 const applyPage=()=>{try{const next=configurePage(source,pageSize.value,Number(margins.value));onChange(next);source=next;paper.style.maxWidth={A4:'794px',A5:'559px',Letter:'816px'}[pageSize.value];paper.style.padding=Number(margins.value)*96/2.54+'px';}catch(e){onError(e);}};pageSize.onchange=applyPage;margins.onchange=applyPage;toolbar.append(pageSize,margins);
 const pageProps=xml.getElementsByTagNameNS(NS.style,'page-layout-properties')[0];if(pageProps){const width=pageProps.getAttributeNS(NS.fo,'page-width'),margin=pageProps.getAttributeNS(NS.fo,'margin');pageSize.value=width==='14.8cm'?'A5':width==='21.59cm'?'Letter':'A4';if(['1','1.5','2','2.5','3'].includes(String(parseFloat(margin))))margins.value=String(parseFloat(margin));paper.style.maxWidth={A4:'794px',A5:'559px',Letter:'816px'}[pageSize.value];if(/^\d+(\.\d+)?cm$/.test(margin))paper.style.padding=parseFloat(margin)*96/2.54+'px';}
 button('首行缩进',()=>{restore();let node=getSelection().anchorNode?.parentElement?.closest('p,h1,h2,h3,div');if(node&&node!==paper&&paper.contains(node)){node.style.textIndent=node.style.textIndent?'':'2em';sync();}},true);
 button('表格',()=>command('insertHTML','<table><tbody><tr><td>项目</td><td>内容</td></tr><tr><td><br></td><td><br></td></tr></tbody></table><p><br></p>'),2);
 const picker=document.createElement('input');picker.type='file';picker.accept='image/png,image/jpeg,image/gif,image/webp';picker.hidden=true;root.append(picker);
 button('插入图片',()=>{remember();picker.click();},2);
 picker.onchange=async()=>{try{const file=picker.files[0];if(!file)return;const before=paper.innerHTML;const image=await loadImage(file);restore();const img=document.createElement('img');img.src=image.src;img.alt=file.name;const width=Math.min(640,image.width);img.width=width;img.height=Math.round(image.height*width/image.width);const selection=getSelection(),range=selection.rangeCount&&paper.contains(selection.anchorNode)?selection.getRangeAt(0):null;
   if(range){range.deleteContents();range.insertNode(img);range.setStartAfter(img);range.collapse(true);selection.removeAllRanges();selection.addRange(range);}else paper.append(img);
   try{sync();}catch(error){paper.innerHTML=before;savedRange=null;throw error;}remember();
  }catch(error){onError(error);}finally{picker.value='';}};
 const imageTools=document.createElement('div');imageTools.className='odf-image-tools';imageTools.hidden=true;
 const widthInput=document.createElement('input');widthInput.type='number';widthInput.min='24';widthInput.max='1600';widthInput.setAttribute('aria-label','图片宽度（px）');
 const altInput=document.createElement('input');altInput.type='text';altInput.maxLength=160;altInput.placeholder='图片说明';altInput.setAttribute('aria-label','图片说明');
 const resize=document.createElement('button');resize.type='button';resize.textContent='应用图片尺寸';resize.onclick=()=>{try{if(!simple||!selectedImage)return;const width=Math.round(Number(widthInput.value));if(width<24||width>1600)throw Error('图片宽度需要在 24–1600 px 之间。');const ratio=selectedImage.height/selectedImage.width;selectedImage.width=width;selectedImage.height=Math.round(width*ratio);selectedImage.alt=altInput.value;sync();}catch(error){onError(error);}};
 const remove=document.createElement('button');remove.type='button';remove.textContent='删除图片';remove.onclick=()=>{selectedImage?.remove();selectedImage=null;imageTools.hidden=true;sync();};imageTools.append(widthInput,altInput,resize,remove);toolbar.append(imageTools);
 paper.addEventListener('click',event=>{if(!simple)return;paper.querySelectorAll('img').forEach(img=>img.classList.remove('odf-image-selected'));selectedImage=event.target.closest('img');imageTools.hidden=!selectedImage;if(selectedImage){selectedImage.classList.add('odf-image-selected');widthInput.value=selectedImage.width;altInput.value=selectedImage.alt;}});
 button('撤回',()=>command('undo'),true);button('重做',()=>command('redo'),true);
 button('导出 TXT',()=>exportText(doc.name.replace(/\.[^.]+$/i,'.txt'),odfPlainText(parseOdf(source))));
 const flatExt=isText?'fodt':info.extension.startsWith('ods')||info.extension==='ots'?'fods':info.extension==='odp'||info.extension==='otp'?'fodp':'fodg';
 button('导出 '+flatExt.toUpperCase(),()=>exportText(doc.name.replace(/\.[^.]+$/i,'.'+flatExt),exportFlatOdf(source)));
 button('导出 VODT（完整资源）',()=>exportText(doc.name.replace(/\.[^.]+$/i,'.vodt'),source));
 button('导出 '+info.extension.toUpperCase(),()=>exportBinary(doc.name.replace(/\.[^.]+$/i,'.'+info.extension),flatToOdt(source),info.mime));
 if(!simple){const note=document.createElement('p');note.className='odf-notice';note.textContent=info.signed?'数字签名文档只读；未修改导出保留签名文件，不校验签名真实性。':compatible?'兼容编辑：可编辑普通段落及字体样式；字段、书签、修订、对象段落受保护。布局、公式、图表和全部包附件保留；复杂分页可能与原软件不同。':isText?'此文档含重复表格结构，采用只读预览保留全部 XML；结构编辑请创建简化副本。':'基础预览：显示工作表缓存值、幻灯片或绘图文字和位图；不进行公式计算、幻灯片动画或精确绘图布局。全部原包资源保留。';root.append(note);if(isText&&!info.signed)button('创建简化可编辑副本',()=>onCopy(htmlToOdf(paper.innerHTML)));}
 root.append(toolbar,scroll);
 paper.addEventListener('beforeinput',e=>{if(compatible&&['insertParagraph','insertOrderedList','insertUnorderedList'].includes(e.inputType)){e.preventDefault();onError(Error('兼容编辑保留原段落结构；请创建简化副本进行结构编辑。'));}});
 paper.oninput=()=>{try{sync();}catch(error){onError(error);}};paper.onpaste=e=>{e.preventDefault();if(editable)command('insertText',e.clipboardData?.getData('text/plain')||'');};
 paper.addEventListener('click',e=>{if(e.target.closest('a'))e.preventDefault();});
 paper.odfCommand=command;paper.odfSync=sync;paper.odfGlossary=onGlossary;
}
