import {unzipSync} from 'fflate';
import DOMPurify from 'dompurify';
export const MAX_BOOK_BYTES=32*1024*1024;
const MAX_EXPANDED=64*1024*1024,MAX_CHAPTER=8*1024*1024;
const utf8=new TextDecoder('utf-8',{fatal:true});
const elements=(root,name)=>[...root.getElementsByTagNameNS('*',name)];
const first=(root,name)=>elements(root,name)[0];
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function xml(data){let text=decodeText(data);if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('电子书包含不支持的 XML 实体。');const doc=new DOMParser().parseFromString(text,'application/xml');if(first(doc,'parsererror'))throw Error('电子书 XML 格式错误。');return doc;}
export function decodeText(bytes){if(bytes[0]===255&&bytes[1]===254)return new TextDecoder('utf-16le',{fatal:true}).decode(bytes);if(bytes[0]===254&&bytes[1]===255)return new TextDecoder('utf-16be',{fatal:true}).decode(bytes);try{return utf8.decode(bytes);}catch{return new TextDecoder('gb18030',{fatal:true}).decode(bytes);}}
export function bookPath(base,href){if(typeof href!=='string'||/^[a-z][\w+.-]*:|^\/|\\|[\x00-\x1f]/i.test(href))throw Error('电子书资源路径无效。');let decoded;try{decoded=decodeURIComponent(href.split(/[?#]/)[0]);}catch{throw Error('电子书资源 URL 无效。');}if(/^[a-z][\w+.-]*:|^\/|\\|[\x00-\x1f]/i.test(decoded))throw Error('电子书资源路径无效。');const parts=base.split('/').slice(0,-1);for(const part of decoded.split('/')){if(part==='..'){if(!parts.length)throw Error('电子书资源越过包根目录。');parts.pop();}else if(part&&part!=='.')parts.push(part);}return parts.join('/');}
function archive(bytes){let total=0,count=0;const seen=new Set();return unzipSync(bytes,{filter:file=>{if(file.name.endsWith('/'))return false;if(!file.name||file.name.startsWith('/')||file.name.includes('\\')||/[\x00-\x1f]/.test(file.name)||file.name.split('/').some(p=>!p||p==='.'||p==='..')||seen.has(file.name))throw Error('电子书 ZIP 包含无效或重复路径。');seen.add(file.name);total+=file.originalSize;if(total>MAX_EXPANDED||++count>2048||file.originalSize>MAX_BOOK_BYTES)throw Error('电子书解压限 64 MB / 2048 文件，单文件限 32 MB。');return true;}});}
function dataImage(data,mime){if(!data||data.length>4*1024*1024)return null;const actual=data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71?'image/png':data[0]===255&&data[1]===216?'image/jpeg':String.fromCharCode(...data.slice(0,3))==='GIF'?'image/gif':String.fromCharCode(...data.slice(0,4))==='RIFF'&&String.fromCharCode(...data.slice(8,12))==='WEBP'?'image/webp':null;if(!actual||mime&&mime!==actual&&mime!=='image/jpg')return null;let binary='';for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));return 'data:'+actual+';base64,'+btoa(binary);}
export function safeChapter(html,path,files={},images={}){
  if(new TextEncoder().encode(html).length>MAX_CHAPTER)throw Error('单章正文超过 8 MB。');
  const fragment=DOMPurify.sanitize(html,{RETURN_DOM_FRAGMENT:true,ALLOWED_TAGS:['p','div','span','section','article','h1','h2','h3','h4','h5','h6','strong','b','em','i','u','s','sup','sub','br','hr','blockquote','pre','code','ul','ol','li','table','thead','tbody','tr','th','td','caption','img','a','ruby','rt','rp'],ALLOWED_ATTR:['id','alt','src','href','recindex','colspan','rowspan'],ALLOW_DATA_ATTR:false});
  let imageBytes=0;
  for(const image of fragment.querySelectorAll('img')){let src=null;const index=image.getAttribute('recindex');if(index)src=images[index];else{try{src=dataImage(files[bookPath(path,image.getAttribute('src')||'')]);}catch{}}if(src&&imageBytes+src.length<=12*1024*1024){imageBytes+=src.length;image.setAttribute('src',src);image.removeAttribute('recindex');}else{const missing=document.createElement('span');missing.textContent='[图片：'+(image.getAttribute('alt')||'无法显示')+']';image.replaceWith(missing);}}
  for(const link of fragment.querySelectorAll('a')){const href=link.getAttribute('href');if(!href?.startsWith('#'))link.removeAttribute('href');}
  const container=document.createElement('div');container.append(fragment);return container.innerHTML;
}
function epub(bytes,name){const files=archive(bytes);if(utf8.decode(files.mimetype||new Uint8Array()).trim()!=='application/epub+zip')throw Error('不是有效的 EPUB 文件。');if(files['META-INF/encryption.xml']){const encryption=xml(files['META-INF/encryption.xml']);const methods=elements(encryption,'EncryptionMethod');if(methods.some(e=>!['http://www.idpf.org/2008/embedding','http://ns.adobe.com/pdf/enc#RC'].includes(e.getAttribute('Algorithm'))))throw Error('此 EPUB 含加密或 DRM 内容，阅读组件不支持。');}
  const container=files['META-INF/container.xml'];if(!container)throw Error('EPUB 缺少 container.xml。');const root=elements(xml(container),'rootfile').find(e=>e.getAttribute('media-type')==='application/oebps-package+xml');const path=bookPath('',root?.getAttribute('full-path')||'');if(!files[path])throw Error('EPUB 缺少 OPF 包文档。');const opf=xml(files[path]),manifest=first(opf,'manifest'),spine=first(opf,'spine');if(!manifest||!spine)throw Error('EPUB 缺少资源清单或阅读顺序。');
  const items=new Map(elements(manifest,'item').map(e=>[e.getAttribute('id'),{path:bookPath(path,e.getAttribute('href')||''),type:e.getAttribute('media-type'),properties:e.getAttribute('properties')||''}]));const labels=new Map();
  const nav=[...items.values()].find(item=>item.properties.split(/\s+/).includes('nav')),ncx=items.get(spine.getAttribute('toc'));
  if(nav&&files[nav.path]){const doc=xml(files[nav.path]);for(const e of elements(doc,'a'))try{const p=bookPath(nav.path,e.getAttribute('href'));if(!labels.has(p))labels.set(p,e.textContent.trim());}catch{}}
  else if(ncx&&files[ncx.path]){for(const point of elements(xml(files[ncx.path]),'navPoint')){const content=first(point,'content');if(content)try{const p=bookPath(ncx.path,content.getAttribute('src'));if(!labels.has(p))labels.set(p,first(point,'text')?.textContent.trim());}catch{}}}
  const chapters=[];for(const ref of elements(spine,'itemref')){if(ref.getAttribute('linear')==='no')continue;const item=items.get(ref.getAttribute('idref'));if(!item||!files[item.path])throw Error('EPUB 阅读顺序引用了缺失资源。');if(!['application/xhtml+xml','text/html'].includes(item.type))throw Error('此 EPUB 含不支持的非 HTML 正文。');const text=decodeText(files[item.path]);if(text.length>MAX_CHAPTER)throw Error('单章正文超过 8 MB。');const title=labels.get(item.path)||new DOMParser().parseFromString(text,'text/html').querySelector('h1,h2,title')?.textContent.trim()||'第 '+(chapters.length+1)+' 节';chapters.push({title,path:item.path,html:text});}
  if(!chapters.length)throw Error('EPUB 没有可阅读的正文。');return {title:first(opf,'title')?.textContent.trim()||name,author:elements(opf,'creator').map(e=>e.textContent.trim()).join('、'),format:'EPUB',chapters,files};
}
function fb2(bytes,name){if(/\.zip$/i.test(name)){const entries=archive(bytes),paths=Object.keys(entries).filter(p=>/\.fb2$/i.test(p));if(paths.length!==1)throw Error('FB2 ZIP 必须仅含一本 .fb2 电子书。');bytes=entries[paths[0]];}
  const doc=xml(bytes);if(doc.documentElement.localName!=='FictionBook')throw Error('不是有效的 FB2 文件。');const images={};for(const binary of elements(doc,'binary')){const encoded=binary.textContent.replace(/\s/g,'');if(encoded.length>6*1024*1024)continue;try{images[binary.getAttribute('id')]=dataImage(Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),binary.getAttribute('content-type'));}catch{}}
  const render=(node,depth=0)=>{if(depth>128)throw Error('FB2 层级过深。');if(node.nodeType===3)return escape(node.textContent);if(node.nodeType!==1)return '';const tag=node.localName,allowed={section:'section',title:'h2',subtitle:'h3',p:'p',strong:'strong',emphasis:'em',strikethrough:'s',sup:'sup',sub:'sub',cite:'blockquote',poem:'blockquote',stanza:'div',v:'p','text-author':'p',code:'code',table:'table',tr:'tr',th:'th',td:'td','empty-line':'br'};if(tag==='image'){const href=node.getAttributeNS('http://www.w3.org/1999/xlink','href')||node.getAttribute('href');return images[href?.replace(/^#/,'')]?'<img recindex="'+escape(href.slice(1))+'" alt="插图">':'[图片]';}const content=[...node.childNodes].map(child=>render(child,depth+1)).join(''),mapped=allowed[tag];return mapped?'<'+mapped+'>'+content+'</'+mapped+'>':content;};
  const chapters=[];for(const body of [...doc.documentElement.children].filter(e=>e.localName==='body')){const sections=[...body.children].filter(e=>e.localName==='section');const groups=sections.length?[...[...body.children].filter(e=>e.localName!=='section'),...sections]:[body];for(const section of groups){const html=render(section);if(!html.trim())continue;chapters.push({title:first(section,'title')?.textContent.trim()||'第 '+(chapters.length+1)+' 节',path:'book.fb2',html});}}
  if(!chapters.length)throw Error('FB2 没有正文。');return {title:first(doc,'book-title')?.textContent.trim()||name,author:elements(first(doc,'title-info')||doc,'author').map(e=>e.textContent.trim().replace(/\s+/g,' ')).join('、'),format:'FB2',chapters,images};
}
export function palmDoc(data,limit=MAX_BOOK_BYTES){const out=[];const push=value=>{if(out.length>=limit)throw Error('MOBI 解压超过大小限制。');out.push(value);};for(let i=0;i<data.length;i++){const value=data[i];if(value>=1&&value<=8){if(i+value>=data.length)throw Error('PalmDOC 字面量损坏。');for(let n=0;n<value;n++)push(data[++i]);}else if(value<128)push(value);else if(value>=192){push(32);push(value^128);}else{if(++i>=data.length)throw Error('PalmDOC 引用损坏。');const pair=((value&63)<<8)|data[i],distance=pair>>>3,length=(pair&7)+3;if(!distance||distance>out.length)throw Error('PalmDOC 引用越界。');for(let n=0;n<length;n++)push(out[out.length-distance]);}}return Uint8Array.from(out);}
function stripExtra(data,flags){let end=data.length;for(let bits=flags>>>1;bits;bits>>>=1){if(!(bits&1))continue;let size=0,shift=0,at=end;while(at>0&&shift<28){const byte=data[--at];size+=(byte&127)*2**shift;shift+=7;if(byte&128)break;}if(size<1||size>end||size<end-at)throw Error('MOBI 尾部记录损坏。');end-=size;}if(flags&1){if(end<1)throw Error('MOBI 尾部记录损坏。');end-=(data[end-1]&3)+1;}if(end<0)throw Error('MOBI 尾部记录越界。');return data.subarray(0,end);}
function mobi(bytes,name){if(bytes.length<86)throw Error('MOBI 文件过短。');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),count=view.getUint16(76);if(!count||count>8192||78+count*8>bytes.length)throw Error('MOBI 记录表损坏。');const offsets=Array.from({length:count},(_,i)=>view.getUint32(78+i*8));if(offsets.some((offset,i)=>offset<78+count*8||offset>=bytes.length||i&&offset<=offsets[i-1]))throw Error('MOBI 记录偏移无效。');const record=index=>bytes.subarray(offsets[index],offsets[index+1]??bytes.length),header=record(0);if(header.length<16)throw Error('MOBI 头损坏。');const h=new DataView(header.buffer,header.byteOffset,header.byteLength),compression=h.getUint16(0),textBytes=h.getUint32(4),records=h.getUint16(8);if(h.getUint16(12)!==0)throw Error('此 MOBI/AZW 含 DRM，阅读组件不支持。');if(![1,2].includes(compression))throw Error('暂不支持此 MOBI 的 HUFF/CDIC 压缩，请转为 EPUB。');if(!records||records>=count||textBytes>MAX_BOOK_BYTES)throw Error('MOBI 正文大小或记录数无效。');
  const isMobi=header.length>=40&&String.fromCharCode(...header.slice(16,20))==='MOBI';let encoding='windows-1252',flags=0,firstImage=0xffffffff,title=decodeText(bytes.slice(0,32)).replace(/\0.*$/s,'')||name;
  if(isMobi){const headerLength=h.getUint32(20);if(headerLength<24||16+headerLength>header.length)throw Error('MOBI 头长度无效。');if(h.getUint32(36)>=8)throw Error('暂不支持 KF8/AZW3/KFX 的版面重建，请使用 EPUB 或 MOBI7。');const codec=h.getUint32(28);if(![65001,1252].includes(codec))throw Error('不支持此 MOBI 的文字编码。');encoding=codec===65001?'utf-8':'windows-1252';if(headerLength>=228)flags=h.getUint16(242);if(headerLength>=96){firstImage=h.getUint32(108);const at=h.getUint32(84),length=h.getUint32(88);if(length&&at+length<=header.length)title=new TextDecoder(encoding).decode(header.slice(at,at+length));}}
  const chunks=[];let size=0;for(let i=1;i<=records;i++){const data=stripExtra(record(i),flags),chunk=compression===2?palmDoc(data,Math.min(MAX_BOOK_BYTES-size,65536)):data;size+=chunk.length;if(size>MAX_BOOK_BYTES)throw Error('MOBI 正文超过 32 MB。');chunks.push(chunk);}if(size<textBytes)throw Error('MOBI 正文不完整。');const text=new Uint8Array(size);let at=0;for(const chunk of chunks){text.set(chunk,at);at+=chunk.length;}const html=new TextDecoder(encoding,{fatal:true}).decode(text.subarray(0,textBytes)).replace(/\0/g,'');const images={};let totalImages=0;if(firstImage<count)for(let i=firstImage;i<count&&i<firstImage+512;i++){const data=record(i);totalImages+=data.length;if(totalImages>16*1024*1024)break;images[String(i-firstImage+1)]=dataImage(data);}
  return {title,author:'',format:'MOBI7',chapters:[{title,path:'book.html',html:/<\w/i.test(html)?html:'<pre>'+escape(html)+'</pre>'}],images};
}
export function readBook(bytes,name){if(!(bytes instanceof Uint8Array)||bytes.length>MAX_BOOK_BYTES)throw Error('电子书限 32 MB。');const lower=name.toLowerCase();if(lower.endsWith('.epub'))return epub(bytes,name);if(/\.fb2(?:\.zip)?$/.test(lower))return fb2(bytes,name);if(/\.(mobi|azw|azw3)$/.test(lower))return mobi(bytes,name);if(/\.(txt|html|htm)$/.test(lower)){const text=decodeText(bytes);return {title:name,author:'',format:lower.endsWith('.txt')?'TXT':'HTML',chapters:[{title:name,path:name,html:lower.endsWith('.txt')?'<pre>'+escape(text)+'</pre>':text}]};}throw Error('不支持此格式；支持 EPUB、FB2、TXT、HTML 和无 DRM 的传统 MOBI/AZW。');}
export function chapterDocument(book,index,{fontSize=20,dark=false}={}){const chapter=book.chapters[index];if(!chapter)throw Error('章节不存在。');const html=safeChapter(chapter.html,chapter.path,book.files,book.images);return '<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:24px auto;padding:0 20px;max-width:760px;line-height:1.85;overflow-wrap:anywhere;font-size:'+Math.max(12,Math.min(36,Number(fontSize)||20))+'px;background:'+(dark?'#161b22':'#fff')+';color:'+(dark?'#e8edf2':'#252a30')+'}img{max-width:100%;height:auto}pre{white-space:pre-wrap}table{max-width:100%;border-collapse:collapse}td,th{border:1px solid #888;padding:6px}h1,h2,h3{line-height:1.4}</style></head><body>'+html+'</body></html>';}
