import {PdfBook} from './pdf.mjs';
import {readBook,chapterDocument,MAX_BOOK_BYTES} from './engine.mjs';
const id='vela.component.ebook-reader';
acode.setPluginInit(id,async(base)=>{
  const api=acode.require('vela'),Page=acode.require('page'),page=new Page('电子书阅读'),root=page.body;
  let book=null,index=0,stopped=false,task=null,epoch=0,busy=false;
  const settings=api.getSettings(),progress={...(settings.readingProgress||{})};let bookKey='';
  root.innerHTML='<div class="ebook-reader" style="height:100%;display:flex;flex-direction:column;padding:12px;box-sizing:border-box"><div class="button-row" style="flex-wrap:wrap"><button data-book-import>导入电子书</button><button data-book-project>工作区书籍</button><button data-book-prev disabled>上一章</button><select aria-label="电子书章节" data-book-chapters disabled style="max-width:100%;width:240px"></select><button data-book-next disabled>下一章</button><label>字号 <input aria-label="电子书字号" type="number" min="12" max="36" value="20" data-book-font style="width:60px"></label><label><input type="checkbox" data-book-dark>夜间</label></div><p role="status" data-book-status>支持 EPUB、FB2、TXT/HTML、无 DRM 的传统 MOBI/AZW（MOBI7）。KF8/AZW3、KFX、HUFF/CDIC 暂不支持；PDF 支持分页、缩放、文字选择与搜索（不支持加密 PDF）。导入的书籍保存在工作区。</p><div data-book-list></div><div data-pdf-tools hidden><label>缩放 <select data-pdf-zoom aria-label="PDF 缩放"><option value="1">适合宽度</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select></label><input data-pdf-query aria-label="搜索 PDF" placeholder="搜索 PDF 文字"><button data-pdf-search>搜索</button><button data-pdf-search-cancel>取消搜索</button><div data-pdf-results></div></div><div class="ebook-pdf" hidden style="overflow:auto;flex:1;min-height:55vh;max-height:70vh;padding:12px"></div><iframe title="电子书正文" sandbox="" style="width:100%;flex:1;min-height:55vh;border:0" referrerpolicy="no-referrer"></iframe></div>';
  const find=s=>root.querySelector(s),frame=find('iframe'),status=find('[data-book-status]'),select=find('[data-book-chapters]'),font=find('[data-book-font]'),dark=find('[data-book-dark]');font.value=settings.fontSize||20;dark.checked=!!settings.dark;
  const pdfRoot=find('.ebook-pdf'),pdfTools=find('[data-pdf-tools]'),pdf=new PdfBook(pdfRoot,base);pdf.onError=error=>log(error);
  const log=error=>{if(!stopped)status.textContent=error.message||String(error);};
  const display=()=>{if(!book||stopped)return;const isPdf=book.format==='PDF';frame.hidden=isPdf;pdfRoot.hidden=!isPdf;pdfTools.hidden=!isPdf;font.disabled=isPdf;dark.disabled=isPdf;
    if(isPdf){frame.removeAttribute('srcdoc');pdf.page=index+1;pdf.render().catch(log);}else frame.srcdoc=chapterDocument(book,index,{fontSize:font.value,dark:dark.checked});
    select.value=String(index);find('[data-book-prev]').disabled=index===0;find('[data-book-next]').disabled=index===book.chapters.length-1;status.textContent=book.title+(book.author?' · '+book.author:'')+' · '+book.format+' · '+(index+1)+' / '+book.chapters.length;progress[bookKey]=index;const keys=Object.keys(progress);while(keys.length>100)delete progress[keys.shift()];api.updateSettings({fontSize:Number(font.value),dark:dark.checked,readingProgress:progress});};
  async function load(project,entry){const turn=++epoch;if(entry.size>MAX_BOOK_BYTES)throw Error('电子书限 32 MB。');const caps=await api.getCapabilities(),bytes=new Uint8Array(entry.size);let offset=0;while(offset<bytes.length){if(stopped||turn!==epoch)return;const part=await api.fs.readBytes({workspaceId:project.id,path:entry.path,offset,length:Math.min(caps.limits.readChunkBytes,bytes.length-offset),expectedRevision:entry.revision});if(!part.bytes.length||part.totalSize!==entry.size||part.bytes.length>bytes.length-offset)throw Error('电子书读取期间发生变化。');bytes.set(part.bytes,offset);offset+=part.bytes.length;}if(stopped||turn!==epoch)return;let next;if(/\.pdf$/i.test(entry.path)){pdfRoot.hidden=false;const metadata=await pdf.load(bytes);if(!metadata||stopped||turn!==epoch)return;next={title:metadata.title||entry.path,author:metadata.author,format:'PDF',chapters:Array.from({length:metadata.pages},(_,i)=>({title:'第 '+(i+1)+' 页'}))};}else{await pdf.close();next=readBook(bytes,entry.path);}book=next;bookKey=project.id+'/'+entry.path;index=Math.max(0,Math.min(book.chapters.length-1,Number(progress[bookKey])||0));select.replaceChildren(...book.chapters.map((chapter,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=chapter.title;return option;}));select.disabled=false;find('[data-book-list]').replaceChildren();display();}
  const run=async fn=>{if(busy)return;busy=true;find('[data-book-import]').disabled=true;find('[data-book-project]').disabled=true;try{await fn();}catch(error){log(error);}finally{busy=false;if(!stopped){find('[data-book-import]').disabled=false;find('[data-book-project]').disabled=false;}}};
  find('[data-book-import]').onclick=()=>run(async()=>{const picked=await api.io.pickFiles({multiple:false,accept:['.epub','.fb2','.zip','.mobi','.azw','.azw3','.txt','.html','.htm','.pdf']});if(picked.cancelled||!picked.selections.length)return;const selection=picked.selections[0];if(selection.size>MAX_BOOK_BYTES)throw Error('电子书限 32 MB。');if(!/\.(epub|fb2|fb2\.zip|mobi|azw|azw3|txt|html|htm|pdf)$/i.test(selection.name))throw Error('请选择支持的电子书格式。');let project=await api.workspace.current();if(!project)project=await api.workspace.create({name:'电子书'});project=await api.workspace.open({workspaceId:project.id});status.textContent='正在导入电子书…';task=api.io.importFiles({workspaceId:project.id,expectedWorkspaceRevision:project.revision,selections:[{token:selection.token,targetPath:selection.name}],collision:'rename'});let result;try{result=await task.result;}finally{task=null;}if(stopped)return;const entry=result.entries.find(e=>e.kind==='file');if(!entry)throw Error('导入结果缺少书籍文件。');await load(project,entry);});
  find('[data-book-project]').onclick=()=>run(async()=>{const project=await api.workspace.current();if(!project)throw Error('请先打开有 .vela 配置的工作区，或导入电子书。');const list=find('[data-book-list]');list.replaceChildren();let cursor;let count=0;do{const result=await api.fs.list({workspaceId:project.id,path:'',recursive:true,limit:500,...(cursor?{cursor}:{})});for(const entry of result.entries.filter(e=>e.kind==='file'&&/\.(epub|fb2|fb2\.zip|mobi|azw|azw3|txt|html|htm|pdf)$/i.test(e.path))){const button=document.createElement('button');button.textContent=entry.path;button.onclick=()=>run(()=>load(project,entry));list.append(button);count++;}cursor=result.nextCursor;}while(cursor&&!stopped);status.textContent=count?'选择一本书籍。':'当前工作区暂无支持的书籍。';});
  select.onchange=()=>{index=Number(select.value);try{display();}catch(error){log(error);}};font.onchange=dark.onchange=()=>{try{display();}catch(error){log(error);}};
  for(const [selector,direction] of [['[data-book-prev]',-1],['[data-book-next]',1]])find(selector).onclick=()=>{const previous=index;index=Math.max(0,Math.min(book.chapters.length-1,index+direction));try{display();}catch(error){index=previous;log(error);}};
  find('[data-pdf-zoom]').onchange=()=>{pdf.zoom=Number(find('[data-pdf-zoom]').value);pdf.render().catch(log);};
  find('[data-pdf-search]').onclick=()=>run(async()=>{const query=find('[data-pdf-query]').value.trim();if(!query)return;status.textContent='正在搜索 PDF…';const results=await pdf.search(query);if(stopped)return;const list=find('[data-pdf-results]');list.replaceChildren();for(const result of results){const button=document.createElement('button');button.textContent='第 '+result.page+' 页';button.title=result.quote;button.onclick=()=>{index=result.page-1;display();};list.append(button);}status.textContent=results.length?'匹配 '+results.length+' 页（最多显示 200 页）。':'没有匹配文字，或搜索已取消。';});
  find('[data-pdf-search-cancel]').onclick=()=>pdf.cancelSearch();
  page.onHide(()=>pdf.cancelSearch());
  const style=document.createElement('style');style.textContent='.ebook-pdf .pdf-page{position:relative;flex-shrink:0;margin:auto;background:white}.ebook-pdf .textLayer{position:absolute;inset:0;overflow:hidden;line-height:1;user-select:text;touch-action:pan-x pan-y;transform-origin:0 0}.ebook-pdf .textLayer :is(span,br){color:transparent;position:absolute;white-space:pre;cursor:text;transform-origin:0 0}.ebook-pdf .textLayer ::selection{background:#70b58b66}.ebook-pdf .textLayer .markedContent{display:contents}';root.append(style);
  acode.require('commands').addCommand({name:id+'.open',description:'电子书：打开阅读器',exec:()=>page.show()});
  api.dispose(()=>{stopped=true;epoch++;task?.cancel();book=null;frame.removeAttribute('srcdoc');pdf.destroy().catch(()=>{});});
});
acode.setPluginUnmount(id,()=>{});
