import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
// Uses its own packaged worker/fonts. Does not rely on the host's PDF resources.
export class PdfBook {
  constructor(root,base){this.root=root;this.base=base;this.epoch=0;this.searchEpoch=0;this.zoom=1;this.page=1;this.resize=new ResizeObserver(()=>{if(this.pdf)this.render().catch(this.onError);});this.resize.observe(root);}
  async load(bytes){await this.close();const epoch=this.epoch;const url=acode.toInternalUrl(this.base+'pdf/pdf.worker.mjs');this.workerPort=new Worker(url,{type:'module'});this.worker=new pdfjs.PDFWorker({port:this.workerPort});const base=this.base;class CMaps{async fetch({name}){const response=await fetch(acode.toInternalUrl(base+'pdf/cmaps/'+name+'.bcmap'));if(!response.ok)throw Error('PDF 字符映射资源缺失。');return {cMapData:new Uint8Array(await response.arrayBuffer()),compressionType:1};}}class Fonts{async fetch({filename}){const response=await fetch(acode.toInternalUrl(base+'pdf/fonts/'+filename));if(!response.ok)throw Error('PDF 字体资源缺失。');return new Uint8Array(await response.arrayBuffer());}}this.loading=pdfjs.getDocument({CMapReaderFactory:CMaps,StandardFontDataFactory:Fonts,data:bytes.slice(),worker:this.worker,isEvalSupported:false,useSystemFonts:true,useWorkerFetch:false,cMapUrl:this.base+'pdf/cmaps/',cMapPacked:true,standardFontDataUrl:this.base+'pdf/fonts/',maxImageSize:16000000});try{const pdf=await this.loading.promise;if(epoch!==this.epoch)return null;this.pdf=pdf;if(pdf.numPages>10000)throw Error('PDF 页数超过 10000 页限制。');const metadata=await pdf.getMetadata().catch(()=>null);return {title:metadata?.info?.Title||'',author:metadata?.info?.Author||'',pages:pdf.numPages};}catch(error){await this.close();throw error.name==='PasswordException'?Error('此 PDF 需要密码；当前组件不支持加密 PDF。'):error;}}
  async render(){if(!this.pdf)return;const pdf=this.pdf,epoch=++this.epoch;this.renderTask?.cancel();this.textLayer?.cancel();const page=await pdf.getPage(this.page);if(epoch!==this.epoch||this.pdf!==pdf)return;const unscaled=page.getViewport({scale:1}),width=Math.max(180,this.root.clientWidth-24),scale=Math.max(.1,Math.min(4,width/unscaled.width*this.zoom)),viewport=page.getViewport({scale});const density=Math.min(devicePixelRatio||1,2,Math.sqrt(16000000/(viewport.width*viewport.height))),wrap=document.createElement('div'),canvas=document.createElement('canvas'),layer=document.createElement('div');wrap.className='pdf-page';wrap.style.width=viewport.width+'px';wrap.style.height=viewport.height+'px';layer.className='textLayer';layer.style.setProperty('--scale-factor',String(scale));layer.style.setProperty('--total-scale-factor',String(scale));canvas.width=Math.max(1,Math.floor(viewport.width*density));canvas.height=Math.max(1,Math.floor(viewport.height*density));canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';wrap.append(canvas,layer);this.root.replaceChildren(wrap);this.root.scrollTop=0;this.textLayer=new pdfjs.TextLayer({textContentSource:page.streamTextContent(),container:layer,viewport});this.textLayer.render().catch(error=>{if(error.name!=='AbortException'&&epoch===this.epoch)this.onError?.(error);});this.renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:[density,0,0,density,0,0]});try{await this.renderTask.promise;}catch(error){if(error.name!=='RenderingCancelledException')throw error;}if(epoch!==this.epoch||this.pdf!==pdf)return;if(this.visiblePage&&this.visiblePage!==page)this.visiblePage.cleanup();this.visiblePage=page;}
  async search(query){const pdf=this.pdf,epoch=++this.searchEpoch,results=[];if(!pdf||!query)return results;for(let number=1;number<=pdf.numPages;number++){if(epoch!==this.searchEpoch||pdf!==this.pdf)return [];const page=await pdf.getPage(number),content=await page.getTextContent();if(epoch!==this.searchEpoch||pdf!==this.pdf)return [];const text=content.items.map(item=>item.str||'').join(' ');if(text.toLocaleLowerCase().includes(query.toLocaleLowerCase()))results.push({page:number,quote:text.slice(0,180)});if(results.length>=200)break;if(number%5===0)await new Promise(resolve=>setTimeout(resolve,0));}return results;}
  cancelSearch(){this.searchEpoch++;}
  async close(){this.epoch++;this.searchEpoch++;this.renderTask?.cancel();this.textLayer?.cancel();this.pdf=null;this.visiblePage=null;const loading=this.loading;this.loading=null;await loading?.destroy().catch(()=>{});this.worker?.destroy();this.workerPort?.terminate();this.worker=null;this.workerPort=null;this.root.replaceChildren();}
  async destroy(){this.resize.disconnect();await this.close();}
}
