import {autocompletion,completionKeymap,snippetCompletion} from '@codemirror/autocomplete';
import {keymap} from '@codemirror/view';
import {documentKind} from './model.mjs';
const registrations=new Map();
export function registerCompletion(owner,source,kinds=[]){if(typeof source!=='function')throw new Error('补全提供器必须是函数');const entry={owner,source,kinds};registrations.set(entry,entry);return ()=>registrations.delete(entry);}
export function removeCompletions(owner){for(const [key,item] of registrations)if(item.owner===owner)registrations.delete(key);}
const words={js:'const let var function return async await import export class new if else for while try catch throw true false null undefined console document window',py:'def class import from return if elif else for while try except with as pass lambda None True False print range',css:'display position color background padding margin border font-size width height flex grid',sql:'SELECT FROM WHERE JOIN INSERT UPDATE DELETE CREATE TABLE ORDER BY GROUP BY LIMIT',tex:'section subsection chapter textbf emph frac sqrt sum int begin end label ref cite includegraphics tableofcontents documentclass usepackage',json:'true false null',sh:'if then fi for do done echo cd export function',common:'if else for while return class function import'};
const snippets={JS:[['function','function ${name}(${args}) {\n  ${body}\n}'],['for','for (let ${i} = 0; ${i} < ${length}; ${i}++) {\n  ${body}\n}']],PY:[['def','def ${name}(${args}):\n    ${body}']],TEX:[['frac','\\frac{${numerator}}{${denominator}}'],['section','\\section{${title}}'],['begin','\\begin{${environment}}\n${content}\n\\end{${environment}}'],['equation','\\begin{equation}\n${formula}\n\\end{equation}']]};
export function novelCompletion(context){const word=context.matchBefore(/[\p{L}\p{N}_]{1,40}/u);if(!word||!context.explicit&&word.text.length<2)return null;const text=context.state.doc.sliceString(Math.max(0,context.pos-12000),Math.min(context.state.doc.length,context.pos+12000)),values=[...new Set(text.match(/[A-Za-z_][\w]{2,39}|[\u4e00-\u9fff]{2,8}/g)||[])];return {from:word.from,options:values.filter(value=>value!==word.text).slice(0,160).map(label=>({label,type:'text'})),validFor:/^[\p{L}\p{N}_]*$/u};}
export function formatCompletion(doc){const kind=documentKind(doc),name=doc.name.toLowerCase(),type=kind==='TEX'?'tex':/\.(js|jsx|ts|tsx|mjs|cjs)$/.test(name)?'js':/\.pyw?$/.test(name)?'py':/\.(css|scss|less)$/.test(name)?'css':/\.sql$/.test(name)?'sql':/\.(json|json5|vela)$/.test(name)?'json':/\.(sh|bash|zsh)$/.test(name)?'sh':'common';return context=>{const word=context.matchBefore(kind==='TEX'?/\\[A-Za-z]*$/:/[A-Za-z_][\w]*$/);if(!word)return null;if(!context.explicit&&word.text.length<(kind==='TEX'?2:2))return null;const prefix=kind==='TEX'?'\\':'',options=(words[type]||words.common).split(' ').map(label=>({label:prefix+label,type:'keyword'}));for(const [label,template] of snippets[type.toUpperCase()]||[])options.push(snippetCompletion(template,{label:prefix+label,detail:'snippet',type:'function',boost:5}));return {from:word.from,options,validFor:kind==='TEX'?/^\\[A-Za-z]*$/:/^\w*$/};};}
export function texContextCompletion(doc,getProject=()=>({documents:[doc],packages:[]})){return context=>{const before=context.state.doc.sliceString(Math.max(0,context.pos-240),context.pos),match=before.match(/\\(ref|eqref|autoref|cite|citep|citet|usepackage|documentclass|input|include|includegraphics|begin|end)\{([^}]*)$/);if(!match)return null;const project=getProject(),values=new Set(),command=match[1];if(/ref|cite/.test(command)){for(const item of project.documents||[doc]){const expression=/cite/.test(command)?/@\w+\s*\{\s*([^,\s]+)/g:/\\label\{([^}]+)\}/g;for(const value of item.text.matchAll(expression))values.add(value[1]);}}
else if(command==='begin'||command==='end')for(const value of ['document','equation','align','align*','gather','itemize','enumerate','figure','table','tabular','quote','verbatim'])values.add(value);
else if(command==='usepackage'||command==='documentclass'){for(const value of (command==='documentclass'?['article','report','book','ctexart','ctexrep','ctexbook']:['amsmath','amssymb','graphicx','hyperref','geometry','ctex','fontspec','xeCJK','natbib']))values.add(value);const extension=command==='usepackage'?'.sty':'.cls';for(const value of project.packages||[])if(value.endsWith(extension))values.add(value.split('/').at(-1).slice(0,-extension.length));}
else for(const item of project.documents||[])if(item.id!==doc.id)values.add(item.path||item.name);
const prefix=match[2].split(',').at(-1).trimStart();return {from:context.pos-prefix.length,options:[...values].map(label=>({label,type:'variable'})),validFor:/^[^},]*$/};};}
export function completionExtensions(doc,getProject){const kind=documentKind(doc),sources=['TXT','CSV','MD'].includes(kind)?[novelCompletion]:[formatCompletion(doc),novelCompletion];if(kind==='TEX')sources.push(texContextCompletion(doc,getProject));const custom=context=>{const results=[...registrations.values()].filter(item=>!item.kinds.length||item.kinds.includes(kind)).map(item=>Promise.resolve().then(()=>item.source(context)).catch(()=>null));return Promise.all(results).then(values=>{const valid=values.filter(Boolean);if(!valid.length)return null;const from=Math.min(...valid.map(value=>value.from));return {from,options:valid.filter(value=>value.from===from).flatMap(value=>value.options)};});};return [autocompletion({defaultKeymap:false,override:undefined}),contextData(sources.concat(custom)),keymap.of(completionKeymap.filter(binding=>binding.key!=='Tab'))];}
import {EditorState} from '@codemirror/state';
function contextData(sources){return EditorState.languageData.of(()=>sources.map(source=>({autocomplete:source})));}
