export function csvTable(rows,rowPage,columnPage,delimiter,esc){
  const columns=rows.reduce((max,row)=>Math.max(max,row.length),1),columnSize=50;
  const columnPages=Math.ceil(columns/columnSize);columnPage=Math.max(0,Math.min(columnPage,columnPages-1));
  const startColumn=columnPage*columnSize,count=Math.min(columnSize,columns-startColumn);
  const pageSize=Math.max(1,Math.min(100,Math.floor(2000/count))),pages=Math.ceil(rows.length/pageSize);rowPage=Math.max(0,Math.min(rowPage,pages-1));
  const offset=rowPage*pageSize,visible=rows.slice(offset,offset+pageSize);
  const html=`<div class="csv-toolbar"><span>${rows.length} 行 × ${columns} 列 · 第 ${rowPage+1} / ${pages} 页${columnPages>1?` · 列 ${startColumn+1}–${startColumn+count}`:''}</span><label>分隔符 <select id="csv-delimiter">${[[',','逗号'],[';','分号'],['\t','Tab']].map(([value,label])=>`<option value="${value}" ${value===delimiter?'selected':''}>${label}</option>`).join('')}</select></label><button class="secondary" id="csv-prev" ${rowPage===0?'disabled':''}>上一页</button><button class="secondary" id="csv-next" ${rowPage+1>=pages?'disabled':''}>下一页</button>${columnPages>1?`<button class="secondary" id="csv-column-prev" ${columnPage===0?'disabled':''}>左侧列</button><button class="secondary" id="csv-column-next" ${columnPage+1>=columnPages?'disabled':''}>右侧列</button>`:''}<button class="secondary" id="csv-add-row">＋ 行</button><button class="secondary" id="csv-add-column">＋ 列</button></div><div class="csv-scroll"><table aria-label="CSV 表格"><thead><tr><th>#</th>${Array.from({length:count},(_,i)=>`<th>${startColumn+i+1}</th>`).join('')}</tr></thead><tbody>${visible.map((row,i)=>{const r=i+offset;return `<tr><th>${r+1}</th>${Array.from({length:count},(_,i)=>{const c=i+startColumn,value=row[c]||'';return `<td><textarea rows="${Math.min(10,value.split('\n').length)}" aria-label="第 ${r+1} 行第 ${c+1} 列" data-cell-row="${r}" data-cell-column="${c}">${esc(value)}</textarea></td>`;}).join('')}</tr>`;}).join('')}</tbody></table></div>`;
  return {html,rowPage,columnPage,pageSize,columns};
}
