const hash=text=>{let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);};
export function remapAnchors(entries,changes,oldText,newText){
  return (entries||[]).map(entry=>{if(entry.pdfPage||entry.format==='rendered')return {...entry,needsReview:oldText!==newText||entry.needsReview};let from=entry.offset||0,to=entry.end??from,ambiguous=false;for(const change of [...changes].sort((a,b)=>b.from-a.from)){const inserted=change.insert.length,removed=change.to-change.from;if(change.to<=from){from+=inserted-removed;to+=inserted-removed;}else if(change.from<to||change.from===from&&change.to>from){ambiguous=true;to=Math.max(from,to+inserted-removed);}}
    return {...entry,offset:Math.max(0,Math.min(newText.length,from)),end:Math.max(0,Math.min(newText.length,to)),context:newText.slice(Math.max(0,from-32),from),quote:entry.quote||oldText.slice(entry.offset,entry.end),needsReview:ambiguous||entry.needsReview};});
}
export function resolveAnchor(text,anchor){const from=Math.max(0,Math.min(text.length,anchor.offset||0)),quote=anchor.quote||'';if(!quote)return {...anchor,offset:from,needsReview:false};if(text.slice(from,from+quote.length)===quote)return {...anchor,offset:from,end:from+quote.length,needsReview:false};const matches=[];let at=text.indexOf(quote);while(at>=0&&matches.length<20){matches.push(at);at=text.indexOf(quote,at+1);}const contextual=matches.filter(offset=>!anchor.context||text.slice(Math.max(0,offset-anchor.context.length),offset)===anchor.context);if(contextual.length!==1)return {...anchor,needsReview:true};return {...anchor,offset:contextual[0],end:contextual[0]+quote.length,needsReview:false};}
export class DocumentService{
  constructor({workspace,write,clock=()=>Date.now()}){Object.assign(this,{workspace,write,clock});this.baselines=new Map();this.saved=new Map();this.dirty=new Set();}
  register(doc){if(!this.baselines.has(doc.id)){this.baselines.set(doc.id,doc.text);this.saved.set(doc.id,doc.revision||0);}return doc;}
  change(doc,text,changes=[],{important=false}={}){this.register(doc);if(text===doc.text)return;const workspace=this.workspace();doc.revision=(doc.revision||0)+1;workspace.annotations={...workspace.annotations,[doc.id]:remapAnchors(workspace.annotations?.[doc.id],changes.length?changes:[{from:0,to:doc.text.length,insert:text}],doc.text,text)};doc.text=text;doc.updatedAt=this.clock();this.dirty.add(doc.id);if(important)this.snapshot(doc,true);}
  changeTree(doc,tree,changes=[]){this.register(doc);const workspace=this.workspace(),anchors=workspace.annotations?.[doc.id];if(anchors?.length)workspace.annotations[doc.id]=remapAnchors(anchors,changes,doc.text,tree.toString());let memo;Object.defineProperty(doc,'text',{configurable:true,enumerable:true,get(){return memo??(memo=tree.toString());},set(value){Object.defineProperty(this,'text',{configurable:true,enumerable:true,writable:true,value});}});doc.revision=(doc.revision||0)+1;doc.updatedAt=this.clock();this.dirty.add(doc.id);}
  snapshot(doc,force=false){const before=this.baselines.get(doc.id);if(before===undefined||before===doc.text)return;const workspace=this.workspace(),history=workspace.localHistory?.[doc.id]||[],last=history.at(-1);if(!force&&last&&this.clock()-last.createdAt<30000)return;const next=[...history,{text:before,createdAt:this.clock(),revision:this.saved.get(doc.id)||0}].slice(-10);while(next.reduce((sum,item)=>sum+item.text.length,0)>4*1024*1024&&next.length>1)next.shift();workspace.localHistory={...workspace.localHistory,[doc.id]:next};}
  save(){const workspace=this.workspace();for(const doc of workspace.documents){if(this.baselines.has(doc.id)&&this.baselines.get(doc.id)!==doc.text&&!this.dirty.has(doc.id)){doc.revision=(doc.revision||0)+1;if(workspace.annotations?.[doc.id]?.length)workspace.annotations[doc.id]=remapAnchors(workspace.annotations[doc.id],[{from:0,to:this.baselines.get(doc.id).length,insert:doc.text}],this.baselines.get(doc.id),doc.text);this.dirty.add(doc.id);}}const versions=new Map(workspace.documents.map(doc=>[doc.id,doc.revision||0]));for(const doc of workspace.documents)if(this.dirty.has(doc.id))this.snapshot(doc);this.trimHistory();this.write(workspace);for(const doc of workspace.documents){if((doc.revision||0)===versions.get(doc.id)){this.saved.set(doc.id,doc.revision||0);this.baselines.set(doc.id,doc.text);this.dirty.delete(doc.id);}}const live=new Set(workspace.documents.map(doc=>doc.id));for(const id of this.baselines.keys())if(!live.has(id)){this.baselines.delete(id);this.saved.delete(id);this.dirty.delete(id);}return this.dirty.size===0;}
  trimHistory(){const histories=this.workspace().localHistory||{},entries=Object.entries(histories).flatMap(([id,list])=>list.map(entry=>({id,entry}))).sort((a,b)=>a.entry.createdAt-b.entry.createdAt);let size=entries.reduce((sum,{entry})=>sum+entry.text.length,0);while(size>8*1024*1024&&entries.length){const {id,entry}=entries.shift();histories[id]=histories[id].filter(item=>item!==entry);size-=entry.text.length;}}
  history(doc){return this.workspace().localHistory?.[doc.id]||[];}
  checkpoint(doc){this.register(doc);const workspace=this.workspace(),history=this.history(doc);if(history.at(-1)?.text===doc.text)return;workspace.localHistory={...workspace.localHistory,[doc.id]:[...history,{text:doc.text,createdAt:this.clock(),revision:doc.revision||0}].slice(-10)};this.trimHistory();}
  restore(doc,index){const snapshot=this.history(doc)[index];if(!snapshot)throw Error('历史版本不存在。');return snapshot.text;}
  receipt(doc){return {id:doc.id,revision:doc.revision||0,savedRevision:this.saved.get(doc.id)||0,modified:this.dirty.has(doc.id)||!this.baselines.has(doc.id)};}
}
export function diffLines(before,after,limit=2000){const a=before.split('\n'),b=after.split('\n');let head=0;while(head<a.length&&head<b.length&&a[head]===b[head])head++;let tail=0;while(tail<a.length-head&&tail<b.length-head&&a[a.length-tail-1]===b[b.length-tail-1])tail++;return {from:head+1,removed:a.slice(head,a.length-tail).slice(0,limit),added:b.slice(head,b.length-tail).slice(0,limit),truncated:a.length-head-tail>limit||b.length-head-tail>limit};}
export function personalFile(path){return path==='.global.vela'||/(^|\/)(\.git|\.vela-data|\.vela-cache|\.vela-history)(\/|$)/.test(path)||/\.vela-(tmp|backup)$/.test(path)||/\.(p12|p7b|jks|keystore|cer)$/i.test(path);}
export {hash as textFingerprint};
