import {ViewPlugin,Decoration,hoverTooltip} from '@codemirror/view';
import {t} from './i18n.mjs';
export function glossaryDecorations(getProject){
  let cached,byFirst=new Map();
  const entries=()=>{const project=getProject?.()||{},terms=project.highlightTerms?project.terms||[]:[];if(cached!==terms){cached=terms;byFirst=new Map();for(const entry of terms)for(const label of [entry.term,...entry.aliases]){if(!label)continue;const list=byFirst.get(label[0])||[];list.push({label,entry});byFirst.set(label[0],list);}for(const list of byFirst.values())list.sort((a,b)=>b.label.length-a.label.length);}return byFirst;};
  const matches=(view,from,to)=>{const lookup=entries(),text=view.state.doc.sliceString(from,to),found=[];for(let i=0;i<text.length;i++){const match=lookup.get(text[i])?.find(v=>text.startsWith(v.label,i));if(match){found.push({from:from+i,to:from+i+match.label.length,...match});i+=match.label.length-1;}}return found;};
  const plugin=ViewPlugin.fromClass(class{constructor(view){this.build(view);}update(u){if(u.docChanged||u.viewportChanged||u.transactions.length)this.build(u.view);}build(view){this.decorations=Decoration.set(view.visibleRanges.flatMap(r=>matches(view,r.from,r.to)).map(m=>Decoration.mark({class:'vela-term',attributes:{title:m.entry.term+' · '+(m.entry.definition||'')}}).range(m.from,m.to)),true);}},{decorations:v=>v.decorations});
  return [plugin,hoverTooltip((view,pos)=>{const from=Math.max(0,pos-120),to=Math.min(view.state.doc.length,pos+120),m=matches(view,from,to).find(m=>m.from<=pos&&pos<m.to);if(!m)return null;return {pos:m.from,end:m.to,create(){const dom=document.createElement('div');dom.className='vela-term-tip';dom.textContent=[m.entry.term,m.entry.category,m.entry.definition,(m.entry.aliases||[]).join('、'),(m.entry.sources||[]).join(' · ')].filter(Boolean).join('\n');return {dom};}};})];
}
export function renderGlossaryPanel(root,terms,{escape:esc,onOpen,onClose}){
  const previousQuery=root.querySelector('input')?.value||'';
  root.innerHTML=`<header><strong>${t('术语库')} · ${terms.length}</strong><input type="search" aria-label="${t('搜索词条')}" placeholder="${t('搜索词条…')}"><button type="button" aria-label="${t('关闭')}">×</button></header><div class="glossary-panel-rows"></div><footer></footer>`;
  let page=0;const search=root.querySelector('input'),rows=root.querySelector('.glossary-panel-rows'),footer=root.querySelector('footer');
  search.value=previousQuery;
  const render=()=>{const query=search.value.trim().toLocaleLowerCase(),filtered=terms.filter(e=>[e.term,e.category,e.definition,...(e.aliases||[])].join(' ').toLocaleLowerCase().includes(query)),pages=Math.max(1,Math.ceil(filtered.length/40));page=Math.min(page,pages-1);rows.innerHTML=filtered.slice(page*40,page*40+40).map(e=>`<button type="button" data-source="${esc(e.source)}" title="${esc((e.sources||[]).join(' · '))}"><strong>${esc(e.term)}</strong><span>${esc(e.category)}</span><span>${esc(e.definition)}</span><small>${esc((e.aliases||[]).join('、'))} · ${esc((e.sources||[]).join(' · '))}</small></button>`).join('')||`<p>${t('暂无匹配词条')}</p>`;footer.innerHTML=`<button type="button" data-page="-1" ${page?'':'disabled'}>←</button><span>${page+1} / ${pages} · ${filtered.length}</span><button type="button" data-page="1" ${page+1<pages?'':'disabled'}>→</button>`;};
  search.oninput=search.onsearch=()=>{page=0;rows.scrollTop=0;render();};root.querySelector('header button').onclick=onClose;rows.onclick=e=>{const b=e.target.closest('[data-source]');if(b)onOpen(b.dataset.source);};footer.onclick=e=>{const b=e.target.closest('[data-page]');if(b){page+=Number(b.dataset.page);render();}};render();
}
