import {parseGlossary,glossaryText} from './glossary.mjs';
import {t} from './i18n.mjs';
import {glossaryKeywords,matchesGlossary} from './glossary-search.mjs';

export function renderGlossary({root,doc,escape:esc,onSave}){
  root.className='glossary-preview';let value;
  try{value=parseGlossary(doc.text);}catch(error){root.innerHTML=`<section class="glossary-error"><h2>${t('术语库')}</h2><p class="error">${esc(error.message)}</p><p>${t('配置无效，请切换源码修复。')}</p></section>`;return;}
  let entries=structuredClone(value.entries);
  root.innerHTML=`<form class="glossary-editor"><header><div><span class="glossary-kind">GLY</span><h2>${t('术语库')}</h2></div><label>${t('名称')}<input name="name" maxlength="160" value="${esc(value.name||doc.name)}"></label></header><div class="glossary-tools"><input type="search" id="glossary-search" placeholder="${t('搜索词条…')}" aria-label="${t('搜索词条')}"><output id="glossary-count"></output><button type="button" class="secondary" id="glossary-add">＋ ${t('添加词条')}</button></div><div id="glossary-entries"></div><footer><p id="glossary-error" class="error" role="alert"></p><button class="primary">${t('保存术语库')}</button></footer></form>`;
  const list=root.querySelector('#glossary-entries'),search=root.querySelector('#glossary-search'),form=root.querySelector('form');
  const render=()=>{const query=glossaryKeywords(search.value);list.innerHTML=entries.map((entry,index)=>({entry,index})).filter(({entry})=>matchesGlossary(entry,query)).map(({entry,index})=>`<section class="glossary-entry" data-entry="${index}"><div class="glossary-entry-top"><label>${t('词条')}<input data-field="term" maxlength="120" value="${esc(entry.term)}" required></label><button type="button" data-delete="${index}" class="text-button" aria-label="${t('删除词条')}">×</button></div><div class="glossary-entry-fields"><label>${t('分类')}<input data-field="category" maxlength="120" value="${esc(entry.category||'')}"></label><label>${t('别名')}<input data-field="aliases" value="${esc(entry.aliases.join(', '))}" placeholder="${t('多个别名用逗号分隔')}"></label></div><label>${t('释义')}<textarea data-field="definition" maxlength="4000" rows="2">${esc(entry.definition||'')}</textarea></label></section>`).join('')||`<p class="blank">${t('暂无匹配词条')}</p>`;root.querySelector('#glossary-count').textContent=entries.length+' '+t('词条');};
  list.oninput=event=>{const field=event.target.dataset.field,row=event.target.closest('[data-entry]');if(!field||!row)return;entries[Number(row.dataset.entry)][field]=field==='aliases'?event.target.value.split(/[,，]/).map(item=>item.trim()).filter(Boolean):event.target.value;};
  list.onclick=event=>{const button=event.target.closest('[data-delete]');if(button){entries.splice(Number(button.dataset.delete),1);render();}};
  search.oninput=search.onsearch=render;root.querySelector('#glossary-add').onclick=()=>{search.value='';entries.push({id:crypto.randomUUID(),term:'',definition:'',category:'',aliases:[]});render();list.lastElementChild?.querySelector('input')?.focus();};
  form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('footer button');button.disabled=true;try{await onSave(glossaryText({...value,name:form.elements.name.value,entries}));}catch(error){root.querySelector('#glossary-error').textContent=error.message;}finally{button.disabled=false;}};render();
}
