// Runs only inside the isolated native HTML view. No native editor or account bridge.
(() => {
  if(window.velaHtmlReaderReady)return;window.velaHtmlReaderReady=true;
  const settings=JSON.parse(new URL(document.currentScript.src).searchParams.get('config')||'{}'),english=settings.english,key='vela.html.reading:'+settings.path;
  let position;try{position=JSON.parse(localStorage.getItem(key)||'null');}catch{}
  const article=document.createElement('article');article.id='vela-html-document';while(document.body.firstChild)article.append(document.body.firstChild);document.body.append(article);
  document.body.style.cssText+=';margin:0!important;padding:0!important;overflow:hidden!important;height:100vh!important;max-width:none!important;';
  const viewport=document.createElement('div');viewport.style.cssText='position:fixed;inset:0 0 30px;overflow:auto;overscroll-behavior:contain;';article.before(viewport);viewport.append(article);
  article.style.cssText+=';box-sizing:border-box;width:100%;padding:24px;min-height:100%;';
  const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:2147483647;';document.body.append(host);const shadow=host.attachShadow({mode:'closed'});
  shadow.innerHTML='<style>:host{font:14px sans-serif;color:#203529}header{display:none;align-items:center;gap:12px;padding:10px 12px;background:#eff5f0;border-bottom:1px solid #d6dfd8;pointer-events:auto}button{font:13px sans-serif;padding:7px;border:0;background:none;color:inherit;cursor:pointer}strong{flex:1;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}small{max-width:35%;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}footer{position:absolute;bottom:0;left:0;right:0;height:29px;display:flex;justify-content:space-between;align-items:center;border-top:1px solid #d6dfd8;background:#eff5f0;padding:0 14px;font-size:10px;color:#77867d}aside{display:none;position:absolute;top:50px;right:0;bottom:30px;width:min(280px,80%);overflow:auto;background:#eff5f0;pointer-events:auto}aside button{display:block;width:100%;text-align:left;padding:12px;border-bottom:1px solid #d6dfd8}</style><header><button id="back"></button><strong></strong><small></small><button id="chapters">☷</button></header><aside></aside><footer><time></time><span></span></footer>';
  if(settings.dark){shadow.querySelector('style').textContent+='header,footer,aside{background:#161e1a;color:#a6b8ab;border-color:#293b30}';}
  shadow.querySelector('#back').textContent=english?'← Library':'← 书库';shadow.querySelector('#back').onclick=()=>location.href='https://wenzhou-reader.local/back';shadow.querySelector('strong').textContent=settings.path.split('/').at(-1);
  let nodeCache;const nodes=()=>{if(nodeCache)return nodeCache;const walker=document.createTreeWalker(article,NodeFilter.SHOW_TEXT),list=[];let node;while(node=walker.nextNode())if(node.parentElement&&!node.parentElement.closest('script,style'))list.push(node);return nodeCache=list;};
  function point(offset){const list=nodes();for(const node of list){if(offset<node.length)return {node,offset};offset-=node.length;}const node=list.at(-1);return node?{node,offset:Math.max(0,node.length-1)}:null;}
  function rect(offset){const p=point(offset);if(!p)return null;const range=document.createRange();range.setStart(p.node,p.offset);range.setEnd(p.node,Math.min(p.offset+1,p.node.length));return range.getBoundingClientRect();}
  let page=0,pages=1,chrome=false,restoring=false;
  const headings=[...article.querySelectorAll('h1,h2,h3,h4,h5,h6')];shadow.querySelector('aside').innerHTML='';for(const heading of headings){const button=document.createElement('button');button.textContent=heading.textContent;button.onclick=()=>{if(settings.pages){page=Math.max(0,Math.floor((heading.getBoundingClientRect().left-article.getBoundingClientRect().left)/(viewport.clientWidth+48)));paint();}else heading.scrollIntoView();shadow.querySelector('aside').style.display='none';capture();};shadow.querySelector('aside').append(button);}
  shadow.querySelector('#chapters').title=english?'Chapters':'章节目录';shadow.querySelector('#chapters').onclick=()=>{const panel=shadow.querySelector('aside');panel.style.display=panel.style.display==='block'?'none':'block';};
  function paint(){if(settings.pages)article.style.transform=`translateX(${-page*(viewport.clientWidth+48)}px)`;}
  function capture(){if(restoring)return;const text=nodes().map(node=>node.textContent).join(''),box=viewport.getBoundingClientRect();let low=0,high=text.length;while(low<high){const mid=(low+high)>>1,r=rect(mid);if(!r)break;if(settings.pages?r.right<=box.left:r.bottom<=box.top)low=mid+1;else high=mid;}
    const ratio=settings.pages?(pages<=1?1:page/(pages-1)):viewport.scrollTop/Math.max(1,viewport.scrollHeight-viewport.clientHeight);position={offset:low,context:text.slice(low,low+64),ratio};try{localStorage.setItem(key,JSON.stringify(position));}catch{}shadow.querySelector('footer span').textContent=(settings.pages?`${page+1} / ${pages}   `:'')+`${Math.round(ratio*100)}%`;
    const current=[...headings].reverse().find(heading=>settings.pages?heading.getBoundingClientRect().left<viewport.clientWidth:heading.getBoundingClientRect().top<viewport.clientHeight*.3);shadow.querySelector('small').textContent=current?.textContent||'';
  }
  function layout(){restoring=true;article.style.transform='';if(settings.pages){viewport.style.overflow='hidden';article.style.height=viewport.clientHeight+'px';article.style.columnWidth=(viewport.clientWidth-48)+'px';article.style.columnGap='96px';article.style.columnFill='auto';pages=Math.max(1,Math.ceil((article.scrollWidth+48)/(viewport.clientWidth+48)));}else article.style.height='';
    if(position){const text=nodes().map(node=>node.textContent).join('');let offset=position.offset||0;if(position.context&&text.slice(offset,offset+position.context.length)!==position.context){const found=text.indexOf(position.context);if(found>=0)offset=found;}const r=rect(offset);if(r){if(settings.pages)page=Math.floor((r.left-article.getBoundingClientRect().left)/(viewport.clientWidth+48));else viewport.scrollTop+=r.top-viewport.getBoundingClientRect().top;}}
    page=Math.max(0,Math.min(pages-1,page));paint();restoring=false;capture();
  }
  function turn(delta){if(settings.pages){page=Math.max(0,Math.min(pages-1,page+delta));paint();}else viewport.scrollBy({top:delta*viewport.clientHeight,behavior:'instant'});capture();}
  let start,moved=false,pinch=false;viewport.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};moved=false;});viewport.addEventListener('pointermove',e=>{if(start&&Math.hypot(start.x-e.clientX,start.y-e.clientY)>12)moved=true;});viewport.addEventListener('touchstart',e=>{pinch=e.touches.length>1;},{passive:true});viewport.onclick=e=>{if(moved||pinch||getSelection()?.toString()||e.target.closest('a,input,textarea,select,button'))return;const fraction=e.clientX/viewport.clientWidth;if(fraction<.3)turn(-1);else if(fraction>.7)turn(1);else{chrome=!chrome;shadow.querySelector('header').style.display=chrome?'flex':'none';if(!chrome)shadow.querySelector('aside').style.display='none';}};
  viewport.addEventListener('scroll',capture,{passive:true});window.addEventListener('resize',layout);window.addEventListener('pagehide',capture);document.addEventListener('click',e=>{if(e.target.closest('a'))e.preventDefault();});
  const sizes=new WeakMap();window.velaHtmlReaderZoom=percent=>{const elements=[article,...article.querySelectorAll('*')].filter(element=>!element.matches('script,style'));for(const element of elements)if(!sizes.has(element))sizes.set(element,parseFloat(getComputedStyle(element).fontSize));for(const element of elements)element.style.setProperty('font-size',sizes.get(element)*percent/100+'px','important');layout();};
  function clock(){shadow.querySelector('time').textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});}clock();setInterval(clock,30000);window.velaHtmlReaderZoom((settings.fontSize||16)*100/16);layout();
})();
