import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import {exportPdf} from './tex-compiler.mjs';
import {t} from './i18n.mjs';
import {mountTexComponents} from './tex-component-view.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./pdf/pdf.worker.mjs',location.href).href;
const escape=text=>String(text??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
// A separate canvas per visible page keeps large PDFs from allocating all pages at once.
export class PdfPreview {
  constructor({compiler,fail,jump,readingMode}){Object.assign(this,{compiler,fail,jump,readingMode});this.epoch=0;}
  cancelRendering(){for(const task of this.renderTasks||[])task.cancel();for(const task of this.textTasks||[])task.cancel();this.textTasks=[];this.renderTasks=[];}
  dispose(){this.epoch++;this.searchEpoch=(this.searchEpoch||0)+1;this.renderEpoch=(this.renderEpoch||0)+1;this.onPage=null;this.abort?.abort();this.cancelRendering();this.loading?.destroy();this.resize?.disconnect();}
  mount(root,doc,{reading=false,onReady}={}){
    this.dispose();this.root=root;this.doc=doc;this.reading=reading;this.onReady=onReady;this.page=1;this.zoom=1;this.compiling=false;this.pdf=null;this.renderEpoch=0;
    root.classList.add('tex-pdf');root.innerHTML=`<div class="tex-tools"><select class="tex-engine" aria-label="${t('编译引擎')}"><option value="xetex">XeLaTeX</option><option value="pdftex">pdfLaTeX</option></select><button class="primary tex-compile">${t('编译 PDF')}</button><button class="secondary tex-cancel" hidden>${t('取消')}</button><button class="secondary tex-export" disabled>${t('导出 PDF')}</button><span class="tex-status" role="status"></span></div><details class="tex-log"><summary>${t('编译日志')}</summary><div class="tex-diagnostics"></div><pre></pre></details><div class="pdf-tools"><button class="pdf-previous" disabled>←</button><span class="pdf-position"></span><button class="pdf-next" disabled>→</button></div><div class="pdf-canvas"></div>`;
    if(this.compiler?.assets&&!/\.pdf$/i.test(doc.name))mountTexComponents(root,this.compiler,this.fail);
    root.querySelector('.tex-compile').onclick=()=>this.compile().catch(this.fail);root.querySelector('.tex-cancel').onclick=()=>this.abort?.abort();root.querySelector('.tex-export').onclick=()=>exportPdf(doc.name,this.bytes).catch(this.fail);root.querySelector('.pdf-previous').onclick=()=>this.turn(-1);root.querySelector('.pdf-next').onclick=()=>this.turn(1);
    this.resize=new ResizeObserver(()=>{if(this.pdf)this.render().catch(this.fail);});this.resize.observe(root.querySelector('.pdf-canvas'));
    const config=this.compiler?.host?.project?.(doc)?.config;root.querySelector('.tex-engine').value=config?.formats?.latex?.engine||'xetex';if(reading){root.classList.add('tex-reading');if(!/\.pdf$/i.test(doc.name))this.compile().catch(this.fail);}if(/\.pdf$/i.test(doc.name)){root.querySelector('.tex-tools').hidden=true;root.querySelector('.tex-log').hidden=true;}
  }
  async openFile(bytes){if(!(bytes instanceof Uint8Array)||bytes.length>32*1024*1024||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('PDF 无效或超过 32 MB。');this.bytes=bytes;await this.load();}
  async outline(){const items=await this.pdf?.getOutline()||[],result=[];const walk=async list=>{for(const item of list){if(result.length>=1000)return;try{const dest=typeof item.dest==='string'?await this.pdf.getDestination(item.dest):item.dest;if(dest){const page=typeof dest[0]==='number'?dest[0]+1:(await this.pdf.getPageIndex(dest[0]))+1;result.push({title:item.title,pdfPage:page});}}catch{}await walk(item.items||[]);}};await walk(items);return result;}
  cancelSearch(){this.searchEpoch=(this.searchEpoch||0)+1;}
  async search(query){const epoch=this.searchEpoch=(this.searchEpoch||0)+1,results=[];for(let number=1;number<=this.pdf.numPages;number++){if(epoch!==this.searchEpoch)return [];const page=await this.pdf.getPage(number),content=await page.getTextContent(),text=content.items.map(item=>item.str||'').join(' ');if(text.toLocaleLowerCase().includes(query.toLocaleLowerCase()))results.push({pdfPage:number,quote:query});if(results.length>=200)break;if(number%5===0)await new Promise(resolve=>setTimeout(resolve,0));}return results;}
  async compile(){
    if(this.compiling)return;this.compiling=true;const epoch=this.epoch,root=this.root;this.abort=new AbortController();root.querySelector('.tex-compile').disabled=true;root.querySelector('.tex-cancel').hidden=false;root.querySelector('.tex-status').textContent=t('正在编译…');const log=root.querySelector('.tex-log pre');log.textContent='';root.querySelector('.tex-diagnostics').innerHTML='';
    try{const result=await this.compiler.compile(this.doc,{engine:root.querySelector('.tex-engine').value,signal:this.abort.signal,onLog:line=>{if(epoch===this.epoch)log.textContent=(log.textContent+'\n'+line).slice(-100000);}});if(epoch!==this.epoch)return;
      root.querySelector('.tex-diagnostics').innerHTML=result.diagnostics.map(item=>`<button class="tex-error" data-line="${Number(item.line)||0}" data-file="${escape(item.file||'')}">${escape(item.file||'')}:${Number(item.line)||0} ${escape(item.message)}</button>`).join('');root.querySelectorAll('.tex-error').forEach(button=>button.onclick=()=>{if(!this.reading)this.jump?.(button.dataset.file,Number(button.dataset.line));});
      if(!result.ok||!result.pdf){root.querySelector('.tex-log').open=true;throw new Error(t('编译失败，请查看日志与缺失宏包。'));}this.bytes=result.pdf;this.page=1;await this.load();root.querySelector('.tex-status').textContent=t('编译完成');root.querySelector('.tex-export').disabled=false;
    }catch(error){if(epoch!==this.epoch)return;root.querySelector('.tex-status').textContent=this.abort.signal.aborted?t('已取消'):t('编译失败');throw error;}finally{if(epoch===this.epoch){this.compiling=false;root.querySelector('.tex-compile').disabled=false;root.querySelector('.tex-cancel').hidden=true;}}
  }
  async load(){this.cancelRendering();await this.loading?.destroy();this.loading=pdfjs.getDocument({data:this.bytes.slice(),isEvalSupported:false,useSystemFonts:true,cMapUrl:new URL('./pdf/cmaps/',location.href).href,cMapPacked:true,standardFontDataUrl:new URL('./pdf/fonts/',location.href).href});this.pdf=await this.loading.promise;await this.render();this.onReady?.(this);}
  async render(){
    if(!this.pdf||!this.root.isConnected)return;this.cancelRendering();const epoch=++this.renderEpoch,box=this.root.querySelector('.pdf-canvas');if(!box.clientWidth||!box.clientHeight)return;
    this.columns=this.reading&&this.readingMode?.()==='double'&&box.clientWidth>=760?2:1;this.page=Math.max(1,Math.min(Math.floor((this.pdf.numPages-1)/this.columns)*this.columns+1,Math.floor((this.page-1)/this.columns)*this.columns+1));const end=Math.min(this.pdf.numPages,this.page+this.columns-1),numbers=Array.from({length:end-this.page+1},(_,index)=>this.page+index),pages=await Promise.all(numbers.map(number=>this.pdf.getPage(number)));if(epoch!==this.renderEpoch)return;
    const bases=pages.map(page=>page.getViewport({scale:1})),gap=this.columns===2?24:0,width=(box.clientWidth-gap)/this.columns,scale=Math.min(width/Math.max(...bases.map(base=>base.width)),box.clientHeight/Math.max(...bases.map(base=>base.height)))*this.zoom,density=Math.min(2,devicePixelRatio||1),group=document.createElement('div');group.className='pdf-pages';group.style.gap=gap+'px';box.replaceChildren(group);
    for(const page of this.visiblePages||[])if(!numbers.includes(page.pageNumber))page.cleanup();this.visiblePages=pages;this.textTasks=[];this.renderTasks=pages.map(page=>{const viewport=page.getViewport({scale}),wrap=document.createElement('div'),canvas=document.createElement('canvas'),layer=document.createElement('div');wrap.className='pdf-page';wrap.style.width=viewport.width+'px';wrap.style.height=viewport.height+'px';layer.className='textLayer';layer.style.setProperty('--scale-factor',String(scale));layer.style.setProperty('--total-scale-factor',String(scale));canvas.width=Math.max(1,Math.floor(viewport.width*density));canvas.height=Math.max(1,Math.floor(viewport.height*density));canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';wrap.append(canvas,layer);group.append(wrap);const text=new pdfjs.TextLayer({textContentSource:page.streamTextContent(),container:layer,viewport});this.textTasks.push(text);text.render().catch(()=>{});return page.render({canvasContext:canvas.getContext('2d'),viewport,transform:density!==1?[density,0,0,density,0,0]:undefined});});
    if(this.columns===2&&pages.length===1){const blank=document.createElement('div');blank.setAttribute('aria-hidden','true');blank.style.width=group.firstElementChild.style.width;blank.style.flexShrink='0';group.append(blank);}
    try{await Promise.all(this.renderTasks.map(task=>task.promise));}catch(error){if(error.name!=='RenderingCancelledException')throw error;return;}if(epoch!==this.renderEpoch)return;
    this.root.querySelector('.pdf-position').textContent=`${this.page}${end!==this.page?'–'+end:''} / ${this.pdf.numPages}`;this.root.querySelector('.pdf-previous').disabled=this.page===1;this.root.querySelector('.pdf-next').disabled=end===this.pdf.numPages;this.onPage?.(this.page,this.pdf.numPages,end);
  }
  turn(delta){if(!this.pdf)return;const columns=this.columns||1;this.page=Math.max(1,Math.min(Math.floor((this.pdf.numPages-1)/columns)*columns+1,this.page+delta*columns));this.render().catch(this.fail);}
}
