import {error,relativePath,within,parentPath,mime,textEditable,bytes,sha256,revision,checkAbort,positive,jsonObject} from './project-contract.mjs';
import {PluginTasks} from './plugin-tasks.mjs';
import {createVelaV2,parseVela,velaText,rewriteVelaFiles,includeNewReadingFile} from './vela.mjs';
import {newDocument} from './model.mjs';
import {documentPath} from './workspace.mjs';
import {fromBase64,toBase64} from './plugin-package.mjs';

/** Coordinates public project operations with live DocumentService state. */
export class ProjectService {
  constructor(host,backend){this.host=host;this.backend=backend;this.tasks=new PluginTasks();this.bindings=new Map();this.watchers=new Set();this.queue=Promise.resolve();this.capabilities=null;this.pendingEvents=new Map();this.observed=new Map();}
  async ready(){this.capabilities=await this.backend.call('capabilities','host',{});return this.capabilities;}
  featureNames(){const f=this.capabilities?.features||{};return [...(f.filesystem?['workspace-v1','filesystem-v1']:[]),...(f.transactions?['file-transactions-v1']:[]),...(f.assetSessions?['asset-sessions-v1']:[]),...(f.archives?['archive-v1']:[]),...(f.snapshots?['snapshots-v1']:[])];}
  state(){return this.host.workspace();}
  projects(){return this.state().documents.filter(d=>d.name==='.vela').flatMap(doc=>{try{const config=parseVela(doc.text);return config.kind==='workspace'?[{id:config.id,name:config.project?.name||parentPath(documentPath(doc)).split('/').at(-1)||'Vela',root:parentPath(documentPath(doc)),doc}]:[];}catch{return [];}});}
  project(id){const all=this.projects().filter(p=>p.id===id);if(all.length!==1)throw error(all.length?'E_INVALID_DATA':'E_NOT_FOUND',all.length?'项目 ID 重复，请修复 .vela。':'项目不存在。');return all[0];}
  alive(binding){if(binding.stopped||this.bindings.get(binding.owner)!==binding)throw error('E_PLUGIN_STOPPED','插件已停用。');}
  permission(binding,id){this.alive(binding);if(!binding.grants.has(id))throw error('E_PERMISSION','请先打开并授权此工作区。',{workspaceId:id});return this.project(id);}
  async authorize(binding,id){this.alive(binding);const p=this.project(id);if(!binding.grants.has(id)){if(!await this.host.confirm('插件项目授权',`允许“${binding.name}”读写工作区“${p.name}”及其附件？`))throw error('E_PERMISSION','项目授权已取消。');this.alive(binding);binding.grants.add(id);}return p;}
  async call(binding,action,args={}){this.alive(binding);let onStop;try{const pending=this.backend.call(action,binding.owner,{...args,pluginId:binding.id}).then(result=>{if(binding.stopped&&!['apply','receipt'].includes(action))this.backend.call('stop',binding.owner,{pluginId:binding.id}).catch(()=>{});return result;}),stop=['apply','receipt'].includes(action)?null:new Promise((_,reject)=>{onStop=()=>reject(error('E_PLUGIN_STOPPED','插件已停用。'));binding.stopController.signal.addEventListener('abort',onStop,{once:true});if(binding.stopped)onStop();});const result=await (stop?Promise.race([pending,stop]):pending);if(binding.stopped&&!['apply','receipt'].includes(action)){await this.backend.call('stop',binding.owner,{pluginId:binding.id}).catch(()=>{});this.alive(binding);}return result;}catch(cause){if(cause.code)throw cause;throw error('E_INVALID_DATA','项目操作失败，请保留原始数据并重试。');}finally{if(onStop)binding.stopController.signal.removeEventListener('abort',onStop);}}
  async entries(binding,p){
    const tree=await this.call(binding,'tree',{root:p.root}),workspace=this.state();workspace.pluginProject||={entries:{},receipts:{}};workspace.pluginProject.entries||={};
    const docs=new Map(workspace.documents.filter(d=>within(p.root,documentPath(d))).map(d=>[documentPath(d).slice(p.root?p.root.length+1:0),d]));
    const entries=[];for(const raw of tree.entries){const path=relativePath(raw.path),full=(p.root?p.root+'/':'')+path,doc=docs.get(path);const entryId=workspace.pluginProject.entries[full]||doc?.id||crypto.randomUUID();workspace.pluginProject.entries[full]=entryId;
      entries.push({...raw,path,workspaceId:p.id,entryId,textEditable:raw.kind==='file'&&(!!doc||workspace.pluginProject?.textFiles?.[full]||textEditable(path)),revision:doc?await revision(doc.text):raw.revision,diskRevision:raw.revision,size:doc?bytes(doc.text).length:raw.size,mime:raw.mime||mime(path),modifiedAt:doc?new Date(doc.updatedAt).toISOString():raw.modifiedAt});docs.delete(path);
    }
    // New unsaved editor files participate in the same revision as on-disk files.
    for(const [path,doc] of docs){const full=(p.root?p.root+'/':'')+path,entryId=workspace.pluginProject.entries[full]||doc.id;workspace.pluginProject.entries[full]=entryId;entries.push({path,workspaceId:p.id,entryId,kind:'file',size:bytes(doc.text).length,mime:mime(path),revision:await revision(doc.text),diskRevision:null,textEditable:true,modifiedAt:new Date(doc.updatedAt).toISOString()});}
    for(const e of entries.filter(e=>e.kind==='directory').sort((a,b)=>b.path.length-a.path.length))e.revision=await revision(JSON.stringify(entries.filter(child=>child!==e&&within(e.path,child.path)).sort((a,b)=>a.path.localeCompare(b.path)).map(child=>[child.path,child.revision])));
    entries.sort((a,b)=>a.path.localeCompare(b.path));const rev='w:'+await sha256(JSON.stringify(entries.map(e=>[e.path,e.entryId,e.revision])));return {entries,revision:rev};
  }
  publicEntry(entry){const {diskRevision,...value}=entry;return value;}
  async handle(binding,p){const tree=await this.entries(binding,p);return {id:p.id,name:p.name,revision:tree.revision,writable:true};}
  async readText(binding,ref,options={}){checkAbort(options.signal);const p=this.permission(binding,ref.workspaceId),path=relativePath(ref.path),tree=await this.entries(binding,p),entry=tree.entries.find(e=>e.path===path);if(!entry)throw error('E_NOT_FOUND','文件不存在。',{path});if(entry.kind!=='file'||!entry.textEditable)throw error('E_INVALID_DATA','此文件不可作为文本读取。',{path});if(entry.size>this.capabilities.limits.textBytes)throw error('E_LIMIT','文本超过读取限制。',{limit:this.capabilities.limits.textBytes});const full=(p.root?p.root+'/':'')+path,doc=this.state().documents.find(d=>documentPath(d)===full);if(doc)return {text:doc.text,revision:entry.revision,encoding:'utf-8'};
    const chunks=[];let offset=0;while(offset<entry.size){checkAbort(options.signal);const part=await this.call(binding,'read',{root:p.root,path,offset,length:Math.min(this.capabilities.limits.readChunkBytes,entry.size-offset),expectedRevision:entry.diskRevision});const data=fromBase64(part.data);if(!data.length)throw error('E_CONFLICT','文件读取期间已改变。');chunks.push(data);offset+=data.length;}
    const data=new Uint8Array(entry.size);let at=0;for(const chunk of chunks){data.set(chunk,at);at+=chunk.length;}let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(data);}catch{throw error('E_INVALID_DATA','文件不是有效的 UTF-8 文本。',{path});}return {text,revision:entry.revision,encoding:'utf-8'};
  }
  async readBytes(binding,ref,options={}){checkAbort(options.signal);const p=this.permission(binding,ref.workspaceId),path=relativePath(ref.path),doc=this.state().documents.find(d=>documentPath(d)===(p.root?p.root+'/':'')+path);if(doc){const data=bytes(doc.text),rev=await revision(data),offset=ref.offset??0,length=ref.length??Math.min(data.length-offset,this.capabilities.limits.readChunkBytes);positive(offset,'读取偏移',data.length,{zero:true});positive(length,'块大小',this.capabilities.limits.readChunkBytes,{zero:true});if(ref.expectedRevision&&ref.expectedRevision!==rev)throw error('E_CONFLICT','文件已改变。',{path});return {bytes:data.slice(offset,offset+length),revision:rev,totalSize:data.length};}const result=await this.call(binding,'read',{root:p.root,path,offset:ref.offset,length:ref.length,expectedRevision:ref.expectedRevision});return {...result,bytes:fromBase64(result.data),data:undefined};}
  exclusive(binding,run){const task=this.queue.then(async()=>{this.alive(binding);const release=await this.host.lock();try{if(this.recoveryBlocked)throw error('E_RECOVERY_REQUIRED','项目提交结果需要恢复，请重启应用。');return await run();}finally{if(!this.recoveryBlocked)release();}});binding.operations.add(task);task.finally(()=>binding.operations.delete(task)).catch(()=>{});this.queue=task.catch(()=>{});return task;}
  async batch(binding,args,options={},taskContext){
    return this.exclusive(binding,async()=>{
      checkAbort(options.signal);const p=this.permission(binding,args.workspaceId);if(!this.capabilities.features.transactions)throw error('E_UNSUPPORTED','当前环境不支持项目事务。');
      if(typeof args.idempotencyKey!=='string'||!args.idempotencyKey||args.idempotencyKey.length>160)throw error('E_INVALID_DATA','需要有效的幂等键。');
      const before=this.state(),candidate=structuredClone(before),receipts=candidate.pluginProject?.receipts||{},key=binding.id+':'+p.id+':'+args.idempotencyKey,signature=await sha256(JSON.stringify(args)),previous=receipts[key];
      if(previous){if(previous.signature!==signature)throw error('E_INVALID_DATA','同一幂等键不可用于不同内容。');return structuredClone(previous.result);}
      const tree=await this.entries(binding,p);candidate.pluginProject||={entries:{},receipts:{}};candidate.pluginProject.entries={...before.pluginProject.entries};candidate.pluginProject.textFiles={...before.pluginProject.textFiles};if(tree.revision!==args.expectedWorkspaceRevision)throw error('E_CONFLICT','工作区已改变，请重新读取。',{workspaceId:p.id},true);
      const changes=args.changes;if(!Array.isArray(changes)||!changes.length||changes.length>this.capabilities.limits.projectEntries)throw error('E_LIMIT','批量变更数量无效。');
      const original=new Map(tree.entries.map(e=>[e.path,e])),working=new Map(original),affected=[],expected=new Map(),wire=[];const removed=[],changedIds=new Set();
      const full=path=>(p.root?p.root+'/':'')+path;
      const check=(path,expectedRevision,creating=false)=>{const entry=original.get(path);if(expectedRevision===null){if(entry)throw error('E_EXISTS','创建目标已存在。',{path});}else if(!entry||entry.revision!==expectedRevision)throw error('E_CONFLICT','文件修订不匹配。',{path},true);if(creating&&[...working.keys()].some(key=>key.toLowerCase()===path.toLowerCase()))throw error('E_EXISTS','创建目标已存在。',{path});expected.set(path,entry?.diskRevision??null);return entry;};
      const parents=path=>{let parent=parentPath(path);while(parent){const conflict=[...working.keys()].find(key=>key.toLowerCase()===parent.toLowerCase()&&key!==parent);if(conflict)throw error('E_EXISTS','父路径大小写冲突。',{path:parent});const e=working.get(parent);if(e&&e.kind!=='directory')throw error('E_EXISTS','父路径是文件。',{path:parent});if(!e){working.set(parent,{path:parent,entryId:crypto.randomUUID(),kind:'directory',revision:'pending',mime:'inode/directory',size:0,modifiedAt:new Date().toISOString(),workspaceId:p.id});candidate.folders=[...new Set([...(candidate.folders||[]),full(parent)])];wire.push({kind:'mkdir',path:parent});expected.set(parent,null);}parent=parentPath(parent);}};
      for(const c of changes){checkAbort(options.signal);if(!c||!['mkdir','writeText','writeBlob','move','delete'].includes(c.kind))throw error('E_INVALID_DATA','变更类型无效。');const path=relativePath(c.path||c.from);if(affected.some(other=>within(other,path)||within(path,other)))throw error('E_INVALID_DATA','首版不支持交叠或循环变更，请拆成独立事务。',{path});affected.push(path);parents(path);
        if(c.kind==='mkdir'){check(path,null,true);const entry={path,entryId:crypto.randomUUID(),kind:'directory',mime:'inode/directory',size:0,revision:'pending',modifiedAt:new Date().toISOString(),workspaceId:p.id};working.set(path,entry);candidate.folders=[...new Set([...(candidate.folders||[]),full(path)])];wire.push({kind:'mkdir',path});changedIds.add(entry.entryId);}
        if(['writeText','writeBlob'].includes(c.kind)){const old=check(path,c.expectedRevision,c.expectedRevision===null);if(old?.kind==='directory')throw error('E_INVALID_DATA','不能用文件覆盖目录。',{path});let size,rev;
          if(c.kind==='writeText'){if(typeof c.text!=='string')throw error('E_INVALID_DATA','正文必须是字符串。');size=bytes(c.text).length;if(size>this.capabilities.limits.textBytes)throw error('E_LIMIT','文本超过限制。');rev=await revision(c.text);}else{const staged=binding.blobs.get(c.blobId);if(!staged?.finished||staged.workspaceId!==p.id)throw error('E_INVALID_DATA','素材尚未完成或不属于当前项目。');size=staged.size;rev='r:'+staged.sha256;}
          const entry={...old,path,workspaceId:p.id,entryId:old?.entryId||crypto.randomUUID(),kind:'file',mime:mime(path),size,revision:rev,textEditable:c.kind==='writeText'||textEditable(path),modifiedAt:new Date().toISOString()};working.set(path,entry);if(c.kind==='writeText')candidate.pluginProject.textFiles[full(path)]=true;else delete candidate.pluginProject.textFiles[full(path)];wire.push({kind:c.kind,path,...(c.kind==='writeText'?{text:c.text}:{blobId:c.blobId})});changedIds.add(entry.entryId);
          const doc=candidate.documents.find(d=>documentPath(d)===full(path));if(doc&&c.kind==='writeBlob')throw error('E_INVALID_DATA','已打开的文本请使用 writeText。',{path});if(doc){doc.text=c.text;doc.revision=(doc.revision||0)+1;doc.updatedAt=Date.now();}else if(c.kind==='writeText'&&(path.endsWith('/.vela')||path==='.vela'||c.addToReadingList||options.restoreMetadata&&JSON.parse(options.restoreMetadata.workspace||'{}').documents?.some(d=>documentPath(d)===full(path)))){const created=newDocument(path.split('/').at(-1),c.text);created.path=full(path);created.id=entry.entryId;candidate.documents.push(created);}
          if(c.addToReadingList){const doc=candidate.documents.find(d=>documentPath(d)===full(path));if(doc)includeNewReadingFile(candidate,doc);}
        }
        if(c.kind==='move'){const old=check(path,c.expectedRevision),to=relativePath(c.to);if(within(path.toLowerCase(),to.toLowerCase())||[...working.keys()].some(other=>other.toLowerCase()===to.toLowerCase()&&other!==path))throw error('E_EXISTS','移动目标已存在或在自身目录内。',{path:to});if(affected.slice(0,-1).some(other=>within(other,to)||within(to,other)))throw error('E_INVALID_DATA','移动目标与其它操作交叠。');affected.push(to);parents(to);expected.set(to,null);
          for(const [key,e] of [...working])if(within(path,key)){working.delete(key);const next=to+key.slice(path.length);working.set(next,{...e,path:next});changedIds.add(e.entryId);delete candidate.pluginProject.entries[full(key)];candidate.pluginProject.entries[full(next)]=e.entryId;if(candidate.pluginProject.textFiles[full(key)]){delete candidate.pluginProject.textFiles[full(key)];candidate.pluginProject.textFiles[full(next)]=true;}}
          for(const doc of candidate.documents)if(within(full(path),documentPath(doc))){doc.path=full(to)+documentPath(doc).slice(full(path).length);doc.name=doc.path.split('/').at(-1);}
          candidate.folders=(candidate.folders||[]).map(value=>within(full(path),value)?full(to)+value.slice(full(path).length):value);for(const repo of candidate.repositories||[])if(within(full(path),repo.folder))repo.folder=full(to)+repo.folder.slice(full(path).length);rewriteVelaFiles(before,candidate,'move',full(path),full(to));wire.push({kind:'move',from:path,to});
        }
        if(c.kind==='delete'){const old=check(path,c.expectedRevision);if(c.mode!=='trash')throw error('E_INVALID_DATA','删除必须移入回收站。');if(old.kind==='directory'&&[...working.keys()].some(key=>key!==path&&within(path,key))&&!c.recursive)throw error('E_INVALID_DATA','非空目录需要 recursive:true。');
          for(const [key,e] of [...working])if(within(path,key)){working.delete(key);removed.push({entryId:e.entryId,path:key});delete candidate.pluginProject.entries[full(key)];delete candidate.pluginProject.textFiles[full(key)];}candidate.documents=candidate.documents.filter(d=>!within(full(path),documentPath(d)));candidate.folders=(candidate.folders||[]).filter(f=>!within(full(path),f));candidate.repositories=(candidate.repositories||[]).filter(repo=>!within(full(path),repo.folder));rewriteVelaFiles(before,candidate,'delete',full(path));let trashId;if(this.host.platform==='browser'){trashId=crypto.randomUUID();candidate.trash||=[];if(candidate.trash.length>=100)throw error('E_QUOTA','回收站已满。');candidate.trash.push({id:trashId,path:full(path),createdAt:Date.now(),directory:old.kind==='directory',documents:before.documents.filter(d=>within(full(path),documentPath(d))),folders:(before.folders||[]).filter(f=>within(full(path),f)),entries:(before.entries||[]).filter(e=>within(full(path),e.path)),repositories:(before.repositories||[]).filter(r=>within(full(path),r.folder)),projectPayload:true});}wire.push({kind:'delete',path,trashId});
        }
      }
      if(working.size>this.capabilities.limits.projectEntries)throw error('E_LIMIT','项目超过条目限制。');if([...working.values()].reduce((sum,e)=>sum+e.size,0)>this.capabilities.limits.projectBytes)throw error('E_LIMIT','项目超过容量限制。');
      // Manifest reference rewrites and explicit reading-list additions share this commit.
      for(const doc of candidate.documents.filter(d=>d.name==='.vela'||d.name==='.global.vela')){const old=before.documents.find(d=>d.id===doc.id);if(old&&old.text!==doc.text&&!wire.some(c=>c.kind==='writeText'&&full(c.path)===documentPath(doc))){const path=documentPath(doc).slice(p.root?p.root.length+1:0);if(!within(p.root,documentPath(doc)))throw error('E_INVALID_DATA','此变更会修改项目之外的配置，请先调整引用。');wire.push({kind:'writeText',path,text:doc.text});expected.set(path,original.get(path)?.diskRevision??null);const entry=working.get(path);if(entry){entry.revision=await revision(doc.text);entry.size=bytes(doc.text).length;changedIds.add(entry.entryId);}}else if(old&&old.text!==doc.text){const c=wire.find(c=>c.kind==='writeText'&&full(c.path)===documentPath(doc));if(c)c.text=doc.text;}}
      for(const e of working.values())candidate.pluginProject.entries[full(e.path)]=e.entryId;
      for(const e of [...working.values()].filter(e=>e.kind==='directory').sort((a,b)=>b.path.length-a.path.length))e.revision=await revision(JSON.stringify([...working.values()].filter(child=>child!==e&&within(e.path,child.path)).sort((a,b)=>a.path.localeCompare(b.path)).map(child=>[child.path,child.revision])));
      if(options.restoreMetadata){const saved=options.restoreMetadata,stored=JSON.parse(saved.workspace||'{}');for(const e of working.values()){const original=saved.entries.find(old=>old.path===e.path);if(original?.entryId){if(changedIds.has(e.entryId)){changedIds.delete(e.entryId);changedIds.add(original.entryId);}if(original.textEditable||stored.pluginProject?.textFiles?.[full(e.path)])candidate.pluginProject.textFiles[full(e.path)]=true;e.entryId=original.entryId;candidate.pluginProject.entries[full(e.path)]=original.entryId;}}for(const old of stored.documents||[])if(within(p.root,documentPath(old))&&saved.includeRoots.some(root=>within(root,documentPath(old).slice(p.root?p.root.length+1:0)))){const doc=candidate.documents.find(d=>documentPath(d)===documentPath(old));if(doc){const liveText=doc.text;Object.assign(doc,structuredClone(old),{text:liveText});}}for(const field of ['annotations','editorPositions','localHistory'])if(stored[field]){candidate[field]||={};for(const old of stored.documents||[])if(within(p.root,documentPath(old))&&candidate.documents.some(d=>d.id===old.id)&&stored[field][old.id])candidate[field][old.id]=structuredClone(stored[field][old.id]);}}
      const sorted=[...working.values()].sort((a,b)=>a.path.localeCompare(b.path)),workspaceRevision='w:'+await sha256(JSON.stringify(sorted.map(e=>[e.path,e.entryId,e.revision]))),transactionId=crypto.randomUUID(),result={transactionId,workspaceRevision,changed:sorted.filter(e=>changedIds.has(e.entryId)).map(e=>this.publicEntry(e)),removed};
      candidate.pluginProject.receipts={...receipts,[key]:{signature,result}};const keys=Object.keys(candidate.pluginProject.receipts);for(const k of keys.slice(0,Math.max(0,keys.length-1000)))delete candidate.pluginProject.receipts[k];candidate.pluginProject.transactions=[...(candidate.pluginProject.transactions||[]),{id:transactionId,label:String(args.label||'插件事务').slice(0,200),createdAt:Date.now(),paths:result.changed.map(e=>e.path),removed}].slice(-100);candidate.treeRevision=(candidate.treeRevision||0)+1;
      candidate.entries=[...(candidate.entries||[]).filter(e=>!within(p.root,e.path)),...sorted.map(e=>({path:full(e.path),name:e.path.split('/').at(-1),directory:e.kind==='directory',editable:e.textEditable,size:e.size,modifiedAt:e.modifiedAt,reason:e.kind==='file'&&e.textEditable?'按需读取项目文件':''}))];candidate.openIds=candidate.openIds.filter(id=>candidate.documents.some(d=>d.id===id));if(!candidate.documents.some(d=>d.id===candidate.activeId))candidate.activeId=null;this.host.prepare?.(candidate);if(options.restoreMetadata){const saved=JSON.parse(options.restoreMetadata.workspace||'{}');for(const field of ['annotations','editorPositions'])for(const doc of candidate.documents)if(within(p.root,documentPath(doc))&&saved[field]?.[doc.id]){candidate[field]||={};candidate[field][doc.id]=structuredClone(saved[field][doc.id]);}}
      checkAbort(options.signal);this.alive(binding);taskContext?.commit();
      try{await this.call(binding,'apply',{root:p.root,expected:[...expected].map(([path,revision])=>({path,revision})),changes:wire,workspace:JSON.stringify(candidate),removedDocuments:before.documents.filter(d=>!candidate.documents.some(c=>c.id===d.id))});}catch(cause){let recovered;try{const raw=await this.backend.call('receipt',binding.owner,{});recovered=raw?JSON.parse(raw):null;}catch{this.recoveryBlocked=true;throw error('E_RECOVERY_REQUIRED','无法确认项目提交结果，写入已暂停；请重启应用恢复。',{},true);}const receipt=recovered?.pluginProject?.receipts?.[key];if(!receipt||receipt.signature!==signature||receipt.result.transactionId!==transactionId)throw cause;}

      this.host.adopt(candidate,{transactionId,changed:result.changed,removed,root:p.root});
      this.observed.set(p.id,{entries:sorted,revision:workspaceRevision});this.emit(p.id,{revision:workspaceRevision,transactionId,origin:options.origin||'plugin',originPluginId:binding.id,changes:[...result.changed.map(e=>({kind:original.has(e.path)?'change':original.size&&[...original.values()].some(old=>old.entryId===e.entryId)?'move':'create',entryId:e.entryId,path:e.path,oldPath:[...original.values()].find(old=>old.entryId===e.entryId&&old.path!==e.path)?.path,revision:e.revision})),...removed.map(e=>({...e,kind:'delete'}))]});return result;
    });
  }
  emit(id,event){for(const w of this.watchers)if(w.workspaceId===id&&!w.binding.stopped&&(!w.paths.length||event.changes.some(c=>w.paths.some(p=>within(p,c.path)||c.oldPath&&within(p,c.oldPath)))))try{w.listener(structuredClone(event));}catch(cause){this.host.fail(cause);}}
  changed(origin='editor',paths=[]){for(const p of this.projects()){if(paths.length&&!paths.some(path=>within(p.root,path)))continue;const previous=this.pendingEvents.get(p.id);this.pendingEvents.set(p.id,{origin:origin==='editor'&&previous?.origin!=='editor'?previous?.origin||origin:origin,paths});}if(this.eventTimer)return;this.eventTimer=setTimeout(async()=>{this.eventTimer=null;const events=[...this.pendingEvents];this.pendingEvents.clear();for(const [id,{origin}] of events){const watcher=[...this.watchers].find(w=>w.workspaceId===id&&!w.binding.stopped);if(!watcher)continue;try{await watcher.ready;const p=this.permission(watcher.binding,id),tree=await this.entries(watcher.binding,p),before=this.observed.get(id);this.observed.set(id,tree);if(!before||tree.revision===before.revision)continue;const old=new Map(before.entries.map(e=>[e.entryId,e])),live=new Map(tree.entries.map(e=>[e.entryId,e])),changes=[];for(const e of tree.entries){const previous=old.get(e.entryId);if(!previous||previous.path!==e.path||previous.revision!==e.revision)changes.push({kind:!previous?'create':previous.path!==e.path?'move':'change',entryId:e.entryId,path:e.path,oldPath:previous?.path!==e.path?previous?.path:undefined,revision:e.revision});}for(const e of before.entries)if(!live.has(e.entryId))changes.push({kind:'delete',entryId:e.entryId,path:e.path});if(changes.length)this.emit(id,{revision:tree.revision,origin,changes});}catch(cause){if(!watcher.binding.stopped)this.host.fail(cause);}}},50);}
  task(binding,run,options={}){this.alive(binding);return this.tasks.start(binding.owner,async ctx=>{const cancel=()=>this.backend.call('cancel',binding.owner,{taskId:ctx.id}).catch(()=>{});ctx.signal.addEventListener('abort',cancel,{once:true});try{return await run(ctx);}finally{ctx.signal.removeEventListener('abort',cancel);for(const [blobId,staged] of binding.blobs)if(staged.taskId===ctx.id){await this.backend.call('abort',binding.owner,{blobId}).catch(()=>{});binding.blobs.delete(blobId);}}},options);}
  extendIO(api,binding,fs){api.io={
    pickFiles:async args=>{this.alive(binding);if(!this.host.userGesture())throw error('E_PERMISSION','请从按钮或命令的用户操作中选择素材。');if(!Array.isArray(args.accept)||args.accept.some(type=>typeof type!=='string'||type.length>120))throw error('E_INVALID_DATA','文件过滤条件无效。');return this.call(binding,'pick',{multiple:!!args.multiple,accept:args.accept});},
    importFiles:(args,options={})=>this.task(binding,async ctx=>{const p=this.permission(binding,args.workspaceId);if(!Array.isArray(args.selections)||!args.selections.length||!['error','rename'].includes(args.collision))throw error('E_INVALID_DATA','导入参数无效。');const tree=await this.entries(binding,p);if(tree.revision!==args.expectedWorkspaceRevision)throw error('E_CONFLICT','工作区已改变。');const used=new Set(tree.entries.map(e=>e.path.toLowerCase())),changes=[];let i=0;
      for(const s of args.selections){ctx.check();let target=relativePath(s.targetPath);if(used.has(target.toLowerCase())){if(args.collision==='error')throw error('E_EXISTS','导入目标已存在。',{path:target});const dot=target.lastIndexOf('.'),suffix=dot>target.lastIndexOf('/')?target.slice(dot):'',stem=suffix?target.slice(0,dot):target;let n=2;while(used.has((stem+'-'+n+suffix).toLowerCase()))n++;target=stem+'-'+n+suffix;}used.add(target.toLowerCase());const staged=await this.call(binding,'selectionStage',{token:s.token,root:p.root,taskId:ctx.id});binding.blobs.set(staged.blobId,{...staged,workspaceId:p.id,finished:true,taskId:ctx.id});changes.push({kind:'writeBlob',path:target,blobId:staged.blobId,expectedRevision:null});ctx.progress({phase:'importing',completedFiles:++i,totalFiles:args.selections.length});}
      const result=await this.batch(binding,{workspaceId:p.id,expectedWorkspaceRevision:args.expectedWorkspaceRevision,idempotencyKey:ctx.id,changes,label:'导入素材'},{signal:ctx.signal,origin:'import'},ctx);return {transactionId:result.transactionId,entries:result.changed};},options),
    inspectArchive:(args,options={})=>this.task(binding,async ctx=>{ctx.progress({phase:'inspecting'});const result=await this.call(binding,'archiveInspect',{selectionToken:args.selectionToken,taskId:ctx.id});return {...result,totalBytes:result.totalBytes??result.expandedBytes};},options),
    readArchiveText:async args=>{this.alive(binding);const result=await this.call(binding,'archiveRead',{archiveToken:args.archiveToken,path:relativePath(args.path),maxBytes:this.capabilities.limits.textBytes});return {text:new TextDecoder('utf-8',{fatal:true}).decode(fromBase64(result.data))};},
    importArchive:(args,options={})=>this.task(binding,async ctx=>{const p=this.permission(binding,args.workspaceId),target=relativePath(args.targetDirectory??'',true);if(args.collision!=='error')throw error('E_INVALID_DATA','归档导入必须采用 collision:error。');const staged=await this.call(binding,'archiveStage',{archiveToken:args.archiveToken,root:p.root,target,taskId:ctx.id}),changes=[];
      for(const e of staged.entries)if(!e.directory)binding.blobs.set(e.blobId,{...e,workspaceId:p.id,finished:true,taskId:ctx.id});for(const e of staged.entries){const path=(target?target+'/':'')+e.path;if(e.directory){if(!staged.entries.some(other=>other.path!==e.path&&within(e.path,other.path)))changes.push({kind:'mkdir',path});}else{if(e.path==='.vela'||e.path.endsWith('/.vela')){const content=await api.io.readArchiveText({archiveToken:args.archiveToken,path:e.path});parseVela(content.text);changes.push({kind:'writeText',path,text:content.text,expectedRevision:null});}else changes.push({kind:'writeBlob',path,blobId:e.blobId,expectedRevision:null});}}ctx.check();const result=await this.batch(binding,{workspaceId:p.id,expectedWorkspaceRevision:args.expectedWorkspaceRevision,idempotencyKey:ctx.id,changes,label:'导入项目包'},{signal:ctx.signal,origin:'import'},ctx);return {transactionId:result.transactionId,revision:result.workspaceRevision};},options),
    exportFile:(args,options={})=>this.task(binding,async ctx=>{const p=this.permission(binding,args.workspaceId),path=relativePath(args.path),read=await this.entries(binding,p),entry=read.entries.find(e=>e.path===path);if(!entry||entry.revision!==args.expectedRevision)throw error('E_CONFLICT','导出文件已改变。');if(!this.host.userGesture())throw error('E_PERMISSION','请从用户操作中导出文件。');return this.exclusive(binding,async()=>{ctx.check();ctx.commit();return this.call(binding,'exportFile',{root:p.root,path,expectedRevision:entry.revision,suggestedName:args.suggestedName,taskId:ctx.id});});},options),
    exportArchive:(args,options={})=>this.task(binding,async ctx=>{this.alive(binding);if(!this.host.userGesture())throw error('E_PERMISSION','请从用户操作中导出归档。');if(!Array.isArray(args.paths)||!args.paths.length)throw error('E_INVALID_DATA','导出必须明确指定文件白名单。');ctx.progress({phase:'exporting'});const result=await this.call(binding,'archiveExport',{...args,paths:args.paths.map(path=>relativePath(path)),root:relativePath(args.root??'',true),taskId:ctx.id});try{ctx.check();ctx.commit();return await this.call(binding,'deliver',{outputToken:result.outputToken,suggestedName:args.suggestedName,sha256:result.sha256,taskId:ctx.id});}finally{await this.backend.call('discardOutput',binding.owner,{outputToken:result.outputToken}).catch(()=>{});}},options)
  };}
  extendSnapshots(api,binding){api.snapshots={
    create:(args,options={})=>this.task(binding,async ctx=>this.exclusive(binding,async()=>{const p=this.permission(binding,args.workspaceId),tree=await this.entries(binding,p);if(tree.revision!==args.expectedWorkspaceRevision)throw error('E_CONFLICT','工作区已改变。');const roots=(args.includeRoots||[]).map(path=>relativePath(path,true));if(!roots.length)throw error('E_INVALID_DATA','快照范围不能为空。');ctx.progress({phase:'snapshot'});const result=await this.call(binding,'snapshotCreate',{root:p.root,workspaceId:p.id,label:args.label,includeRoots:roots,workspace:JSON.stringify(this.state()),entries:tree.entries.map(e=>this.publicEntry(e)),taskId:ctx.id});return {...result,revision:tree.revision};}),options),
    list:args=>{const p=this.permission(binding,args.workspaceId);return this.call(binding,'snapshotList',{workspaceId:p.id});},
    restore:(args,options={})=>this.task(binding,async ctx=>{const p=this.permission(binding,args.workspaceId),tree=await this.entries(binding,p);if(tree.revision!==args.expectedWorkspaceRevision)throw error('E_CONFLICT','工作区已改变。');const record=await this.call(binding,'snapshotEntries',{snapshotId:args.snapshotId,workspaceId:p.id});if(!await this.host.confirm('恢复项目快照',`恢复“${record.label}”？会先保存当前项目的安全快照。`))throw error('E_CANCELLED','恢复已取消。');const safety=api.snapshots.create({workspaceId:p.id,expectedWorkspaceRevision:tree.revision,label:'恢复前安全快照',includeRoots:['']},{signal:ctx.signal});const safetyResult=await safety.result;ctx.check();const staged=await this.call(binding,'snapshotStage',{snapshotId:args.snapshotId,workspaceId:p.id,root:p.root,taskId:ctx.id}),changes=[],saved=new Map(record.entries.map(e=>[e.path,e])),extras=tree.entries.filter(e=>record.includeRoots.some(root=>within(root,e.path))&&!saved.has(e.path));
      for(const e of staged.entries)if(e.blobId)binding.blobs.set(e.blobId,{...e,workspaceId:p.id,finished:true,taskId:ctx.id});
      for(const e of extras.filter(e=>!extras.some(parent=>parent!==e&&within(parent.path,e.path))))changes.push({kind:'delete',path:e.path,expectedRevision:e.revision,recursive:true,mode:'trash'});
      for(const e of staged.entries){const current=tree.entries.find(old=>old.path===e.path);if(e.kind==='directory'){if(!current&&!staged.entries.some(other=>other!==e&&within(e.path,other.path)))changes.push({kind:'mkdir',path:e.path});continue;}if(current?.revision===e.revision&&current?.entryId===e.entryId)continue;const full=(p.root?p.root+'/':'')+e.path,doc=this.state().documents.find(d=>documentPath(d)===full);if(doc||JSON.parse(record.workspace||'{}').documents?.some(d=>documentPath(d)===full)||e.path==='.vela'||e.path.endsWith('/.vela')){const parts=[];let offset=0;while(offset<e.size){ctx.check();const part=await this.call(binding,'read',{snapshotId:args.snapshotId,path:e.path,offset,length:Math.min(this.capabilities.limits.readChunkBytes,e.size-offset),expectedRevision:e.revision});const data=fromBase64(part.data);parts.push(data);offset+=data.length;}const data=new Uint8Array(e.size);let at=0;for(const part of parts){data.set(part,at);at+=part.length;}changes.push({kind:'writeText',path:e.path,text:new TextDecoder('utf-8',{fatal:true}).decode(data),expectedRevision:current?.revision??null});}else{binding.blobs.set(e.blobId,{...e,workspaceId:p.id,finished:true,taskId:ctx.id});changes.push({kind:'writeBlob',path:e.path,blobId:e.blobId,expectedRevision:current?.revision??null});}}
      if(!changes.length)return {revision:tree.revision,safetySnapshotId:safetyResult.snapshotId};const result=await this.batch(binding,{workspaceId:p.id,expectedWorkspaceRevision:tree.revision,idempotencyKey:ctx.id,changes,label:'恢复项目快照'},{signal:ctx.signal,origin:'restore',restoreMetadata:record},ctx);return {revision:result.workspaceRevision,safetySnapshotId:safetyResult.snapshotId};},options)
  };}
  extendAssets(api,binding){const urls=new Map(),sessions=new Map();binding.resources.add(()=>{for(const url of urls.values())URL.revokeObjectURL(url);});api.assets={
    openSession:async args=>{const p=this.permission(binding,args.workspaceId);if(!['editor','preview'].includes(args.purpose)||!Array.isArray(args.allowedRoots)||!args.allowedRoots.length)throw error('E_INVALID_DATA','资源会话范围无效。');const allowedRoots=args.allowedRoots.map(path=>relativePath(path,true));if(args.purpose==='preview'&&!args.snapshotId)throw error('E_INVALID_DATA','试演资源必须绑定快照。');const result=await this.call(binding,'assetOpen',{root:p.root,workspaceId:p.id,snapshotId:args.snapshotId,allowedRoots,purpose:args.purpose});sessions.set(result.sessionId,{workspaceId:p.id,...args});return result;},
    resolve:async args=>{this.alive(binding);const s=sessions.get(args.sessionId);if(!s)throw error('E_NOT_FOUND','资源会话不存在。');const path=relativePath(args.path);if(!s.allowedRoots.some(root=>within(root,path)))throw error('E_PERMISSION','资源不在授权范围内。');const result=await this.call(binding,'assetResolve',{sessionId:args.sessionId,path,expectedRevision:args.expectedRevision});if(result.url)return result;
      const key=args.sessionId+':'+path;if(urls.has(key))URL.revokeObjectURL(urls.get(key));const blob=result.blob||new Blob([fromBase64(result.data)],{type:result.mime}),url=URL.createObjectURL(blob);urls.set(key,url);return {...result,url,data:undefined,blob:undefined,supportsRange:false};},
    release:async args=>{this.alive(binding);await this.call(binding,'assetRelease',args);sessions.delete(args.sessionId);for(const [key,url] of urls)if(key.startsWith(args.sessionId+':')){URL.revokeObjectURL(url);urls.delete(key);}}
  };}
  extendPreview(api,binding){const previews=new Map();binding.resources.add(()=>{for(const record of previews.values()){clearInterval(record.timer);record.listeners.clear();}});api.preview={
    open:async args=>{this.alive(binding);if(!this.capabilities.features.independentPreview)throw error('E_UNSUPPORTED','此平台支持插件页内试演，请在插件页面中运行。');if(args.network!=='none')throw error('E_INVALID_DATA','独立试演不允许网络访问。');const asset=relativePath(args.runtime?.pluginAsset),runtime=this.host.pluginAsset(binding.id,asset);if(!runtime||!(/\.(html?|js)$/i.test(asset)))throw error('E_INVALID_DATA','试演入口必须来自当前插件包。');const result=await this.call(binding,'previewOpen',{...args,runtime:{path:asset,data:runtime,files:this.host.pluginAssets?.(binding.id)||{}},initialState:jsonObject(args.initialState||{},65536),contentRoot:relativePath(args.contentRoot??'',true)});previews.set(result.previewId,{listeners:new Set(),timer:null});return result;},
    reload:args=>{this.alive(binding);if(!previews.has(args.previewId))throw error('E_NOT_FOUND','试演不存在。');return this.call(binding,'previewReload',args);},
    close:async args=>{this.alive(binding);await this.call(binding,'previewClose',args);},
    on:(id,listener)=>{this.alive(binding);const record=previews.get(id);if(!record||typeof listener!=='function')throw error('E_NOT_FOUND','试演不存在。');record.listeners.add(listener);if(!record.timer)record.timer=setInterval(async()=>{if(binding.stopped)return;try{const events=await this.call(binding,'previewEvents',{previewId:id});for(const event of events)for(const fn of record.listeners)fn(event);}catch{clearInterval(record.timer);record.timer=null;}},500);return ()=>{record.listeners.delete(listener);if(!record.listeners.size){clearInterval(record.timer);record.timer=null;}};}
  };}
  bind(id,name){const owner=crypto.randomUUID(),binding={id,name,owner,grants:new Set(),blobs:new Map(),resources:new Set(),operations:new Set(),stopController:new AbortController(),stopped:false};this.bindings.set(owner,binding);const manager=this;
    const fileAPI={
      list:async args=>{const p=this.permission(binding,args.workspaceId),path=relativePath(args.path??'',true),tree=await this.entries(binding,p),limit=positive(args.limit??200,'分页大小',1000);let offset=0;if(args.cursor){let cursor;try{cursor=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(fromBase64(args.cursor)));}catch{throw error('E_STALE_CURSOR','分页游标无效。');}if(cursor.workspaceId!==p.id||cursor.path!==path||cursor.recursive!==!!args.recursive||cursor.revision!==tree.revision)throw error('E_STALE_CURSOR','目录已改变，请重新列举。');offset=positive(cursor.offset,'分页偏移',tree.entries.length,{zero:true});}const matching=tree.entries.filter(e=>e.path!==path&&within(path,e.path)&&(args.recursive||parentPath(e.path)===path));return {entries:matching.slice(offset,offset+limit).map(e=>this.publicEntry(e)),revision:tree.revision,...(offset+limit<matching.length?{nextCursor:toBase64(bytes(JSON.stringify({workspaceId:p.id,path,recursive:!!args.recursive,revision:tree.revision,offset:offset+limit})))}:{})};},
      stat:async ref=>{const p=this.permission(binding,ref.workspaceId),path=relativePath(ref.path),tree=await this.entries(binding,p),entry=tree.entries.find(e=>e.path===path);if(!entry)throw error('E_NOT_FOUND','文件不存在。',{path});return this.publicEntry(entry);},
      readText:(ref,options)=>this.readText(binding,ref,options),readBytes:(ref,options)=>this.readBytes(binding,ref,options),
      applyBatch:(args,options)=>this.batch(binding,args,options),
      beginWrite:async args=>{const p=this.permission(binding,args.workspaceId);positive(args.size,'素材大小',this.capabilities.limits.importFileBytes,{zero:true});const result=await this.call(binding,'begin',{root:p.root,size:args.size,mime:args.mime,sha256:args.sha256});binding.blobs.set(result.blobId,{workspaceId:p.id,size:args.size});return result;},
      writeChunk:async args=>{if(!(args.bytes instanceof Uint8Array)||args.bytes.byteLength>this.capabilities.limits.bridgeChunkBytes)throw error('E_LIMIT','传输块超过限制。');return this.call(binding,'chunk',{blobId:args.blobId,sequence:args.sequence,data:toBase64(args.bytes)});},
      finishWrite:async args=>{const result=await this.call(binding,'finish',args),b=binding.blobs.get(args.blobId);if(!b)throw error('E_NOT_FOUND','暂存对象不存在。');Object.assign(b,result,{finished:true});return result;},
      abortWrite:async args=>{await this.call(binding,'abort',args);binding.blobs.delete(args.blobId);},
      watch:(args,listener)=>{this.permission(binding,args.workspaceId);if(typeof listener!=='function')throw error('E_INVALID_DATA','事件监听器无效。');const w={binding,workspaceId:args.workspaceId,paths:(args.paths||[]).map(p=>relativePath(p,true)),listener};this.watchers.add(w);w.ready=this.entries(binding,this.project(args.workspaceId)).then(tree=>{if(!this.observed.has(args.workspaceId))this.observed.set(args.workspaceId,tree);}).catch(cause=>{if(!binding.stopped)this.host.fail(cause);});return ()=>this.watchers.delete(w);}
    };
    const api={workspace:{
      current:async()=>{this.alive(binding);const doc=this.host.current(),path=doc&&documentPath(doc),p=path&&this.projects().filter(p=>within(p.root,path)).sort((a,b)=>b.root.length-a.root.length)[0];if(!p)return null;await this.authorize(binding,p.id);return this.handle(binding,p);},
      list:async()=>{this.alive(binding);return Promise.all(this.projects().map(p=>this.handle(binding,p)));},
      open:async args=>this.handle(binding,await this.authorize(binding,args.workspaceId)),
      create:async args=>this.exclusive(binding,async()=>{const name=relativePath(args.name);if(name.includes('/'))throw error('E_INVALID_PATH','工作区名称不能包含斜杠。');const parent=args.parentWorkspaceId?this.permission(binding,args.parentWorkspaceId):null,root=(parent?.root?parent.root+'/':'')+name,tree=await this.call(binding,'tree',{root:parent?.root||''});if(tree.entries.some(e=>e.path.toLowerCase()===name.toLowerCase()))throw error('E_EXISTS','工作区已存在。');if(!await this.host.confirm('创建插件工作区',`在内部文件夹中创建“${name}”？`))throw error('E_PERMISSION','创建已取消。');this.alive(binding);const candidate=structuredClone(this.state()),config=createVelaV2(name),doc=newDocument('.vela',velaText(config));doc.path=root+'/.vela';candidate.documents.push(doc);candidate.folders=[...new Set([...(candidate.folders||[]),root])];candidate.treeRevision=(candidate.treeRevision||0)+1;await this.call(binding,'apply',{root:parent?.root||'',expected:[{path:name,revision:null}],changes:[{kind:'mkdir',path:name},{kind:'writeText',path:name+'/.vela',text:doc.text}],workspace:JSON.stringify(candidate)});this.host.adopt(candidate,{root,changed:[],removed:[]});binding.grants.add(config.id);return this.handle(binding,this.project(config.id));})
    },fs:fileAPI,
      documents:{open:async args=>{const p=this.permission(binding,args.workspaceId),read=await this.readText(binding,args);if(args.expectedRevision&&args.expectedRevision!==read.revision)throw error('E_CONFLICT','定位所依据的文稿已改变。');if(args.selection&&(!Number.isSafeInteger(args.selection.from)||!Number.isSafeInteger(args.selection.to)||args.selection.from<0||args.selection.to<args.selection.from||args.selection.to>read.text.length))throw error('E_INVALID_DATA','文稿选区无效。');return this.host.openDocument((p.root?p.root+'/':'')+relativePath(args.path),read,args);}},
      config:{patchExtension:async args=>{const read=await this.readText(binding,{workspaceId:args.workspaceId,path:'.vela'});if(read.revision!==args.expectedRevision)throw error('E_CONFLICT','工作区配置已改变。');const config=parseVela(read.text),patch=jsonObject(args.patch);config.extensions={...config.extensions,[binding.id]:{...config.extensions?.[binding.id],...patch}};const handle=await this.handle(binding,this.permission(binding,args.workspaceId));await this.batch(binding,{workspaceId:args.workspaceId,expectedWorkspaceRevision:handle.revision,idempotencyKey:crypto.randomUUID(),label:'插件配置',changes:[{kind:'writeText',path:'.vela',text:velaText(config),expectedRevision:read.revision}]});return {revision:await revision(velaText(config))};}},
      tasks:{status:async id=>{this.alive(binding);return this.tasks.status(owner,id);},cancel:async id=>{this.alive(binding);return this.tasks.cancel(owner,id);}},
      getCapabilities:async()=>{this.alive(binding);return structuredClone({apiVersion:3,platform:this.host.platform, ...this.capabilities});}
    };
    this.extendIO(api,binding,fileAPI);this.extendSnapshots(api,binding);this.extendAssets(api,binding);this.extendPreview(api,binding);
    return {api,stop:async()=>{binding.stopped=true;binding.stopController.abort();for(const w of this.watchers)if(w.binding===binding)this.watchers.delete(w);await this.tasks.stop(owner);await Promise.allSettled([...binding.operations]);try{if(this.capabilities.features.filesystem)await this.backend.call('stop',owner,{pluginId:id});}finally{for(const dispose of binding.resources)dispose();this.bindings.delete(owner);}}};
  }
}
