import {NativeArchiveBackend} from './project-archive.mjs';
import {native,transport} from './platform.mjs';
import {error,relativePath,within,mime,sha256,revision,bytes} from './project-contract.mjs';
import {fromBase64,toBase64} from './plugin-package.mjs';

const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(error('E_QUOTA','项目存储不可用，请检查空间。'));});
const database=()=>new Promise((resolve,reject)=>{const open=indexedDB.open('vela-project-api',2);open.onupgradeneeded=()=>{for(const name of ['files','state','snapshots','trash'])if(!open.result.objectStoreNames.contains(name))open.result.createObjectStore(name);};open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(error('E_UNSUPPORTED','浏览器项目存储不可用。'));});
export async function recoverBrowserProjects(){if(native||!localStorage.getItem('vela.project.pending'))return;const pending=JSON.parse(localStorage.getItem('vela.project.pending')),db=await database();try{const state=await request(db.transaction('state').objectStore('state').get('commit'));localStorage.setItem('wenzhou.workspace',state?.id===pending.id?state.workspace:pending.before);localStorage.removeItem('vela.project.pending');}finally{db.close();}}
export class BrowserProjectBackend {
  constructor(workspace){this.workspace=workspace;this.blobs=new Map();this.selections=new Map();this.sessions=new Map();}
  async files(){const db=await database();try{const store=db.transaction('files').objectStore('files');const [keys,values]=await Promise.all([request(store.getAllKeys()),request(store.getAll())]);return new Map(keys.map((key,i)=>[key,values[i]]));}finally{db.close();}}
  own(map,id,owner){const s=map.get(id);if(!s||s.owner!==owner)throw error('E_NOT_FOUND','会话不存在。');return s;}
  path(root,p){return (root?relativePath(root)+'/':'')+relativePath(p);}
  async tree(root){const files=await this.files(),w=this.workspace();for(const d of w.documents)files.set(d.path||d.name,{blob:new Blob([d.text]),revision:await revision(d.text),modifiedAt:new Date(d.updatedAt).toISOString()});for(const f of w.folders||[])if(!files.has(f))files.set(f,{directory:true,modifiedAt:new Date(0).toISOString()});const entries=[];for(const [full,f] of files)if(full!==root&&within(root,full)){const path=full.slice(root?root.length+1:0);entries.push({path,kind:f.directory?'directory':'file',mime:f.directory?'inode/directory':mime(path),size:f.directory?0:f.blob.size,revision:f.revision,modifiedAt:f.modifiedAt});}
    entries.sort((a,b)=>a.path.localeCompare(b.path));for(const e of entries.filter(e=>e.kind==='directory').sort((a,b)=>b.path.length-a.path.length))e.revision=await revision(JSON.stringify(entries.filter(child=>child!==e&&within(e.path,child.path)).map(child=>[child.path,child.revision])));return {entries,totalBytes:entries.reduce((s,e)=>s+e.size,0)};}
  async call(action,owner,a){const MB=1024*1024;switch(action){
    case 'receipt':return localStorage.getItem('wenzhou.workspace')||'';
    case 'capabilities':return {limits:{textBytes:8*MB,readChunkBytes:256*1024,bridgeChunkBytes:256*1024,importFileBytes:32*MB,projectEntries:2000,archiveExpandedBytes:0,archiveEntries:0,projectBytes:64*MB,snapshotBytes:64*MB},resource:{range:false,worker:typeof Worker!=='undefined',canvas2d:true},features:{filesystem:true,transactions:true,assetSessions:true,archives:false,snapshots:true,nativePicker:false,independentPreview:false,externalWatch:false}};
    case 'tree':return this.tree(a.root);
    case 'begin':{if(a.size<0||a.size>32*MB)throw error('E_LIMIT','素材超过 32 MB。');const blobId=crypto.randomUUID();this.blobs.set(blobId,{owner,root:a.root,size:a.size,expectedHash:a.sha256,blob:new Blob([]),sequence:0});return {blobId,maxChunkBytes:256*1024};}
    case 'chunk':{const s=this.own(this.blobs,a.blobId,owner),data=fromBase64(a.data),hash=await sha256(data);if(a.sequence===s.sequence-1&&hash===s.last)return {acceptedBytes:s.blob.size,nextSequence:s.sequence};if(a.sequence!==s.sequence||s.blob.size+data.length>s.size||data.length>256*1024||s.complete)throw error('E_INVALID_DATA','块大小或顺序无效。');s.blob=new Blob([s.blob,data]);s.sequence++;s.last=hash;return {acceptedBytes:s.blob.size,nextSequence:s.sequence};}
    case 'finish':{const s=this.own(this.blobs,a.blobId,owner);if(s.size!==s.blob.size)throw error('E_INVALID_DATA','素材大小不匹配。');s.sha256||=await sha256(await s.blob.arrayBuffer());if(s.expectedHash&&s.expectedHash!==s.sha256)throw error('E_INVALID_DATA','素材摘要不匹配。');s.complete=true;return {blobId:a.blobId,size:s.size,sha256:s.sha256};}
    case 'abort':this.own(this.blobs,a.blobId,owner);this.blobs.delete(a.blobId);return true;
    case 'apply':{const files=await this.files(),tree=await this.tree(a.root),before=new Map(files),deleted=[];for(const doc of this.workspace().documents)files.set(doc.path||doc.name,{blob:new Blob([doc.text]),revision:await revision(doc.text),modifiedAt:new Date(doc.updatedAt).toISOString()});for(const folder of this.workspace().folders||[])if(!files.has(folder))files.set(folder,{directory:true,modifiedAt:new Date(0).toISOString()});for(const e of a.expected||[])if((tree.entries.find(f=>f.path===e.path)?.revision??null)!==e.revision)throw error('E_CONFLICT','文件已改变。',{path:e.path});const full=p=>this.path(a.root,p);for(const c of a.changes){const p=full(c.path||c.from);if(c.kind==='mkdir')files.set(p,{directory:true,modifiedAt:new Date().toISOString()});else if(c.kind==='writeText')files.set(p,{blob:new Blob([c.text]),revision:await revision(c.text),modifiedAt:new Date().toISOString()});else if(c.kind==='writeBlob'){const s=this.own(this.blobs,c.blobId,owner);if(!s.complete||s.root!==a.root)throw error('E_INVALID_DATA','素材尚未完成。');files.set(p,{blob:s.blob,revision:'r:'+s.sha256,modifiedAt:new Date().toISOString()});}else if(c.kind==='move'||c.kind==='copy'){const to=full(c.to);if(files.has(to))throw error('E_EXISTS','目标已存在。');for(const [key,f] of [...files])if(within(p,key)){if(c.kind==='move')files.delete(key);files.set(to+key.slice(p.length),f);}}else if(c.kind==='delete'){const records=[...files].filter(([key])=>within(p,key));if(!c.trashId)throw error('E_INVALID_DATA','删除没有回收站标识。');deleted.push({id:c.trashId,records});for(const [key] of records)files.delete(key);}else throw error('E_INVALID_DATA','变更类型无效。');}
      if([...files.values()].reduce((s,f)=>s+(f.blob?.size||0),0)>64*MB)throw error('E_QUOTA','浏览器项目超过 64 MB。');const db=await database(),id=crypto.randomUUID(),pending={id,before:localStorage.getItem('wenzhou.workspace')||''};localStorage.setItem('vela.project.pending',JSON.stringify(pending));try{const tx=db.transaction(['files','state','trash'],'readwrite'),store=tx.objectStore('files');for(const key of before.keys())if(!files.has(key))store.delete(key);for(const [key,value] of files)if(before.get(key)!==value)store.put(value,key);for(const record of deleted)tx.objectStore('trash').put(record,record.id);tx.objectStore('state').put({id,workspace:a.workspace},'commit');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(error('E_QUOTA','项目写入失败，原始数据已保留。'));tx.onabort=tx.onerror;});localStorage.setItem('wenzhou.workspace',a.workspace);localStorage.removeItem('vela.project.pending');return {committed:true};}finally{db.close();}}
    case 'restoreTrashPayload':{const db=await database();try{const item=await request(db.transaction('trash').objectStore('trash').get(a.id));if(!item)throw error('E_NOT_FOUND','回收站素材不存在。');const files=await this.files();if(!a.permanent)for(const [path] of item.records)if(files.has(path))throw error('E_EXISTS','原路径已存在。',{path});const id=crypto.randomUUID(),pending={id,before:localStorage.getItem('wenzhou.workspace')||''};localStorage.setItem('vela.project.pending',JSON.stringify(pending));const tx=db.transaction(['files','state','trash'],'readwrite');if(!a.permanent)for(const [path,value] of item.records)tx.objectStore('files').put(value,path);tx.objectStore('trash').delete(a.id);tx.objectStore('state').put({id,workspace:a.workspace},'commit');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(error('E_QUOTA','回收站恢复失败，原数据已保留。'));tx.onabort=tx.onerror;});localStorage.setItem('wenzhou.workspace',a.workspace);localStorage.removeItem('vela.project.pending');return true;}finally{db.close();}}
    case 'read':{let f;if(a.snapshotId){const record=await this.snapshot(owner,a);f=record.files.find(f=>f.path===a.path);if(!f)throw error('E_NOT_FOUND','快照文件不存在。');}else{const full=this.path(a.root,a.path),doc=this.workspace().documents.find(d=>(d.path||d.name)===full);f=doc?{blob:new Blob([doc.text]),revision:await revision(doc.text)}:(await this.files()).get(full);}if(!f?.blob)throw error('E_NOT_FOUND','文件不存在。');if(a.expectedRevision&&a.expectedRevision!==f.revision)throw error('E_CONFLICT','文件已改变。');const offset=a.offset||0,length=a.length??Math.min(256*1024,f.blob.size-offset);if(!Number.isSafeInteger(offset)||!Number.isSafeInteger(length)||offset<0||length<0||length>256*1024||offset>f.blob.size)throw error('E_LIMIT','读取范围无效。');return {data:toBase64(new Uint8Array(await f.blob.slice(offset,offset+length).arrayBuffer())),revision:f.revision,totalSize:f.blob.size};}
    case 'pick':{const input=document.createElement('input');input.type='file';input.multiple=a.multiple;input.accept=a.accept.join(',');return new Promise(resolve=>{input.oncancel=()=>resolve({cancelled:true,selections:[]});input.onchange=()=>{const selections=[];for(const file of input.files){const token=crypto.randomUUID();this.selections.set(token,{owner,file});selections.push({token,name:file.name,size:file.size,mime:file.type||mime(file.name)});}resolve({cancelled:false,selections});};input.click();});}
    case 'selectionStage':{const s=this.own(this.selections,a.token,owner);if(s.file.size>32*MB)throw error('E_LIMIT','素材超过 32 MB。');const blobId=crypto.randomUUID(),hash=await sha256(await s.file.arrayBuffer());this.blobs.set(blobId,{owner,root:a.root,blob:s.file,size:s.file.size,sha256:hash,complete:true});this.selections.delete(a.token);return {blobId,size:s.file.size,sha256:hash};}
    case 'snapshotCreate':{const tree=await this.tree(a.root),files=await this.files(),record={id:crypto.randomUUID(),owner:a.pluginId,workspaceId:a.workspaceId,root:a.root,includeRoots:a.includeRoots,label:a.label,createdAt:new Date().toISOString(),entries:tree.entries.filter(e=>a.includeRoots.some(root=>within(root,e.path))).map(e=>({...e,...(a.entries||[]).find(v=>v.path===e.path)})),workspace:a.workspace,files:[]};let size=0;for(const e of record.entries)if(e.kind==='file'){const full=this.path(a.root,e.path),doc=this.workspace().documents.find(d=>(d.path||d.name)===full),f=doc?{blob:new Blob([doc.text]),revision:await revision(doc.text)}:files.get(full);record.files.push({...f,path:e.path});size+=f.blob.size;}record.bytes=size;const db=await database();try{await request(db.transaction('snapshots','readwrite').objectStore('snapshots').put(record,record.id));}finally{db.close();}return {snapshotId:record.id,bytes:size};}
    case 'snapshotList':{const db=await database();try{return (await request(db.transaction('snapshots').objectStore('snapshots').getAll())).filter(r=>r.owner===a.pluginId&&r.workspaceId===a.workspaceId).map(({id,label,createdAt,bytes})=>({id,label,createdAt,bytes}));}finally{db.close();}}
    case 'snapshotEntries':return this.snapshot(owner,a);
    case 'snapshotStage':{const r=await this.snapshot(owner,a),entries=[];for(const e of r.entries){if(e.kind==='directory'){entries.push(e);continue;}const f=r.files.find(f=>f.path===e.path),blobId=crypto.randomUUID();this.blobs.set(blobId,{owner,root:a.root,blob:f.blob,size:e.size,complete:true,sha256:e.revision.slice(2)});entries.push({...e,blobId,sha256:e.revision.slice(2)});}return {entries};}
    case 'assetOpen':{if(a.snapshotId)await this.snapshot(owner,a);const sessionId=crypto.randomUUID();this.sessions.set(sessionId,{...a,owner});return {sessionId};}
    case 'assetResolve':{const s=this.own(this.sessions,a.sessionId,owner);relativePath(a.path);if(!s.allowedRoots.some(root=>within(root,a.path)))throw error('E_PERMISSION','资源越过授权范围。');const f=s.snapshotId?(await this.snapshot(owner,{...s,snapshotId:s.snapshotId})).files.find(f=>f.path===a.path):(await this.files()).get(this.path(s.root,a.path));if(!f?.blob)throw error('E_NOT_FOUND','资源不存在。');if(a.expectedRevision&&a.expectedRevision!==f.revision)throw error('E_CONFLICT','资源已改变。');return {blob:f.blob,mime:mime(a.path),size:f.blob.size,revision:f.revision,supportsRange:false};}
    case 'assetRelease':this.own(this.sessions,a.sessionId,owner);this.sessions.delete(a.sessionId);return true;
    case 'stop':for(const map of [this.blobs,this.sessions,this.selections])for(const [key,s] of map)if(s.owner===owner)map.delete(key);return true;
    case 'cancel':return true;
    default:throw error('E_UNSUPPORTED','浏览器预览不支持此能力，请在原生应用中使用。');
  }}
  async snapshot(owner,a){const db=await database();try{const r=await request(db.transaction('snapshots').objectStore('snapshots').get(a.snapshotId));if(!r||r.owner!==a.pluginId||a.workspaceId&&r.workspaceId!==a.workspaceId)throw error('E_NOT_FOUND','快照不存在或不属于此插件。');return r;}finally{db.close();}}
}
export function projectBackend(workspace,platform=window.WenzhouNative?.platform){const backend=native?{call:async(action,owner,args)=>{try{return await transport('project',{action,owner,request:JSON.stringify(args)});}catch(cause){if(action==='capabilities'&&!cause.code)return {limits:{textBytes:0,readChunkBytes:0,bridgeChunkBytes:0,importFileBytes:0,projectEntries:0,archiveExpandedBytes:0,archiveEntries:0,projectBytes:0,snapshotBytes:0},resource:{range:false,worker:false,canvas2d:true},features:{filesystem:false,transactions:false,assetSessions:false,archives:false,snapshots:false,nativePicker:false,independentPreview:false,externalWatch:false}};throw cause;}}}:new BrowserProjectBackend(workspace);return native&&['harmony','harmonyos'].includes(platform)?new NativeArchiveBackend(backend):backend;}
