import {documentKind} from './model.mjs';
import {documentPath} from './workspace.mjs';
import {readingDocuments,projectConfig,projectWriter,readingLayout} from './vela.mjs';
import {displayChapterTitle,chapterOffset,lineOffsets,renderPlainChapters,fitReadingLayout,swipeDirection,readingPageInfo,readingGeometry,spreadStart,paginatedPages} from './reader-layout.mjs';
import {parseCsv,csvDelimiter} from './csv.mjs';
import {bindTextZoom} from './gestures.mjs';
import {resolveReadingOffset,characterRect,visibleTextOffset,invalidateTextIndex} from './reading-position.mjs';
import {readingWindow,ReadingScrollWindow} from './reading-window.mjs';
import {mountReadingTools} from './reading-tools.mjs';
import {renderReadingMarks} from './reading-marks.mjs';
import {highlightMarkdown} from './code-preview.mjs';
import Writer from '../vendor/acode-writer/src/core.js';
import {chapterMatcher} from './chapters.mjs';
import {t} from './i18n.mjs';
import {icon} from './icons.mjs';

export class Reader {
  constructor(options){Object.assign(this,options);this.id=null;this.page=0;this.epoch=0;this.resize=new ResizeObserver(()=>this.layout());this.resize.observe(this.root);window.addEventListener('pagehide',()=>this.persist());document.addEventListener('keydown',event=>this.handleKey(event));}
  handleKey(event){
    if(!this.id||this.root.hidden||event.defaultPrevented||event.ctrlKey||event.metaKey||event.altKey||event.shiftKey||document.querySelector('dialog[open]')||event.target.closest?.('input,textarea,select,button,[contenteditable=true]'))return;
    if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','PageUp','PageDown',' '].includes(event.key)){event.preventDefault();this.turn(['ArrowLeft','ArrowUp','PageUp'].includes(event.key)?-1:1);}else if(event.key==='Escape'){event.preventDefault();this.chrome();}
  }
  stop(){this.closeTools?.();this.closeTools=null;this.measuringKey=null;this.measureGeneration=(this.measureGeneration||0)+1;clearTimeout(this.measureTimer);this.measureBox?.remove();this.measureBox=null;this.pdfPane?.dispose();this.pdfPane=null;clearTimeout(this.positionTimer);clearInterval(this.clockTimer);this.persist();}
  home(){this.stop();this.epoch++;this.id=null;this.onChrome?.(false,false);const workspace=this.workspace(),docs=readingDocuments(workspace),esc=this.escape;
    this.root.classList.remove('reader-paged','reader-double');this.root.innerHTML=`<div class="reader-stage"><section class="reader-library"><header><h1>${t('阅读')}</h1><input id="reader-search" type="search" placeholder="${t('搜索文稿…')}" aria-label="${t('搜索文稿')}"></header><div class="reader-books"></div></section><section class="reader-document" inert></section></div>`;
    const list=()=>{const query=this.root.querySelector('#reader-search').value.toLowerCase();this.root.querySelector('.reader-books').innerHTML=docs.filter(doc=>(doc.name+' '+documentPath(doc)).toLowerCase().includes(query)).map(doc=>{const project=projectConfig(workspace,doc),relative=documentPath(doc).slice(project?.folder?project.folder.length+1:0),entry=project?.config?.reading.items?.find(item=>item.path===relative),title=entry?.title||doc.name.replace(/\.[^.]+$/,''),position=workspace.readerPositions?.[doc.id],percent=Math.round(Math.max(0,Math.min(1,Number(position?.ratio)||0))*100);return `<button class="reader-book" data-read="${esc(doc.id)}"><span class="book-cover">${documentKind(doc)}</span><strong data-user-content>${esc(title)}</strong><small data-user-content>${esc([project?.config?.project?.name||documentPath(doc),entry?.group].filter(Boolean).join(' · '))}</small>${position?`<div class="book-progress"><progress max="100" value="${percent}" aria-label="${t('阅读进度')}"></progress><span>${percent}%</span></div>`:''}</button>`;}).join('')||`<p class="blank">${t('没有可阅读的文件，请在工作区 .vela 中选择阅读文件。')}</p>`;};list();this.root.querySelector('#reader-search').oninput=list;
    this.root.querySelector('.reader-books').onclick=e=>{const button=e.target.closest('[data-read]');if(button)this.open(button.dataset.read).catch(this.fail);};
  }
  localize(){if(!this.id){if(this.root.childElementCount)this.home();return;}for(const [id,label] of [['reader-back','返回书库'],['reader-outline-action','章节目录'],['reader-tools','全文搜索'],['reader-notes','批注']]){const button=this.root.querySelector('#'+id);button.title=t(label);button.setAttribute('aria-label',t(label));}this.root.querySelector('#reader-chapter').title=t('当前章节');this.clock();if(this.kind==='CSV')this.renderCsv();const html=this.root.querySelector('#reader-html');if(html){html.title=t('打开 HTML 阅读');html.setAttribute('aria-label',html.title);}}
  leave(){this.stop();this.id=null;this.epoch++;this.onChrome?.(false,false);}
  chrome(show=!this.chromeVisible){this.chromeVisible=show;this.root.classList.toggle('reader-chrome-visible',show);this.onChrome?.(true,show);if(!show){this.root.querySelector('.reader-outline')?.remove();this.closeTools?.();}}
  async open(id){
    this.stop();const workspace=this.workspace(),doc=readingDocuments(workspace).find(doc=>doc.id===id);if(!doc)return;getSelection()?.removeAllRanges();
    const epoch=++this.epoch;await this.load?.(doc);if(epoch!==this.epoch||this.root.hidden)return;this.id=id;this.page=0;this.searchHit=null;this.doc=doc;this.kind=documentKind(doc);const project=projectConfig(workspace,doc);this.config=project?.config;this.readingLayout=readingLayout(project?.config?.reading.layout);this.size=project?.config?.reading?.layout?.fontSize??workspace.readerSizes?.[id]??workspace.settings.fontSize;
    this.position=workspace.readerPositions?.[id]||null;workspace.readingRecent=id;const root=this.root.querySelector('.reader-document');root.inert=false;
    const relative=documentPath(doc).slice(project?.folder?project.folder.length+1:0),bookTitle=project?.config?.reading?.items?.find(item=>item.path===relative)?.title||doc.name.replace(/\.[^.]+$/,'');
    const action=(id,label,name)=>`<button id="${id}" title="${t(label)}" aria-label="${t(label)}">${icon(name)}</button>`;
    root.innerHTML=`<header class="reader-header"><div class="reader-header-left">${action('reader-back','返回书库','back')}<strong id="reader-title" data-user-content title="${this.escape(bookTitle)}">${this.escape(bookTitle)}</strong></div><i class="reader-notch-space" aria-hidden="true"></i><div class="reader-header-right">${action('reader-outline-action','章节目录','outline')}${action('reader-tools','全文搜索','search')}${action('reader-notes','批注','annotation')}</div><span id="reader-chapter" data-user-content title="${t('当前章节')}" hidden></span></header><div class="reader-viewport" tabindex="0" aria-label="${t('阅读正文')}"><article class="reader-content" data-user-content></article></div><footer class="reader-pagebar"><time id="reader-clock"></time><span id="reader-footer-chapter" data-user-content></span><span class="reader-progress"><span id="reader-position"></span><span id="reader-percent"></span></span></footer>`;
    const content=root.querySelector('.reader-content');content.style.fontSize=this.size+'px';const writer=projectWriter(workspace,doc),sections=Writer.buildIndex(doc.text,writer,chapterMatcher(writer)).sections;this.writer=writer;this.windowModel=!['MD','HTML','CSV','TEX','PDF'].includes(this.kind)&&doc.text.length>120000?readingWindow(doc):null;this.scrollState=null;this.scrollKey=null;this.renderMode=null;this.chunk=this.windowModel?.at(this.position?.offset||0)||0;this.root.classList.toggle('reader-no-titlepage',this.config?.reader?.titlePage===false);
    if(this.kind==='HTML'){content.innerHTML=`<button id="reader-html" class="secondary" title="${t('打开 HTML 阅读')}" aria-label="${t('打开 HTML 阅读')}">${icon('external')}</button>`;root.querySelector('#reader-html').onclick=()=>this.html(doc,this.size,this.readingLayout).catch(this.fail);}
    else if(this.kind==='CSV'){this.csv=parseCsv(doc.text,doc.delimiter||csvDelimiter(doc.text));this.csvRow=this.position?.csvRow||0;this.csvColumn=this.position?.csvColumn||0;this.renderCsv();}
    else if(['TEX','PDF'].includes(this.kind)){this.pdfPane=this.latex(content,doc,pane=>{pane.page=Math.max(1,Math.min(pane.pdf.numPages,this.position?.pdfPage||1));pane.onPage=(page,pages,end=page)=>{this.position={pdfPage:page,updatedAt:Date.now()};this.root.querySelector('#reader-position').textContent=`${page}${end!==page?'–'+end:''} / ${pages}`;this.root.querySelector('#reader-percent').textContent=`${Math.round(end/pages*100)}%`;this.renderMarks();this.persist();};pane.render().catch(this.fail);});}
    else if(this.kind==='MD'){content.innerHTML=this.sanitize(this.markdown.render(doc.text,{path:documentPath(doc)}),{FORBID_TAGS:['iframe','form','input','button','video','audio','style'],FORBID_ATTR:['style','contenteditable']});this.assets?.(content);}
    else{content.classList.add('reader-plain');if(this.windowModel)this.renderChunk(this.chunk,content);else renderPlainChapters(content,doc.text,sections);}
    if(this.kind==='MD'){content.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach(heading=>heading.classList.add('reader-section-title'));highlightMarkdown(content).then(()=>{if(epoch===this.epoch&&content.isConnected){invalidateTextIndex(content);this.layout();}});}
    const offsets=lineOffsets(doc.text),renderedText=content.textContent;this.chapters=sections.map(section=>({...section,offset:!['MD','HTML','CSV','TEX'].includes(this.kind)?chapterOffset(doc.text,section.row,offsets):Math.max(0,renderedText.indexOf(section.title.replace(/^#{1,6}\s+/,'')))}));this.renderedText=this.windowModel?doc.text:renderedText;
    mountReadingTools(this);root.querySelector('#reader-back').onclick=()=>this.home();root.querySelector('#reader-outline-action').onclick=()=>this.toggleOutline();const viewport=root.querySelector('.reader-viewport');
    viewport.onkeydown=e=>this.handleKey(e);
    viewport.addEventListener('scroll',()=>{if(!this.restoring&&!this.paged){if(this.windowModel&&this.scrollState&&!getSelection()?.toString()){const target=this.scrollState.at(viewport.scrollTop);if(target!==this.scrollCenter)this.renderScrollChunk(target);}this.capture();}},{passive:true});
    bindTextZoom(viewport,()=>this.size,size=>this.setSize(size),()=>{workspace.readerSizes={...workspace.readerSizes,[id]:this.size};this.persist();});
    let start=null,dragged=false,pointers=new Set();viewport.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size===1){start={x:e.clientX,y:e.clientY};dragged=false;}else{start=null;dragged=true;}});viewport.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>12)dragged=true;});viewport.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;dragged=true;});
    viewport.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(start&&dragged&&e.pointerType==='touch'&&(this.paged||this.pdfPane)&&!getSelection()?.toString()){const direction=swipeDirection(e.clientX-start.x,e.clientY-start.y);if(direction)this.turn(direction);}start=null;});
    viewport.onclick=e=>{const selection=getSelection();if(dragged||e.target.closest('a,button,input,select')||(selection?.toString()&&viewport.contains(selection.anchorNode)))return;const box=viewport.getBoundingClientRect(),fraction=(e.clientX-box.left)/box.width;if(fraction<.3)this.turn(-1);else if(fraction>.7)this.turn(1);else this.chrome();};
    this.root.querySelector('.reader-stage').classList.add('reading');this.root.querySelector('.reader-library').inert=true;this.chrome(false);this.clock();this.clockTimer=setInterval(()=>this.clock(),30000);this.save();requestAnimationFrame(()=>this.layout());
    this.assets?.(content);if(this.kind==='HTML'){await new Promise(resolve=>setTimeout(resolve,180));if(epoch===this.epoch&&this.id===id)await this.html(doc,this.size,this.readingLayout);}
  }
  clock(){const clock=this.root.querySelector('#reader-clock');if(clock)clock.textContent=new Date().toLocaleTimeString(this.workspace().settings.language==='en'?'en-GB':'zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});}
  renderChunk(index,content=this.root.querySelector('.reader-content')){this.chunk=index;const text=this.windowModel.textAt(index),sections=Writer.buildIndex(text,this.writer,chapterMatcher(this.writer)).sections;renderPlainChapters(content,text,sections);invalidateTextIndex(content);}
  renderScrollChunk(index,content=this.root.querySelector('.reader-content')){
    if(!content||!this.scrollState)return;this.scrollCenter=index;this.scrollFrom=Math.max(0,index-1);const end=Math.min(this.windowModel.chunks.length-1,index+1),fragment=document.createDocumentFragment(),top=document.createElement('div'),bottom=document.createElement('div'),wrappers=[];
    top.className=bottom.className='reader-scroll-spacer';top.setAttribute('aria-hidden','true');bottom.setAttribute('aria-hidden','true');fragment.append(top);
    for(let i=this.scrollFrom;i<=end;i++){const wrapper=document.createElement('div');wrapper.className='reader-scroll-chunk';const text=this.windowModel.textAt(i);renderPlainChapters(wrapper,text,Writer.buildIndex(text,this.writer,chapterMatcher(this.writer)).sections);fragment.append(wrapper);wrappers.push({index:i,wrapper});}fragment.append(bottom);content.replaceChildren(fragment);invalidateTextIndex(content);
    for(const {index,wrapper} of wrappers)this.scrollState.measured(index,wrapper.getBoundingClientRect().height);
    top.style.height=this.scrollState.prefix[this.scrollFrom]+'px';bottom.style.height=(this.scrollState.total-this.scrollState.prefix[end+1])+'px';
  }
  measureChunks(key){if(this.measuringKey===key)return;this.measuringKey=key;const generation=this.measureGeneration=(this.measureGeneration||0)+1;clearTimeout(this.measureTimer);this.measureBox?.remove();const viewport=this.root.querySelector('.reader-viewport'),content=this.root.querySelector('.reader-content'),model=this.windowModel,counts=this.chunkCounts;const next=()=>{if(generation!==this.measureGeneration||!this.id)return;const index=counts.findIndex(value=>!Number.isFinite(value));if(index<0){this.measureBox?.remove();this.measureBox=null;this.capture();return;}const box=document.createElement('div');box.className='reader-measure';box.style.cssText=`position:absolute;left:0;top:0;width:${viewport.clientWidth}px;height:${viewport.clientHeight}px;visibility:hidden;pointer-events:none;overflow:hidden;contain:layout paint;`;const sample=content.cloneNode(false);sample.style.transform='';const text=model.textAt(index);renderPlainChapters(sample,text,Writer.buildIndex(text,this.writer,chapterMatcher(this.writer)).sections);box.append(sample);viewport.append(box);this.measureBox=box;counts[index]=paginatedPages(sample,this.geometry);box.remove();this.measureBox=null;this.measureTimer=setTimeout(next,30);};this.measureTimer=setTimeout(next,300);}
  renderCsv(){const content=this.root.querySelector('.reader-content');if(!content)return;const rows=this.csv,columns=rows.reduce((max,row)=>Math.max(max,row.length),0),rowPages=Math.max(1,Math.ceil(rows.length/100)),columnPages=Math.max(1,Math.ceil(columns/50));this.csvRow=Math.max(0,Math.min(rowPages-1,this.csvRow));this.csvColumn=Math.max(0,Math.min(columnPages-1,this.csvColumn));invalidateTextIndex(content);content.innerHTML=`<div class="reader-csv-tools"><button data-csv-row="-1" ${this.csvRow?'':'disabled'}>←</button><span>${t('行')} ${this.csvRow+1} / ${rowPages}</span><button data-csv-row="1" ${this.csvRow+1<rowPages?'':'disabled'}>→</button><button data-csv-column="-1" ${this.csvColumn?'':'disabled'}>←</button><span>${t('列')} ${this.csvColumn+1} / ${columnPages}</span><button data-csv-column="1" ${this.csvColumn+1<columnPages?'':'disabled'}>→</button></div><table>`+rows.slice(this.csvRow*100,(this.csvRow+1)*100).map(row=>'<tr>'+row.slice(this.csvColumn*50,(this.csvColumn+1)*50).map(cell=>'<td>'+this.escape(cell)+'</td>').join('')+'</tr>').join('')+'</table>';this.renderedText=content.textContent;content.querySelectorAll('[data-csv-row],[data-csv-column]').forEach(button=>button.onclick=()=>{if(button.dataset.csvRow)this.csvRow+=Number(button.dataset.csvRow);else this.csvColumn+=Number(button.dataset.csvColumn);this.page=0;this.renderCsv();this.position=null;this.layout();this.capture();});}
  setSize(size){if(this.pdfPane){this.size=Math.max(10,Math.min(40,Math.round(size)));this.pdfPane.zoom=this.size/16;this.pdfPane.render().catch(this.fail);return;}this.size=Math.max(10,Math.min(40,Math.round(size)));const content=this.root.querySelector('.reader-content');if(content){content.style.fontSize=this.size+'px';this.layout();}}
  layout(){
    if(!this.id||!this.root.offsetWidth)return;
    const refreshed=projectConfig(this.workspace(),this.doc)?.config;if(refreshed!==this.config){this.config=refreshed;this.readingLayout=readingLayout(refreshed?.reading.layout);this.size=refreshed?.reading?.layout?.fontSize??this.size;this.root.classList.toggle('reader-no-titlepage',refreshed?.reader?.titlePage===false);const current=this.root.querySelector('.reader-content');if(current)current.style.fontSize=this.size+'px';}
    if(['TEX','PDF'].includes(this.kind)){this.root.classList.remove('reader-paged','reader-double');this.pdfPane?.render().catch(this.fail);return;}
    const viewport=this.root.querySelector('.reader-viewport'),content=this.root.querySelector('.reader-content');if(!viewport||!content)return;
    this.restoring=true;const mode=this.config?.reader?.mode||this.workspace().settings.readingMode;this.geometry=readingGeometry(mode==='auto'?(viewport.clientWidth>=1000?'double':'scroll'):mode||this.workspace().settings.readingMode,viewport.clientWidth);this.paged=this.geometry.paged;this.root.classList.toggle('reader-paged',this.paged);this.root.classList.toggle('reader-double',this.paged&&this.geometry.columns===2);
    const useWindow=!['MD','HTML','CSV','TEX','PDF'].includes(this.kind)&&this.doc.text.length>120000;if(useWindow&&!this.windowModel){this.windowModel=readingWindow(this.doc);this.chunk=-1;this.measuringKey=null;}else if(!useWindow&&this.windowModel){this.measureGeneration=(this.measureGeneration||0)+1;clearTimeout(this.measureTimer);this.measureBox?.remove();this.measuringKey=null;this.windowModel=null;renderPlainChapters(content,this.doc.text,this.chapters);invalidateTextIndex(content);}
    if(this.windowModel&&this.paged){const chunk=this.windowModel.at(this.position?.offset||0);if(chunk!==this.chunk||this.renderMode!=='pages'||!content.childNodes.length)this.renderChunk(chunk,content);this.renderMode='pages';}
    const layout=fitReadingLayout(this.readingLayout,this.geometry.pageWidth,viewport.clientHeight);
    for(const [key,value] of Object.entries(layout))content.style.setProperty('--reader-'+key,key==='lineHeight'?String(value):value+'px');
    content.style.setProperty('--reader-page-height',Math.max(80,viewport.clientHeight-layout.marginTop-layout.marginBottom)+'px');
    content.style.setProperty('--page-width',this.geometry.pageWidth+'px');content.style.setProperty('--reader-gap',this.geometry.gap+'px');content.style.transform='';
    if(this.windowModel&&!this.paged){const key=JSON.stringify([this.size,layout,viewport.clientWidth]);if(this.scrollKey!==key){this.scrollState=new ReadingScrollWindow(this.windowModel,{width:Math.max(80,viewport.clientWidth-layout.marginLeft-layout.marginRight),fontSize:this.size,lineHeight:layout.lineHeight});this.scrollKey=key;}this.renderScrollChunk(this.windowModel.at(this.position?.offset||0),content);this.renderMode='scroll';this.measuringKey=null;this.measureGeneration=(this.measureGeneration||0)+1;clearTimeout(this.measureTimer);this.measureBox?.remove();}
    this.pages=this.paged?paginatedPages(content,this.geometry):1;
    if(this.position){const offset=resolveReadingOffset(this.renderedText,this.position)-(this.windowModel?.chunks[this.paged?this.chunk:this.scrollFrom??this.chunk].from||0),rect=characterRect(content,offset);if(rect){if(this.paged)this.page=Math.floor((rect.left-content.getBoundingClientRect().left)/this.geometry.stride);else viewport.scrollTop+=rect.top-viewport.getBoundingClientRect().top;}else if(!this.paged)viewport.scrollTop=this.position.ratio*Math.max(0,viewport.scrollHeight-viewport.clientHeight);}
    this.page=spreadStart(this.page,this.pages,this.geometry.columns);if(this.paged)content.style.transform=`translateX(${-this.page*this.geometry.stride}px)`;
    this.restoring=false;if(this.windowModel&&this.paged){const key=JSON.stringify([this.size,layout,this.geometry,viewport.clientHeight,this.config?.reader?.titlePage]);this.chunkCounts=this.windowModel.layout(key);this.chunkCounts[this.chunk]=this.pages;this.measureChunks(key);}this.capture();
  }
  turn(delta){
    if(!this.id)return;if(this.pdfPane){this.pdfPane.turn(delta);return;}
    const viewport=this.root.querySelector('.reader-viewport'),content=this.root.querySelector('.reader-content');if(!viewport)return;
    if(this.paged){
      let next=spreadStart(this.page+delta*this.geometry.columns,this.pages,this.geometry.columns),changeChunk=0;if(this.windowModel&&next===this.page){if(delta>0&&this.chunk<this.windowModel.chunks.length-1)changeChunk=1;else if(delta<0&&this.chunk>0)changeChunk=-1;}if(next===this.page&&!changeChunk)return;
      if(changeChunk){this.renderChunk(this.chunk+changeChunk,content);content.style.transform='';this.pages=paginatedPages(content,this.geometry);this.chunkCounts[this.chunk]=this.pages;next=changeChunk>0?0:spreadStart(this.pages-1,this.pages,this.geometry.columns);}this.page=next;const base=-this.page*this.geometry.stride;content.style.transform=`translateX(${base}px)`;this.capture();
    }else{viewport.scrollBy({top:delta*viewport.clientHeight,behavior:'instant'});this.capture();}
  }
  renderMarks(){renderReadingMarks(this);}
  capture(){
    if(!this.id||['TEX','PDF'].includes(this.kind))return;const viewport=this.root.querySelector('.reader-viewport'),content=this.root.querySelector('.reader-content');if(!viewport||!content)return;
    const offset=visibleTextOffset(content,viewport,this.paged)+(this.windowModel?.chunks[this.paged?this.chunk:this.scrollFrom??this.chunk].from||0),info=readingPageInfo({paged:this.paged,page:this.page,pages:this.pages,columns:this.geometry?.columns,scrollTop:viewport.scrollTop,scrollHeight:viewport.scrollHeight,height:viewport.clientHeight});
    if(this.windowModel&&this.paged){const computed=this.windowModel.info(this.chunk,this.page,this.chunkCounts||[]);info.page=computed.prefixKnown?computed.page:'…';info.pages=computed.pages??'…';info.end=computed.prefixKnown&&this.geometry.columns===2?info.page+1:info.page;info.ratio=this.doc.text.length?offset/this.doc.text.length:1;if(computed.pages)info.end=Math.min(info.end,computed.pages);if(this.chunk===this.windowModel.chunks.length-1&&this.page+this.geometry.columns>=this.pages)info.ratio=1;}
    if(this.windowModel&&!this.paged)info.ratio=this.doc.text.length?offset/this.doc.text.length:1;
    this.position={offset,context:this.renderedText.slice(offset,offset+64),ratio:info.ratio,csvRow:this.csvRow||0,csvColumn:this.csvColumn||0,mode:this.paged?'pages':'scroll',updatedAt:Date.now()};
    this.root.querySelector('#reader-position').textContent=`${info.page}${info.end&&info.end!==info.page?'–'+info.end:''} / ${info.pages}`;this.root.querySelector('#reader-percent').textContent=`${Math.round(Math.max(0,Math.min(1,info.ratio))*100)}%`;
    const section=[...(this.chapters||[])].reverse().find(section=>section.offset<=offset),title=displayChapterTitle(section?.title||t('全文'));
    this.root.querySelector('#reader-chapter').textContent=title;this.root.querySelector('#reader-footer-chapter').textContent=title;
    this.renderMarks();clearTimeout(this.positionTimer);this.positionTimer=setTimeout(()=>this.persist(),350);
  }
  persist(){if(this.id&&this.position){const workspace=this.workspace();workspace.readerPositions={...workspace.readerPositions,[this.id]:this.position};this.save();}}
  toggleOutline(){if(this.pdfPane?.pdf){this.togglePdfOutline().catch(this.fail);return;}const existing=this.root.querySelector('.reader-outline');if(existing){existing.remove();return;}this.chrome(true);const panel=document.createElement('aside');panel.className='reader-outline';panel.innerHTML=`<header><strong>${t('章节目录')}</strong><button data-reader-close aria-label="${t('关闭')}">${icon('close')}</button></header><input type="search" placeholder="${t('筛选章节标题')}"><div></div>`;const render=()=>{const query=panel.querySelector('input').value.toLowerCase();panel.querySelector('div').innerHTML=(this.chapters||[]).filter(s=>s.title.toLowerCase().includes(query)).map(s=>`<button data-reader-offset="${s.offset}" data-user-content>${this.escape(s.title)}</button>`).join('');};panel.querySelector('input').oninput=render;panel.onclick=e=>{if(e.target.closest('[data-reader-close]'))panel.remove();const button=e.target.closest('[data-reader-offset]');if(button){this.position={offset:Number(button.dataset.readerOffset)};this.layout();panel.remove();this.chrome(false);this.persist();}};render();this.root.querySelector('.reader-document').append(panel);}
  async togglePdfOutline(){const existing=this.root.querySelector('.reader-outline');if(existing){existing.remove();return;}this.chrome(true);const pane=this.pdfPane,epoch=this.epoch,items=await pane.outline();if(epoch!==this.epoch)return;const panel=document.createElement('aside');panel.className='reader-outline';panel.innerHTML=`<header><strong>${t('章节目录')}</strong><button data-reader-close aria-label="${t('关闭')}">${icon('close')}</button></header><div>${items.map((item,i)=>`<button data-pdf-chapter="${i}">${this.escape(item.title)}</button>`).join('')||t('此 PDF 未提供目录')}</div>`;panel.onclick=e=>{if(e.target.closest('[data-reader-close]'))panel.remove();const b=e.target.closest('[data-pdf-chapter]');if(b){pane.page=items[Number(b.dataset.pdfChapter)].pdfPage;pane.render().catch(this.fail);panel.remove();this.chrome(false);}};this.root.querySelector('.reader-document').append(panel);}

}
