import {parseVela,velaText,configFolder,readable,GLOBAL_VELA_PATH,readingLayoutDefaults} from './vela.mjs';
import {documentPath} from './workspace.mjs';
import {t} from './i18n.mjs';

export function renderVelaEditor({root,doc,workspace,escape:esc,onSave}){
  root.className='vela-preview';let config;
  try{config=parseVela(doc.text);}catch(error){root.innerHTML=`<p class="error">${esc(error.message)}</p><p>${t('配置无效，请切换源码修复。')}</p>`;return;}
  const global=documentPath(doc)===GLOBAL_VELA_PATH,folder=global?'':configFolder(documentPath(doc));
  const available=workspace.documents.filter(file=>readable(file)&&(!folder||documentPath(file).startsWith(folder+'/'))).map(file=>documentPath(file).slice(folder?folder.length+1:0));
  const files=[...new Set([...available,...config.reading.files])].sort((a,b)=>a.localeCompare(b));
  const labels={lineHeight:'行距',marginTop:'上边距',marginBottom:'下边距',marginLeft:'左边距',marginRight:'右边距'};
  root.innerHTML=`<form id="vela-form" class="vela-config"><header class="vela-config-header"><span class="vela-config-mark">.vela</span><div><h2>${t(global?'全局阅读配置':'工作区配置')}</h2><small data-user-content>${esc(folder||t('内部文件夹'))}</small></div></header><div class="vela-config-grid"><section class="vela-card"><h3>${t('名称与章节')}</h3><label>${t('工作区名称')}<input name="name" value="${esc(config.name)}" maxlength="160" required></label><label>${t('标题模板')}<textarea name="titleTemplates" rows="4" placeholder="Episode {number}: {title}">${esc(config.titleTemplates.join('\n'))}</textarea><small>${t('每行一个模板，使用 {序号}、{标题} 或 {number}、{title}。')}</small></label></section><section class="vela-card"><h3>${t('阅读排版')}</h3><div class="vela-layout-fields"><label>${t('文字字号')}<input name="fontSize" type="number" min="10" max="40" required value="${config.fontSize}"></label>${Object.keys(readingLayoutDefaults).map(key=>`<label>${t(labels[key])}${key==='lineHeight'?'':' (px)'}<input name="${key}" type="number" min="${key==='lineHeight'?1:0}" max="${key==='lineHeight'?3.5:240}" step="${key==='lineHeight'?.1:1}" required value="${config.reading.layout[key]}"></label>`).join('')}</div><div class="vela-layout-sample"><article><strong>${t('第一章 航程')}</strong><p>${t('文字与留白共同构成阅读节奏。调整排版后，阅读页面会使用这些设置。')}</p></article></div></section><section class="vela-card vela-files"><div class="vela-files-heading"><h3>${t('阅读文件')}</h3><output id="vela-file-count"></output></div><div class="vela-file-tools"><input id="vela-file-search" type="search" placeholder="${t('搜索文稿…')}" aria-label="${t('搜索文稿')}"><button type="button" data-vela-select="all" class="secondary">${t('全选')}</button><button type="button" data-vela-select="none" class="secondary">${t('清空选择')}</button></div><div class="vela-file-list">${files.map(path=>`<label class="checkbox vela-file" data-vela-path="${esc(path.toLowerCase())}"><input name="readingFiles" type="checkbox" value="${esc(path)}" ${config.reading.files.includes(path)?'checked':''}><span data-user-content>${esc(path)}</span>${available.includes(path)?'':`<small>${t('文件不存在')}</small>`}</label>`).join('')||`<p>${t('暂无文件')}</p>`}</div></section></div><footer class="vela-config-actions"><p class="error" id="vela-error" role="alert"></p><button class="primary">${t('保存配置')}</button></footer></form>`;
  const form=root.querySelector('form'),checks=[...form.querySelectorAll('[name=readingFiles]')];
  const count=()=>root.querySelector('#vela-file-count').textContent=`${checks.filter(input=>input.checked).length} / ${files.length}`;
  const preview=()=>{const sample=root.querySelector('.vela-layout-sample article'),data=new FormData(form);sample.style.fontSize=Math.max(10,Math.min(22,Number(data.get('fontSize'))))+'px';sample.style.lineHeight=data.get('lineHeight');for(const side of ['Top','Bottom','Left','Right'])sample.style['padding'+side]=Math.min(36,Math.max(0,Number(data.get('margin'+side)))/2)+'px';};
  form.oninput=()=>{count();preview();};count();preview();
  root.querySelector('#vela-file-search').oninput=e=>{const query=e.target.value.toLowerCase();root.querySelectorAll('[data-vela-path]').forEach(label=>label.hidden=!label.dataset.velaPath.includes(query));};
  root.querySelectorAll('[data-vela-select]').forEach(button=>button.onclick=()=>{for(const input of checks)if(!input.closest('label').hidden)input.checked=button.dataset.velaSelect==='all';count();});
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('footer button');button.disabled=true;try{const data=new FormData(form),layout={...config.reading.layout};for(const key of Object.keys(readingLayoutDefaults))layout[key]=Number(data.get(key));const next={...config,name:data.get('name').trim(),fontSize:Number(data.get('fontSize')),titleTemplates:data.get('titleTemplates').split(/\r?\n/),reading:{...config.reading,files:data.getAll('readingFiles'),layout}};if(global)next.scope='global';await onSave(velaText(next));}catch(error){root.querySelector('#vela-error').textContent=error.message;}finally{button.disabled=false;}};
}
